### ISSUE TITLE
doom-one region background colour

### ISSUE THREAD

**Issue by ryankask** [hlissner/emacs-doom-themes#100]
I've noticed that if I mark a few words on a line it's very difficult to distinguish the region:

![2017-08-11 at 09 46](https://user-images.githubusercontent.com/81891/29206483-0be5c012-7e7a-11e7-88e3-eb8b360754b9.png)

Do you have any suggestions for how to improve the visibility of the region?

**Comment by ryankask** [comment]
I've changed the background colour to `(doom-lighten bg 0.1)` which effectively reverts the recent change in b83b2b5e8a4da14c62aad4ecd5c187873a3def2d

**Comment by hlissner** [comment]
I've gone the opposite route and made region 5% brighter. This looks fine as far as my eyes can discern (across 3 monitors), so I'll consider this resolved for now, but feel free to reopen this if the contrast isn't enough.

**Comment by ryankask** [comment]
Thanks! I've removed my customisation
