### ISSUE TITLE
hl-line uses same color as background

### ISSUE THREAD

**Issue by drrlvn** [hlissner/emacs-doom-themes#107]
This makes `hl-line` essentially do nothing.

**Comment by hlissner** [comment]
Are you using `doom-one` or `doom-one-light`?

**Comment by spatz** [comment]
Using `doom-one`.

**Comment by hlissner** [comment]
This should be resolved as of https://github.com/hlissner/emacs-doom-themes/commit/1b019fc9b471d4a81ee1e9d0308169571c094b24. I'll consider this resolved for now. Reopen this if that isn't the case.
