### ISSUE TITLE
Helm colors don't have enough contrast

### ISSUE THREAD

**Issue by jonathanj** [hlissner/emacs-doom-themes#109]
Using `doom-vibrant` there is very little contrast in helm. I'd greatly appreciate if the active row could have a slightly lighter background color and maybe adjust the text color. If the use of bold is disabled in the theme, then some selected helm items are indistinguishable from unselected items.

Here the first item is selected (see "1/6" in the mode line):
![image](https://user-images.githubusercontent.com/112166/31285194-03ef6eae-aabb-11e7-8e54-024813942062.png)

Here the third item is selected (see "3/6" in the mode line):
![image](https://user-images.githubusercontent.com/112166/31285437-922ecf8e-aabb-11e7-86cc-d2fd14c8bc6c.png)

So here you can see that filenames are very slightly dimmer than directories and that selected directories are indistinguishable from unselected directories.

The background highlight as seen in company-mode pseudo tooltips seems excellent:
![image](https://user-images.githubusercontent.com/112166/31285529-d6bac298-aabb-11e7-90a4-5c2285a794f5.png)

**Comment by jonathanj** [comment]
I just wanted to clarify something: I didn't investigate the other doom themes, it's possible this may apply to others.

**Comment by hlissner** [comment]
My bad, this was certainly an oversight (I don't use helm). This did affect all Doom's themes, but this should be fixed now. Let me know if that isn't the case!

**Comment by jonathanj** [comment]
You're awesome, thank you!

**Comment by ohshane71** [comment]
can I ask what font you are using? thanks.
