### ISSUE TITLE
hl-line-mode doesn't work in dired 

### ISSUE THREAD

**Issue by amosbird** [hlissner/emacs-doom-themes#110]
Current line isn't highlighted in `dired` after enabling `hl-line-mode`.

**Comment by hlissner** [comment]
This is more an issue with solaire-mode's `solaire-mode-swap-bg` function. I've pushed a fix for it in https://github.com/hlissner/emacs-solaire-mode/commit/ce91b8709124738abb4a1612d4801e16f1d0faec

Let me know if that resolves your issue!

**Comment by amosbird** [comment]
hi, um i've removed solaire-mode since it's weird in terminal emacs anyway :)
