### ISSUE TITLE
org-mode: Invisible headline when tagged with :ARCHIVE:

### ISSUE THREAD

**Issue by mpolden** [hlissner/emacs-doom-themes#111]
When a headline in org-mode is tagged with `:ARCHIVE:`, the headline is invisible when using the `doom-one` theme.

Org file:
```
* Tasks
** Task one
* Archived Tasks                                                    :ARCHIVE:
```

is displayed like this:
<img width="325" alt="screen shot 2017-10-25 at 21 28 38" src="https://user-images.githubusercontent.com/174496/32018882-9fa470e6-b9cb-11e7-8154-1ff7a84cec4e.png">

While the default theme displays it like this:
<img width="629" alt="screen shot 2017-10-25 at 21 28 58" src="https://user-images.githubusercontent.com/174496/32018898-ae5b9bf0-b9cb-11e7-8d9f-491b16c684d1.png">

This seems to be the case for all Doom themes, except `doom-nova`, `doom-molokai` and `doom-one-light`.

**Comment by mpolden** [comment]
Seems to be due to this face: https://github.com/hlissner/emacs-doom-themes/blob/d91f72b83ec22f1620372574582e163f921e6796/doom-themes-common.el#L774

Using `(set-face-attribute 'org-archived nil :foreground nil)` as a workaround for now.

**Comment by hlissner** [comment]
Sorry for the long wait. This should be fixed as of https://github.com/hlissner/emacs-doom-themes/commit/e2461667e612f7665c42fc5e974f366dd9dc59ef. Let me know if it persists.

**Comment by mpolden** [comment]
Thanks, that fixed the issue.
