### ISSUE TITLE
if the first char of line is underlined, then the line number also will be underlined.

### ISSUE THREAD

**Issue by ichirika** [hlissner/emacs-doom-themes#114]
![123](https://user-images.githubusercontent.com/16498050/32403067-ab614c6c-c16c-11e7-8df7-8a9635c1b3ef.png)

in my config, i set highlight parens to be underlined, 
but when its at the first char of line, the line number also will be underlined.

**Comment by hlissner** [comment]
This should be fixed as of https://github.com/hlissner/emacs-doom-themes/commit/f1d134eb49b408eb3a429a71c5a73b8e1b32ff51. Please update and let me know.

**Comment by ichirika** [comment]
@hlissner  Fixed.!! good job ! 
love your work!expecting new themes from you xDD
