### ISSUE TITLE
Highlight-Indentation missing

### ISSUE THREAD

**Issue by r0m4n27** [hlissner/emacs-doom-themes#115]
You can't see the indentations with the doom-themes.
![2017-11-04-123438_1920x1080_scrot](https://user-images.githubusercontent.com/12500244/32405003-db6da9f6-c15c-11e7-80ce-62fafefabb92.png)
(Left: doom-vibrant Right: wombat)

**Comment by hlissner** [comment]
Are you using `solaire-mode-swap-bg` without `solaire-mode`? It would appear that way just eyeballing the screenshot, which could cause this issue.

**Comment by r0m4n27** [comment]
No, but after I tried it with `solaire-mode` I could see the indentations.
