### ISSUE TITLE
terminal true color compatibility.

### ISSUE THREAD

**Issue by amosbird** [hlissner/emacs-doom-themes#121]
Emacs 26 has true color support. It seems doom theme acts a bit different in GUI and a true color terminal.

Left one is GUI and right one is terminal.
![img-2017-11-16-011814](https://user-images.githubusercontent.com/5085485/32850436-bfb9dc7c-c9f7-11e7-94f0-e7b8c313f06c.png)

**Comment by hlissner** [comment]
Sorry for the late reply! I'm not sure how much I can do about that. My themes use min-color classes to assign colors, so it is up to Emacs to use the most accurate color for that session. e.g. In doom-one, `base1` is: `("#1c1f24" "#1e1e1e" "brightblack")`

So if base1 is used in a face, e.g. 

```emacs-lisp
(font-lock-comment-face :foreground base1)
```

This will expand to

```emacs-lisp
(font-lock-comment-face
 ((((class color) (min-colors 257)) (:foreground "#1c1f24"))
  (((class color) (min-colors 256)) (:foreground "#1e1e1e"))
  (((class color) (min-colors 16))  (:foreground "brightblack"))))
```

This means that it is up to Emacs to deliver the correct color depending on the current session's color support, and not really up to me.

In a true color session, whether it's in the terminal or GUI, you _should_ get the `#1c1f24`. Is that not the case?

**Comment by hlissner** [comment]
Is this still an issue? I think this may be a duplicate of #89, which has some information about true colors in the terminal. Unfortunately, there is little I can do about the minor discrepancies between true-color terminals and GUI emacs. If it is misinterpreting the color classes, then that may be an Emacs issue.

If this isn't an issue, I'll go ahead and close this in a couple days.

**Comment by amosbird** [comment]
Ah, that's fine :-)
