### ISSUE TITLE
Problem with company popup on peacock theme 

### ISSUE THREAD

**Issue by justbur** [hlissner/emacs-doom-themes#122]
I like the new theme, but the company popup is unreadable

![screen shot 2017-11-15 at 2 33 47 pm](https://user-images.githubusercontent.com/2208382/32856261-4ccafee2-ca12-11e7-9c86-ac773431a38e.png)

**Comment by hlissner** [comment]
Sorry for only getting to this now, but as of https://github.com/hlissner/emacs-doom-themes/pull/123/commits/e66af45175ba22fc4e2db0021665081d5f5d9feb this should be fixed. Feel free to reopen this if that isn't the case!
