### ISSUE TITLE
Problem with terminal mode and spaceline

### ISSUE THREAD

**Issue by KrullBorg** [hlissner/emacs-doom-themes#124]
terminal mode
![schermata da 2017-11-16 10-26-34](https://user-images.githubusercontent.com/4976455/32883857-d2c09c2c-cab8-11e7-9fbd-6acc3f6115ab.png)
gui mode
![schermata da 2017-11-16 10-28-42](https://user-images.githubusercontent.com/4976455/32883916-f9ff1ee4-cab8-11e7-9362-ab7ceba2ea9d.png)

**Comment by hlissner** [comment]
As of https://github.com/hlissner/emacs-doom-themes/commit/9c2a4a54989af16f01ca5b08bf8d48f2a3534227 I've removed the powerline and spaceline faces that could be causing this. Could you see if this solves your problem? If not, feel free to reopen this.

**Comment by drrlvn** [comment]
I think this change made the mode line yellow instead of blue for me.

**Comment by KrullBorg** [comment]
for me worked (no colors) thanks

**Comment by hlissner** [comment]
@drrlvn Those are the default colors of powerline/spaceline. I'll try to figure out better integration with spaceline/powerline, but for the time being I've left them to their defaults.

**Comment by dagnachewa** [comment]
@drrlvn hello, my modeline looks like the one you posted, I use doom-one but, I have yellow color
