### ISSUE TITLE
doom-one theme: modeline is blue, really blue

### ISSUE THREAD

**Issue by ghost** [hlissner/emacs-doom-themes#125]
When I start Emacs with doom-one theme, the modeline is blue. I need to define another theme and choose again doom-one to correct this problem temporarily.

**Comment by hlissner** [comment]
Sorry for the incredibly late reply. Am I right to assume you are an Emacs daemon or terminal user?

**Comment by Postroutine** [comment]
Emacs daemon user, yes.

**Comment by hlissner** [comment]
Sorry for the late reply.

This is actually a known issue with how Emacs initializes themes in daemon sessions. [I talked about it (and a workaround)](https://github.com/hlissner/emacs-doom-themes/issues/73#issuecomment-312319122) in #73.

Could you give that a try and let me know if it solves your issue?

**Comment by c0001** [comment]
@hlissner 

Yes it worked for me and I found this forcting method will let the frame blinking for a moment with start new gui with 'emacsclinet -c'. 

Can you fix it or upgrade this method for perfect be?

**Comment by hlissner** [comment]
Unfortunately, if there is a way to avoid the blink, I don't know it. Reloading the theme causes Emacs to redraw, and I'm pretty sure it's unavoidable.

However, I have changed the code slightly:

```elisp
(defun doom|init-theme ()
  "Set the theme and load the font, in that order."
  (load-theme 'doom-one t)
  (add-hook 'after-make-frame-functions #'doom|init-theme-in-frame))

(defun doom|init-theme-in-frame (frame)
  "Reloads the theme in new daemon or tty frames."
  (when (or (daemonp) (not (display-graphic-p)))
    (with-selected-frame frame
      (doom|init-theme))))

(add-hook 'emacs-startup-hook #'doom|init-theme)
```

Perhaps it will work better for you.

**Comment by vodik** [comment]
The key to avoiding the blink is that `load-theme` should be called once and only once inside `init-theme-in-frame`. The first time the hook it called, the theme is properly applied and will work for all future frames. Every subsequent call reloads the theme and causes the flickering.

Try this:

```elisp
(defun doom|init-theme ()
  (load-theme 'doom-one t)
  (load-theme 'airline-doom-one t))

(defun doom|init-theme-in-frame (frame)
  (with-selected-frame frame
    (doom|init-theme))

  ;; Unregister this hook once its run
  (remove-hook 'after-make-frame-functions
	           'doom|init-theme-in-frame))

(if (daemonp)
    (add-hook 'after-make-frame-functions
	          'doom|init-theme-in-frame)
  (doom|init-theme))
```

**Comment by hlissner** [comment]
@vodik the problem is how you create that first frame. If you create a terminal frame (`emacsclient -nw`), your emacs session is initialized with a terminal rendering of the theme. Start a graphical frame (`emacsclient -c`) and you get the opposite. Only load the theme once snd you’re stuck with one or the other.

If you can keep to one or the other, your solution works, but if you use them interchangeably, you have issues. Like, for instance, when you run a daemon server which you use gui frames for at home and terminal frames for from abroad (e.g. through ssh).

Perhaps a better approach is reload the theme, but only when a new frame type is detected?

**Comment by vodik** [comment]
Would you want to put this in a FAQ on the README? I can do the PR if you'd like.

**Comment by vodik** [comment]
Well honestly, my terminal session looks like its rendering correctly, for what its worth.

**Comment by vodik** [comment]
> Perhaps a better approach is reload the theme, but only when a new frame type is detected?

I like this idea, might not be a bad idea to publish it as its own package. Seems like its a general emacs problem.

**Comment by hlissner** [comment]
As of 1cdc201, this issue should be resolved. Feel free to reopen this if that isn't the case.
