### ISSUE TITLE
M-x Broken in ivy

### ISSUE THREAD

**Issue by mantlepro** [hlissner/emacs-doom-themes#127]
On a clean install, `M-x` says

    Wrong type argument: commandp, counsel-M-x

in minibuffer.

Switching to helm fixes it

**Comment by hlissner** [comment]
I think you meant to post this to [hlissner/doom-emacs](https://github.com/hlissner/doom-emacs).

See [this issue](https://github.com/hlissner/doom-emacs/issues/286) for a workaround while I address it. I will close this since it isn't relevant to this project.

**Comment by mantlepro** [comment]
My mistake! Meant to head over to [hlissner/doom-emacs](https://github.com/hlissner/doom-emacs) but got distracted and posted here by accident. Taking a look at [Issue 286](https://github.com/hlissner/doom-emacs/issues/286) for the workaround.

Thanks for for all your work on doom-emacs.
