### ISSUE TITLE
Mail side pane

### ISSUE THREAD

**Issue by jwintz** [hlissner/emacs-doom-themes#128]
Hello,

Not an issue, just wanted to share a mail side pane implementation inspired by `doom-themes-neotree`. It borrows code from `neotree` and uses `mu4e-maildirs-extension`.

![screen shot 2017-12-11 at 13 58 12](https://user-images.githubusercontent.com/3277054/33835860-13d716d6-de88-11e7-9fb4-49360dd3be8c.png)

Should someone be interested, I can turn it into a `doom-theme` layer or into a single package.

**Comment by rakanalh** [comment]
Off-topic: Might i say, this looks awesome and the font is amazing!

**Comment by hlissner** [comment]
That looks great! I'm definitely interested. I think it'd be better as its own package, if possible -- I wouldn't want to monopolize it.

**Comment by jwintz** [comment]
@rakanalh, @hlissner many thanks.

The regular font is Source Code Pro and the glyphs are provided by all-the-icons.

Henrik, I like your spirit but I doubt the monopole is significant. Few of us still use Emacs for mail, fewer with mu4e.

As regarding to turn it into a single package, 95% of the code is the (awesome) window management from neotree. It would be great if the author of emacs’ neotree split its package into two: the single side window management, and the filling of the buffer WRT/ the file system.

Besides, the contribution is very small: just a hack on `mu4e-maildirs-extension` hook, that you can see in the screenshot (plus some former setup).

**Comment by hlissner** [comment]
It's just that some time ago I was looking for a plugin exactly like this. It'd be nice to have it without being locked into doom-themes. That said, it's better that it exists at all! So very well, I'd be happy to bring it into doom-themes. Do you have the code somewhere I can see? Or can you make a PR for it? Either into `doom-themes-neotree.el` or `doom-themes-mu4e.el`.

**Comment by jwintz** [comment]
Here's the current implementation: https://github.com/jwintz/prolusion/blob/develop/prolusion-core/prolusion-mail.el.

I won't have much time until the end of the year but I'll definitely turn it into either a package or a `doom-themes-mu4e.el` ASAP.

**Comment by jwintz** [comment]
Ok, after 10 years tweaking my .emacs.d, I finally took the decision to switch to `doom`. Not a VI user however, I knowing the learning curve is steep, I'll keep trying, but from what I've seen, its emacs lisp is awesome and inspiriting, the startup time cannot be compared to any other setup. Love makefile system.

Once I'll have it in hands, I'll PR directly into `emacs-doom`.

So far I even do not know how to set my leader key for a vanilla emacs experience, after commenting out `evil` in my init.el. Even the semantic of a leader key is foreign to me since it's not pure emacs.

**Comment by ema2159** [comment]
> Hello,
> 
> Not an issue, just wanted to share a mail side pane implementation inspired by `doom-themes-neotree`. It borrows code from `neotree` and uses `mu4e-maildirs-extension`.
> 
> ![screen shot 2017-12-11 at 13 58 12](https://user-images.githubusercontent.com/3277054/33835860-13d716d6-de88-11e7-9fb4-49360dd3be8c.png)
> 
> Should someone be interested, I can turn it into a `doom-theme` layer or into a single package.

Hi! Have you implemented this yet in a package? I'm willing to help

**Comment by ekhall** [comment]
Also very interested in this. Any gists or repos where this is available?

**Comment by jesusbv** [comment]
Hi @jwintz, it looks quite nice.

Any news on this ? I took a look in [emacs-doom](https://github.com/hlissner/doom-emacs) and nothing about this there.
Maybe, share a gist/snippet so contributions can be made ?

**Comment by jwintz** [comment]
Hi @jesusbv ,

Unfortunately I do not have this code anymore. I shared it with @hlissner but it’s been years ago, it did not survive my previous machine ;-)

For the record, it borrowed some code from `neotree` for the side pane management with a fork of `mu4e-maildir-extensions` inside it.

At the time, the popup system of doom was managed by shackle but constantly evolving, so I had plan to adapt it later on, but got very very busy at work, which I’m still.

I think that @tecosaur is coming up with something great by the way. (Yes I'm still on `doom`'s Discord everyday).

Best.
