### ISSUE TITLE
Variable org-highlight-links obsolete in Emacs 25.3.1 

### ISSUE THREAD

**Issue by cybergoll** [hlissner/emacs-doom-themes#130]
Hello,

I am a recent Emacs user (ver 25.3.1 on MacOS High Sierra, installed from emacsformacosx.com) and after I started using doom-themes (ver 20180101.2140 installed via melpa) including the modifications for org-mode (doom-themes-org-config), I got the following error when opening an org file : 

```
Debugger entered--Lisp error: (void-variable org-highlight-links)
  doom-org-custom-fontification()
```

This resulted, among other things, in hyperlinks not being underlined and not working correctly in org-mode.

The problem was that for my Emacs installation, the variable org-highlight-links had been replaced by the variable org-activate-links. 
I tried to replace directly the faulty variable name directly in the file doom-themes-org.el but this would fix the issue only after evaluating the modifications in emacs, not when starting a new session (need to recompile the files ? sorry for my lack of knowledge).

In the meantime, adding the following alias in my .emacs file seems to do the trick : 
`(defvaralias 'org-highlight-links 'org-activate-links)
`

**Comment by hlissner** [comment]
Good catch! I have pushed the fix.

You are correct, `org-highlight-links` doesn't exist in the earlier versions of Org (like the one included with Emacs <= 25.3). I use Emacs 26, which has a much more recent version.
