### ISSUE TITLE
Solarized Light, anyone interested? ;-)

### ISSUE THREAD

**Issue by fuxialexander** [hlissner/emacs-doom-themes#131]
![image](https://user-images.githubusercontent.com/8258908/34656989-9cd6c3fc-f45c-11e7-8673-7409ba9c9456.png)
![image](https://user-images.githubusercontent.com/8258908/34657044-1097b260-f45d-11e7-9e6a-06de0a4281ab.png)
![image](https://user-images.githubusercontent.com/8258908/34686512-bd95a07e-f4e6-11e7-8e82-3bbf6798f259.png)

**Comment by hlissner** [comment]
You are a wizard, good sir. I am definitely interested!

**Comment by fuxialexander** [comment]
Seems my commit history is not well separated that a pull request can be created only for the solarized light theme. So please just check it out [here](https://github.com/fuxialexander/emacs-doom-themes/blob/master/themes/doom-solarizedlight-theme.el). Feel free to copy/modify them.

I also have some customized face for `org` and `notmuch` in the `doom-themes-common.el`.  Check them out if you are interested ;-).

**Comment by fuxialexander** [comment]
@hlissner There is a `org-level-9` in just updated doom-themes-common.el, typo maybe?

**Comment by hlissner** [comment]
Whoops! Typo indeed. 

I've mostly merged your changes, but it needs more testing. I've cut down a bit on the custom fonts (as much as I'd love to include them).

Your mods to twittering look fantastic, by the way. Great work! I may pull a great deal fo that into Doom emacs!

**Comment by hlissner** [comment]
@fuxialexander How did you do the dividers after each tweet? I see you have a `twitter-divider` face, but I can't find a definition for it anywhere.

**Comment by fuxialexander** [comment]
[Here](https://github.com/fuxialexander/doom-emacs-private-xfu/blob/44c1ae640b087b89129676f0a2f0fd83cff3b5d4/twitter/config.el#L7)

**Comment by hlissner** [comment]
There we go! 

> I'm not sure how to let it pick the color dynamically using defface...

Perhaps doom-themes' api could help? They can look up theme vars from outside themes:

```emacs-lisp
(doom-darken 'vertical-bar 0.2)
(doom-color 'vertical-bar)
(doom-blend 'red 'blue 0.4)

(defface twitter-divider
  `((t (:underline (:color ,(doom-darken 'vertical-bar 0.2)))))
  "test"
  :group 'twittering-mode)
```

**Comment by fuxialexander** [comment]
Wow cool! Thanks for the bit of elisp-fu!

**Comment by teesloane** [comment]
this looks uhhhhhh-mazing. Can't wait to use it.

**Comment by dsdshcym** [comment]
Any plans for solarized-dark theme?

**Comment by fuxialexander** [comment]
@dsdshcym well I actually didn't planned to do that as I don't like it's color. Although I think is very easy to do: just replace ~10 color in the theme file and you are done.
