### ISSUE TITLE
setting org-fontify-done-headline to nil doesn't take effect

### ISSUE THREAD

**Issue by dsdshcym** [hlissner/emacs-doom-themes#132]
I want to revert this setting made by doom-themes but there seems to be some changes in `doom-org-custom-fontification` that doesn't respect this setting.

**Comment by hlissner** [comment]
Sorry for the late response! I've changed the org config to set its variables earlier (rather than when org is loaded), which will prevent it from overwriting your customization. Let me know if that resolves the problem.

**Comment by dsdshcym** [comment]
Sorry, it's still not fixed yet.

I found that these settings are also set in doom-themes-common:
https://github.com/hlissner/emacs-doom-themes/blob/master/doom-themes-common.el#L881-L883

**Comment by hlissner** [comment]
And fixed! Sorry about that, I forgot about those.

**Comment by UndeadKernel** [comment]
I believe this issue is back.
With the latest changes, setting `org-fontify-done-headline` to `nil` does not work. The call to ` doom-org-custom-fontification` somehow still fontifies the entire headline.
