### ISSUE TITLE
No longer themes spaceline

### ISSUE THREAD

**Issue by cmacrae** [hlissner/emacs-doom-themes#134]
Yo @hlissner  👋 

Thanks very much for your brilliant themes!

I use spaceline with my configuration. It used to work nicely with `doom-one`, but after updating my packages in the new year, it seems it no longer affects the modeline, which results in a pretty garish colour combination.  

Any ideas why this might have stopped working? I didn't change any of my configuration for this to start happening, and I've tried bootstrapping from a completely clean slate (delete all state other than my config so packages/config is evaluated from scratch).  

If there's any debug info I can provide, please let me know.  

Thanks in advance.

**Comment by hlissner** [comment]
Thanks for the kind words! I suspect https://github.com/hlissner/emacs-doom-themes/commit/9c2a4a54989af16f01ca5b08bf8d48f2a3534227 is the reason. I removed the custom spaceline faces and left them to their defaults to fix #124 (which I can imagine clash with doom-themes). 

I figured it best to leave it to the user to customize their spaceline configs (and as I'm not a spaceline user, I know precious little about the package).

That said, I'll look into spaceline again over the weekend to see if I can figure out some decent defaults.

**Comment by cmacrae** [comment]
Yeah, I think you're right - that's what did it. 
Ah great, thank you very much - that'd be great!  

Just waiting on the doom modeline to be available as a package, at which point I'll likely drop spaceline 😉

**Comment by jwintz** [comment]
Love the new `doom-nord`  theme, however, its modelines are ugly, and the original palette is not respected.

I'll try the vanilla one to see if I get better results (should it work with the AFAIK mandatory `solaire-mode`).

**Comment by hlissner** [comment]
Sorry for a tremendously late reply. As of de75e44 I've added some spaceline support, but also, [doom-modeline](https://github.com/seagle0128/doom-modeline) has been out for a while. In any case, I'll consider this issue resolved, but feel free to follow up here if you have suggestions or think this needs more work. Thanks for bringing it to my attention!
