### ISSUE TITLE
Non-focused statusbar have a strong blue at doom-vibrant and doom-one

### ISSUE THREAD

**Issue by ryukinix** [hlissner/emacs-doom-themes#138]
I don't like that very much, how I can make that color more soft? Probably is some face attribute, but the correct name would be a nice help.

![image](https://user-images.githubusercontent.com/7642878/35790269-15a85c36-0a20-11e8-890c-a58c5b0b3a66.png)

Thanks. I appreciate the well made themes, this was a long journey until finish here with the doom-themes.

**Comment by hlissner** [comment]
You appear to have a customized mode line. Those blue segments are typically caused by a custom modeline segment that doesn't update itself when the window is no longer selected, which isn't something the theme can necessarily fix.

Do you have your modeline config up somewhere where I can see it?

**Comment by ryukinix** [comment]
I fixed with your suggestion, thanks. There is some garbage on my own `~/.emacs.d/custom.el`. I'm closing this since this was fixed, thanks for the quick answer/guide.

**Comment by ryukinix** [comment]
Sorry for this, but for some reason this behavior come back. My personal setup is host in [ryukinix/dotfiles](https://github.com/ryukinix/dotfiles/tree/master/.emacs.d/personal) where I use with the Prelude config for emacs.

My custom.el is that: `curl http://ix.io/Fki`

**Comment by ryukinix** [comment]
A weird thing: thins seems to happen only when I use the daemon of emacs... which is even more bizarre. If attach my frame-session by emacsclient on the daemon I get this issue, but if I call directly /bin/emacs works as expected.

![image](https://user-images.githubusercontent.com/7642878/35832204-1fe1c6f2-0aab-11e8-96e6-e1e5f889ad27.png)

![image](https://user-images.githubusercontent.com/7642878/35832215-2ea9e8cc-0aab-11e8-89c7-0c9660102ec3.png)


To avoid any pain to setup my environment, you can download here: https://www.dropbox.com/s/zo8g2fsluid65gy/ryukinix-emacs.d.tar.gz?dl=0

As I can seems a problem with a side-effect of loading the zenburn theme before as default of Prelude. Trying reload the theme again at customize-theme (enable doom theme) fix that, but this is a manual fix...

**Comment by ryukinix** [comment]
![image](https://user-images.githubusercontent.com/7642878/35832632-cfbe17f0-0aac-11e8-9924-61d6610c8d90.png)

This happens even with the terminal session using the daemon as well. This is really curious for me... which thing can the daemon set or do to get this behavior?

Sorry for all the flood here.

**Comment by ryukinix** [comment]
![image](https://user-images.githubusercontent.com/7642878/35832750-293162ec-0aad-11e8-849e-b79389d0d0a3.png)
 HMMMMMMMM this seems something related to the face-attribute for selection as well!

**Comment by hlissner** [comment]
Ah, I misunderstood your original problem. I am familiar with this issue. The theme has several classes for each face. Meaning the colors are different depending on how many colors your session supports.

If you load the theme while the daemon is loading, the daemon "frame" supports no colors at all, so the theme thinks your display supports the minimum number of colors, and you get these shoddy colors.

The trick is to load the theme when new frames are created, something like:

```emacs-lisp
(defun init-theme (_frame) 
  (load-theme 'doom-one t)
  (remove-hook 'after-make-frame-functions 'init-theme))

(if (daemonp)
    (add-hook 'after-make-frame-functions 'init-theme)
  (init-theme))
```

Unfortunately, I'm about to head out for several hours. I'll expand on this when I return if it isn't sufficient.

**Comment by ryukinix** [comment]
https://stackoverflow.com/questions/18904529/after-emacs-deamon-i-can-not-see-new-theme-in-emacsclient-frame-it-works-fr

Yes! Thanks, this fix all my problem. ❤️ 

Sorry again for the flood.
