### ISSUE TITLE
[BUG]Install failed

### ISSUE THREAD

**Issue by hikycool** [hlissner/emacs-doom-themes#139]
release: emacs 26.x
os: mac os
issue:
    when use 'M-x package-install doom-themes', then 'M-x doom-themes' , no such option.
    And use '(require 'doom-themes)' in '~/.emacs', it also failed.
    Any problem with my operation or your guide?

**Comment by hlissner** [comment]
`M-x doom-themes` does not exist. You first need to `(require 'doom-themes)` and then load the theme `M-x load-theme`.

If `(require 'doom-themes)` is not working, then I require more information. How does it fail? Is there an error message? Does it fail to load, or are you expecting it to load the theme with that alone?

**Comment by hikycool** [comment]
I test it in emacs release 25.3 now.
Operation:  1. M-x package-install doom-themes
                   2. write (require 'doom-themes) into .emacs file
                   3. restart emacs
error info :
Warning (initialization): An error occurred while loading ‘/Users/syu/.emacs’:
File error: Cannot open load file, No such file or directory, doom-themes

debug info:
  eval-buffer(#<buffer  *load*> nil "/Users/syu/.emacs" nil t)  ; Reading at buffer position 714
  load-with-code-conversion("/Users/syu/.emacs" "/Users/syu/.emacs" t t)
  load("~/.emacs" t t)
  #[0 "\205\266	\306=\203\307\310Q\202?	\311=\204\307\312Q\202?\313\307\314\315#\203*\316\202?\313\307\314\317#\203>\320\321\322!D\nB\323\202?\316\324\325\324\211#\210\324=\203e\326\327\330\307\331Q!\"\325\324\211#\210\324=\203d\210\203\247\332!\333\232\203\247\334!\211\335P\336!\203\201\211\202\214\336!\203\213\202\214\314\262\203\245\337\"\203\243\340\341#\210\342\343!\210\266\f?\205\264\314\325\344\324\211#)\262\207" [init-file-user system-type delayed-warnings-list user-init-file inhibit-default-init inhibit-startup-screen ms-dos "~" "/_emacs" windows-nt "/.emacs" directory-files nil "^\\.emacs\\(\\.elc?\\)?$" "~/.emacs" "^_emacs\\(\\.elc?\\)?$" initialization format-message "`_emacs' init file is deprecated, please use `.emacs'" "~/_emacs" t load expand-file-name "init" file-name-as-directory "/.emacs.d" file-name-extension "elc" file-name-sans-extension ".el" file-exists-p file-newer-than-file-p message "Warning: %s is newer than %s" sit-for 1 "default"] 7]()
  command-line()
  normal-top-level()

**Comment by hlissner** [comment]
You need either of these _before_ you do `(require 'doom-themes)`:

```elisp
(package-initialize)
```

or

```elisp
(add-to-list 'load-path "path/to/doom-themes")
```

**Comment by hikycool** [comment]
OK ,  I have got it.
Thanks for your answer
