### ISSUE TITLE
Suggestion to doom-nova theme

### ISSUE THREAD

**Issue by diegonogueira** [hlissner/emacs-doom-themes#140]
Thanks for created this version to Emacs!
I'm using spacemacs and the doom-nova theme, but some colors are not so good for me..

I changed to:

```
  (custom-theme-set-faces
   'doom-nova
   '(mode-line ((t (:background "#556873"))))
   '(hl-line ((t (:background "#556873"))))
   '(region ((t (:background "#7FC1CA" :foreground "#3C4C55"))))
   '(font-lock-type-face ((t (:foreground "#A8CE93"))))
   '(elixir-atom-face ((t (:inherit font-lock-string-face))))
   '(helm-source-header ((t (:inherit info-title-2))))
   '(helm-selection ((t (:inherit hl-line))))
   '(helm-buffer-not-saved ((t (:inherit error))))
   '(helm-buffer-process ((t (:inherit helm-buffer-size))))
   '(evil-ex-info ((t (:inherit error))))
   '(powerline-active0 ((t (:background "#899BA6"))))
   '(powerline-active1 ((t (:background "#6A7D89"))))
   '(powerline-active2 ((t (:inherit mode-line))))
   '(powerline-inactive1 ((t (:inherit mode-line-inactive))))
   '(powerline-inactive2 ((t (:inherit mode-line-inactive)))))
  )
```

What do you think? :)

**Comment by hlissner** [comment]
I've tweaked some of nova's colors. Some of these tweaks were inspired by your colors.

Unfortunately, I am not an elixir programmer. Would you mind giving me a screenshot of an elixir file where `elixir-atom-face` has an effect? It would help with a before and after screenshot; this will tell me if I can include it in doom-nova.

**Comment by diegonogueira** [comment]
before:
![screen shot 2018-02-24 at 20 57 49](https://user-images.githubusercontent.com/68256/36636418-8390505c-19a5-11e8-936d-67f09599f3b9.png)

after:
![screen shot 2018-02-24 at 21 01 33](https://user-images.githubusercontent.com/68256/36636428-ed66d726-19a5-11e8-9d8c-440781094dec.png)

:)

**Comment by hlissner** [comment]
Alright, most of your suggestions have made it into Doom, including your elixir-mode suggestions, so I'll consider this resolved.

Thank you for bringing this to my attention!
