### ISSUE TITLE
"doom-nova" face tweaks

### ISSUE THREAD

**Issue by muirrn** [hlissner/emacs-doom-themes#157]
First I want to say thanks for your themes. I appreciate the attention to detail and ease of customization.

I'm not sure if the following colors are intended or just not fine tuned yet, but these are a few things I have noticed:
- `ivy-current-match` is hard to read (background doesn't stand out)
- `region` doesn't stand out enough, esp. when selecting small regions (for my tastes at least)
- `show-paren-match/mismatch` look funny with black background

I'm no color expert, but at least temporarily I added these tweaks for my config:

```
(set-face-attribute 'ivy-current-match nil :background (doom-color 'blue))
(set-face-attribute 'region nil :background (doom-darken (doom-color 'blue) 0.45))
(set-face-attribute 'show-paren-match nil :background (doom-darken (doom-color 'violet) 0.4) :foreground (doom-color 'red))
(set-face-attribute 'show-paren-mismatch nil :background (doom-darken (doom-color 'red) 0.4) :foreground (doom-color 'cyan))
```

**Comment by hlissner** [comment]
These faces simply haven't been tuned, so I've gone through them and done so, which should resolve your issues, please update and let me know if they're satisfactory.

**Comment by muirrn** [comment]
Thank you, much improved! I really love this theme.

I've run into a few other tweakable places:
- vc-annotate  - black background on right looks funny <img width="860" alt="vc-annotate" src="https://user-images.githubusercontent.com/11356572/38031200-a1f86536-32d5-11e8-8b17-cd1ad34ca91a.png">
- diff-mode - can't read the black text (arrived at from `C-x v l (vc-print-log)` then `D` to view diff)
<img width="690" alt="diff-mode" src="https://user-images.githubusercontent.com/11356572/38031215-ae173856-32d5-11e8-9b20-43767a486588.png">
- powerline is not styled (I realize no doom themes style this mode, so maybe not something you care about)

Below is what I am playing with for powerline (I couldn't get `mode-line-buffer-id-inactive` face to do anything). Maybe it is too colorful?

```
(set-face-attribute 'powerline-active0 nil :background (doom-darken (doom-color 'blue) 0.2) :foreground (doom-color 'fg))
(set-face-attribute 'powerline-active1 nil :background (doom-darken (doom-color 'violet) 0.2) :foreground (doom-color 'fg))
(set-face-attribute 'powerline-active2 nil :background (doom-color 'base5) :foreground (doom-color 'fg))
(set-face-attribute 'mode-line-buffer-id nil :foreground (doom-color 'fg))

(set-face-attribute 'powerline-inactive0 nil :background (doom-darken (doom-color 'blue) 0.5) :foreground (doom-darken (doom-color 'fg) 0.2))
(set-face-attribute 'powerline-inactive1 nil :background (doom-darken (doom-color 'violet) 0.6) :foreground (doom-darken (doom-color 'fg) 0.2))
(set-face-attribute 'powerline-inactive2 nil :background (doom-color 'base3) :foreground (doom-darken (doom-color 'fg) 0.2))
```
<img width="1661" alt="powerline" src="https://user-images.githubusercontent.com/11356572/38031327-e7b23a5c-32d5-11e8-9d14-0c5faf307da4.png">

I've also tweaked paren-mode styling a bit:
```
(set-face-attribute 'show-paren-match nil :background (doom-color 'bg) :foreground (doom-color 'orange))
(set-face-attribute 'show-paren-mismatch nil :background (doom-darken (doom-color 'red) 0.4) :foreground (doom-color 'red))
```

**Comment by muirrn** [comment]
Also, the magit conflict styling looks a bit off

![screen shot 2018-03-30 at 8 56 10](https://user-images.githubusercontent.com/11356572/38118827-6025ead8-33f8-11e8-8f97-ccb212fec2da.png)

**Comment by muirrn** [comment]
Another issue: enh-ruby-mode operator face is not styled. I also styled the string delimiter face to be the same as string face because I think it looks funny having the quotes be a different color.

```
(doom-themes-set-faces 'doom-nova
  (enh-ruby-op-face :foreground operators)
  (enh-ruby-string-delimiter-face :inherit 'font-lock-string-face))
```

**Comment by muirrn** [comment]
I'm going to break this up into separate issues since some of these are not related to nova.
