### ISSUE TITLE
enh-ruby-mode styling

### ISSUE THREAD

**Issue by muirrn** [hlissner/emacs-doom-themes#158]
This is a ruby-mode replacement that works better in various ways. The main problem face is `enh-ruby-op-face` which defaults to something that looks pretty bad in the doom themes:

<img width="230" alt="screen shot 2018-03-31 at 16 02 00" src="https://user-images.githubusercontent.com/11356572/38160718-e846ae52-34fc-11e8-92df-432e8cabebf1.png">

The minimum styling would be to set `enh-ruby-op-face` to `operators`, but personally I think it looks funny having all your `=` signs colored, so I am using this:

```
(doom-themes-set-faces 'doom-nova
  (enh-ruby-op-face :foreground fg)
  (enh-ruby-string-delimiter-face :foreground strings)
  (enh-ruby-heredoc-delimiter-face :foreground strings)
  (enh-ruby-regexp-delimiter-face :foreground strings))
```

I prefer the operators not colored, and to make the string/regexp delimiters colored the same as the contents rather than darkened a bit. I do not have a strong opinion, so I will be satisfied as long as `enh-ruby-op-face` is set to something that looks better.

For comparison's sake, solarized styles like this:
```
`(enh-ruby-string-delimiter-face ((,class (:foreground ,yellow))))
`(enh-ruby-heredoc-delimiter-face ((,class (:inherit enh-ruby-string-delimiter-face))))
`(enh-ruby-regexp-delimiter-face ((,class (:inherit enh-ruby-string-delimiter-face))))
`(enh-ruby-op-face ((,class (:foreground ,base0))))
```
However I don't like the quotes being a different color than the string, personally.

**Comment by hlissner** [comment]
I've added `enh-ruby-mode` faces in a35d707. I _did_ end up setting enh-ruby-op-face to `operators` (for consistency), but this can be undone with:

```elisp
(set-face-foreground 'enh-ruby-op-face :foreground (doom-color 'fg))
```

I've also given enh-ruby-regexp-face (and its delimiters) a different color, since I think it should regexps should be distinct from strings.

Give it a try and let me know what you think!

**Comment by muirrn** [comment]
Looks good, thank you!
