### ISSUE TITLE
diff-context styling

### ISSUE THREAD

**Issue by muirrn** [hlissner/emacs-doom-themes#159]
The `diff-context` face is missing and makes the "context" hard to read:

<img width="690" alt="diff-mode" src="https://user-images.githubusercontent.com/11356572/38160827-5cbd8bd8-34fe-11e8-9264-3901a44d9341.png">

I'm using `(diff-context :foreground (doom-darken fg 0.1))`:

**Comment by hlissner** [comment]
Thanks for letting me know. This should be fixed as of 42c3fb6. Feel free to reopen this if that isn't the case.
