### ISSUE TITLE
smerge styling

### ISSUE THREAD

**Issue by muirrn** [hlissner/emacs-doom-themes#160]
The smerge faces look bad by default:

![screen shot 2018-03-30 at 8 56 10](https://user-images.githubusercontent.com/11356572/38161027-6dfc36ca-3502-11e8-839e-939362137fa2.png)

Am I supped to be using `(setq frame-background-mode 'dark)` to get dark mode default stylings, or have these just not been styled?

**Comment by hlissner** [comment]
You are correct. Doom-themes was missing definitions for smerge-mode faces! They've been added as of 5fe154f. Let me know that it looks alright.
