### ISSUE TITLE
vc-annotate needs styling (?)

### ISSUE THREAD

**Issue by muirrn** [hlissner/emacs-doom-themes#161]
Not sure if the background for the code is intentionally black or not:

<img width="860" alt="vc-annotate" src="https://user-images.githubusercontent.com/11356572/38161046-ce750478-3502-11e8-8b45-13ca9da2998d.png">

**Comment by hlissner** [comment]
The vc-annotate faces were designed for `doom-one`, and hadn't been updated for other themes yet. I've changed its background in dc3fd55, which should look better in all themes (though I've only tested doom-one and doom-nova so far).

Let me know if you find any issue with it!
