### ISSUE TITLE
thank you

### ISSUE THREAD

**Issue by WhosCounting** [hlissner/emacs-doom-themes#164]
These are so beautiful. I am really grateful you did those themes. Keep up the good work! 
(feel free to close or delete this "issue" obviously).

**Comment by hlissner** [comment]
Thank you, and you're very welcome! I wish I could hog all the credit, but a great deal of it is owed to the awesome folks that have contributed themes, bug reports and PRs to keep this ol' ship afloat; folks like @fuxialexander, @teesloane, @ztlevi and @emacswatcher. 

Thank you, thank them, and thank our holy father, RMS!
