### ISSUE TITLE
challenger-deep-theme has the same highlight and text color for company

### ISSUE THREAD

**Issue by mbark** [hlissner/emacs-doom-themes#169]
When autocompleting with company the highlighted word has the same text color as selection highlight which means that in some cases -- especially when only one completion is relevant -- it is impossible to tell what the alternative is, see the image below:
![screen shot 2018-04-26 at 08 57 04](https://user-images.githubusercontent.com/1579384/39290444-d2915fc0-492f-11e8-9c96-399c838665dd.png)

My emacs skills are unfortunately not good enough to make this a PR, but my temporary solution is to add this line to the theme: `(company-tooltip-selection :background (doom-darken bg 0.075))`

**Comment by hlissner** [comment]
cc24f23 should resolve this. Let me know if that isn't the case!

**Comment by mbark** [comment]
It's fixed! Thanks you 👍
