### ISSUE TITLE
neotree shows strange icons

### ISSUE THREAD

**Issue by oracleyue** [hlissner/emacs-doom-themes#179]
Strange, as shown in the figure, where I use the minimal setting you provided and nothing else. 

<img width="697" alt="screen shot 2018-05-06 at 06 48 12" src="https://user-images.githubusercontent.com/5046605/39669928-9cec8d1e-50f9-11e8-9ce3-ac28c80d339a.png">

FYI,
`all-the-icons`: 20180125.757 or 3.2.0
`doom-themes`: 20180505.911
`neotree`: 20170522.758
emacs: 25.3.1
osx: sierra

**Comment by hlissner** [comment]
Have you installed `all-the-icons`'s icon fonts? i.e. with `M-x all-the-icons-install-fonts`?

**Comment by oracleyue** [comment]
@hlissner Oh, I am soooo stupid! I forgot it....
