### ISSUE TITLE
Certain Neotree icons cannot be displayed

### ISSUE THREAD

**Issue by ppwwyyxx** [hlissner/emacs-doom-themes#180]
I've install fonts from all-the-icons, and after `  (setq doom-neotree-file-icons t)`, I can see icons for most filetypes except for certain files:
![0505-22 57 10](https://user-images.githubusercontent.com/1381301/39670354-b36e0456-50b7-11e8-9c98-2a56a6e5dae0.png)

Then I modified `modules/ui/doom/config.el` and remove the `doom-themes-neotree-config` hook, the icons for Makefile and LICENSE are back, just like the official neotree screenshot: https://github.com/jaypei/emacs-neotree/blob/dev/screenshots/icons.png 

So it seems like doom-themes-neotree has some issues with files without extensions.

**Comment by hlissner** [comment]
Is there any reason you can't use `(setq neo-theme 'icons)` instead of `doom-themes-neotree-config`?

I've been meaning to phase out support for `(setq doom-neotree-file-icons t)`, because it does little that neotree's `icon` theme can't. Rather, the purpose of `doom-themes-neotree-config` is to provide a minimalistic icon theme, like what exists in atom:

![image](https://user-images.githubusercontent.com/510883/39670928-44e29990-510f-11e8-9536-13ad85e86548.png)

This is meant as an alternative to neotree's full-blown icon theme.

**Comment by ppwwyyxx** [comment]
`(setq neo-theme 'icons)` seems to have the same issue.

**Comment by hlissner** [comment]
Even with `doom-themes-neotree-config` removed from your config?

**Comment by ppwwyyxx** [comment]
When doom-themes-neotree-config was removed things work fine.
Do you mean that I should just disable it if I want icons?

**Comment by hlissner** [comment]
Yes, if you want icons-by-filetype (like in your post), use `(setq neo-theme 'icons)`.

If you want atom-style icons (like in my post above), use

```el
(doom-themes-neotree-config)
(setq doom-neotree-file-icons 'simple)
```

**Comment by ppwwyyxx** [comment]
Thanks! I end up with
```elisp
(def-package-hook! doom-themes
  :post-config
  (remove-hook 'doom-load-theme-hook #'doom-themes-neotree-config)
)
```

**Comment by hlissner** [comment]
Oh! I wasn't aware you were a Doom user. In that case, I'd recommend doing it this way:

```el
(after! doom-themes
  (remove-hook 'doom-load-theme-hook #'doom-themes-neotree-config))
```

It is functionally equivalent, but `after!` is generally more preformant than `(def-package-hook! X :post-config ...)`.

**Comment by jupl** [comment]
I'm pretty bummed out by this move, unfortunately. If I don't use `doom-themes-neotree-config` I lose the nice customizations that were offered by doom.

<img width="217" alt="screen shot 2018-05-09 at 6 57 19 am" src="https://user-images.githubusercontent.com/2065876/39813552-7eb19a6a-5356-11e8-8387-47c218256f83.png">

However, when I use `doom-themes-neotree-config` I don't get any of the file icons that are useful at a glance.

<img width="245" alt="screen shot 2018-05-09 at 6 58 29 am" src="https://user-images.githubusercontent.com/2065876/39813553-82ab0930-5356-11e8-8b95-fe1850aea1bd.png">

Is there any way to get the best of both worlds like how it used to work?

**Comment by hlissner** [comment]
@jupl Sorry about that. To remove it entirely was too hasty a decision. I'll revisit this in the next day or two and bring `doom-themes-neotree-config` to snuff so I can restore that feature.

**Comment by rickithadi** [comment]
@hlissner  any updates on this?

**Comment by jesusbv** [comment]
Thank you for the package and the efforts on this repo @hlissner 

I would like to ask if it is possible to extend/add more icons ?

for example, without 
```emacs-lisp 
(doom-themes-neotree-config)
```
![Screenshot from 2020-12-07 11-52-21](https://user-images.githubusercontent.com/3913611/101348629-da57f200-3883-11eb-8b19-756369985f13.png)

with 

```emacs-lisp
(doom-themes-neotree-config)
(setq doom-themes-neotree-file-icons t)
```

![Screenshot from 2020-12-07 11-52-42](https://user-images.githubusercontent.com/3913611/101348716-05424600-3884-11eb-87e5-d2f15aca86fc.png)

Most of icons are there but some are missing
