### ISSUE TITLE
Set font-latex-verbatim-face

### ISSUE THREAD

**Issue by karljs** [hlissner/emacs-doom-themes#181]
By default when editing LaTeX, doom themes will make the face used for verbatim code (an environment for typesetting source code, more or less) use an ugly sans-serif font.  I'd love to see it get set to something not awful.  For inspiration, bbatsov sets it as follows for his nice solarized theme:

    font-latex-verbatim-face ((,class (:inherit fixed-pitch :foreground ,base0 :slant italic))))

**Comment by hlissner** [comment]
doom-themes doesn't have a definition for `font-latex-verbatim-face` at all, so that appears to be LaTeX-mode's default style. I've just pushed fb29315 with your suggestion. Let me know if that looks better.

**Comment by karljs** [comment]
@hlissner Thanks for the super quick response.  Yes, I think that's much better.

**Comment by hlissner** [comment]
Excellent. Thanks for letting me know!
