### ISSUE TITLE
Add monokai theme

### ISSUE THREAD

**Issue by seagle0128** [hlissner/emacs-doom-themes#184]
I love `doom-themes` very much because it makes me focus on contents.
I know `doom-molokai` is great and I like it. But I love `monokai-theme` since it's lighter and warmer.
[monokai-theme](https://github.com/oneKelvinSmith/monokai-emacs) is amazing, so is it impossible to support it in `doom-themes`?

![image](https://raw.githubusercontent.com/oneKelvinSmith/monokai-emacs/master/assets/monokai_0.png)

**Comment by ema2159** [comment]
There's a PR (#413), so it may be included soon.

**Comment by seagle0128** [comment]
Thank you.

**Comment by ema2159** [comment]
@seagle0128 given that there's been quite some interest for Monokai themes, I decided to simply transform Molokai into Monokai classic, given that the palette is the same and it's just the UI that changes.

**Comment by brunosmmm** [comment]
Why remove molokai completely? Just updated my packages and restarted to a broken setup because of this.

**Comment by ema2159** [comment]
@brunosmmm I felt it was too similar to Monokai classic, but if you want I can bring it back!

**Comment by brunosmmm** [comment]
@ema2159  It's up to you, I can use monokai just fine. Here's a side-by-side comparison to show how different they are, just for more info:

[![monomolo.png](https://i.postimg.cc/G2THN1nT/monomolo.png)](https://postimg.cc/5Y14YT0f)

**Comment by ema2159** [comment]
@brunosmmm I'll bring it back then!

**Comment by DanielRichtmann** [comment]
I'd be happy if you brought it back and just have them coexist.

**Comment by ema2159** [comment]
@brunosmmm @DanielRichtmann it's back!
