### ISSUE TITLE
Unable to see time in modeline

### ISSUE THREAD

**Issue by knjk04** [hlissner/emacs-doom-themes#185]
Emacs version: GNU Emacs 25.3.1

I can't see the time in my modeline if I activate the following in my config file 
`(display-time-mode` 1)

![1526501426_2110_16 05 2018_](https://user-images.githubusercontent.com/11173328/40141356-9f9feef0-594d-11e8-8754-584b7bfdf08c.png)

Do you know why this is the case?

**Comment by hlissner** [comment]
Do you have your config somewhere I can see it? Perhaps on github?

It _appears_ you're using a mode-line like mine. If that's the case, it is a dynamic modeline, which modes like `display-battery-mode` and `display-time-mode` cannot modify. Adding new segments depends on the precise implementation you're using, however, which I'll need to see to offer any advice.

**Comment by knjk04** [comment]
Here it is: https://github.com/knjk04/.emacs.d/blob/master/config.el.org

Oh OK, I didn't know that. Thanks for the help!

**Comment by hlissner** [comment]
Ah, I'm terribly sorry for taking so long to get around to this. Might I suggest:

```elisp
(defun *extra ()
  (when global-mode-string
    (concat (format-mode-line global-mode-string) "   ")))
```

And then add `(*extra)` to the `doom-mode-line` function. Something like:

```diff
 (defun doom-mode-line (&optional id)
   `(:eval
     (let* ((active (eq (selected-window) mode-line-selected-window))
            (lhs (list (propertize " " 'display (if active mode-line-bar mode-line-inactive-bar))
                       (*flycheck)
                       (*selection-info)
                       ;; (*anzu)
                       ;; (*iedit)
                       " "
                       (*buffer-path)
                       (*buffer-name)
                       " "
                       (*buffer-state)
                       ,(if (eq id 'scratch) '(*buffer-pwd))))
-           (rhs (list (*buffer-encoding-abbrev)
+           (rhs (list (*extra)
+                      (*buffer-encoding-abbrev)
                       (*vc)
                       "  " (*major-mode) "  "
                       (propertize
                        (concat "(%l,%c) " (*buffer-position))
                        'face (if active 'mode-line-2))))
            (middle (propertize
                     " " 'display `((space :align-to (- (+ right right-fringe right-margin)
                                                        ,(1+ (string-width (format-mode-line rhs)))))))))
       (list lhs middle rhs))))
```

Then when you activate `display-battery-mode` and `display-time-mode`, they will be in your modeline.

**Comment by hlissner** [comment]
Since this has been inactive for a while and isn't related to doom-themes, I'll consider this resolved.
