### ISSUE TITLE
The option doom-dracula-brighter-comments doesn't change the comment face

### ISSUE THREAD

**Issue by lckarssen** [hlissner/emacs-doom-themes#192]
Even though I have `(setq doom-dracula-brighter-comments t)`, the comments don't appear brighter. Setting `doom-dracula-comment-bg` does work, so I thought it had to be something else. Digging into the source I noticed that [lines 74 and 75](https://github.com/hlissner/emacs-doom-themes/blob/427ad34e8442a18b4adafe530e6827c9c3af3a04/themes/doom-dracula-theme.el#L75) are slightly different:
``` lisp
   (comments       base5)
   (doc-comments   (doom-lighten (if doom-dracula-brighter-comments dark-cyan base5) 0.25))
```
Later, in [lines 132–139](https://github.com/hlissner/emacs-doom-themes/blob/427ad34e8442a18b4adafe530e6827c9c3af3a04/themes/doom-dracula-theme.el#L132) `font-lock-comment-face` and `font-lock-doc-face` are defined (as expected) based on `comments` and `doc-comments` respectively. As a result, comments (e.g. in lisp code or LaTeX) are not brighter. 

Shouldn't the `comments` colour be defined in the same way as `doc-comments`?

Edit: indeed, adding
``` lisp
    (font-lock-comment-face :foreground (doom-lighten
                                         (if doom-dracula-brighter-comments
                                             (doom-color 'dark-cyan)
                                           (doom-color 'base5))
                                         0.25)
                            )
    )
```
to my init file works as expected.

**Comment by hlissner** [comment]
This should be fixed as of fdba37a. Feel free to reopen this if that isn't the case. Thanks for letting me know!
