### ISSUE TITLE
Add erc support

### ISSUE THREAD

**Issue by memeplex** [hlissner/emacs-doom-themes#194]
Just that, I doesn't look good now :)

**Comment by hlissner** [comment]
I've added ERC faces, but it is complete guess work (as I don't use it). Let me know what you think and if it can be improved. A screenshot would help too!

**Comment by memeplex** [comment]
Sure, later I'll take a look and tell you. But you could use the base16 tomorrow dark theme as inspiration. I'm using that and, though it's not awesome, it's quite acceptable.

**Comment by memeplex** [comment]
From a cursory inspection I can say that at least these two faces look out of place and are better set by base16 tomorrow dark:

``` elisp
'(erc-current-nick-face ((t (:foreground "#b5bd68" :weight bold))))
'(erc-timestamp-face ((t (:foreground "#8abeb7"))))
```

**Comment by hlissner** [comment]
I've added those faces, and then some, in b8353da, after playing around with ERC. I think it looks good enough to consider this resolved.

Thanks for letting me know, and for your suggestions, they were a great help!
