### ISSUE TITLE
problem with colors in challenger-deep with company-mode

### ISSUE THREAD

**Issue by Dickby** [hlissner/emacs-doom-themes#198]
in the company popup the backgroundcolor of the active selection is the same as the foreground color of the information following the candidate.
![example](https://user-images.githubusercontent.com/10100765/41193793-22687166-6c01-11e8-9301-8f793dd51010.png)

**Comment by mbark** [comment]
This seems to be the same problem as I had in #169, are you running a recent enough version to include cc24f23? For me that solved it at least.

**Comment by hlissner** [comment]
I've pushed a potential fix for this. Please update and let me know!

**Comment by Dickby** [comment]
Perfect thanks!
