### ISSUE TITLE
Variable declarations are not distinguishable.

### ISSUE THREAD

**Issue by bradyt** [hlissner/emacs-doom-themes#202]
In many languages when you have `var i` or `int i`, variable is said to be declared, and is fontified with `font-lock-variable-name-face`. This face is left indistinguishable from the rest of text by `dracula-mode`.

For example,

``` emacs-lisp
(defvar hello "")
(setq hello "world")
```

We see if we're looking for the declaration of `hello`, the syntax highlighting draws our eye to the `defvar` expression.

**Comment by hlissner** [comment]
I sympathize, it is a preference I share, but these colors were derived from the Dracula theme, where variables are intentionally indistinguishable, so I'd rather classify this a matter of personal preference and leave it to the user to change.

You can change this yourself with the following line added to your config (after you've loaded `doom-dracula`):

```elisp
(set-face-foreground 'font-lock-variable-name-face (doom-color 'violet))
```

You can use any of the colors/variables defined in [doom-dracula-theme's let-vars](https://github.com/hlissner/emacs-doom-themes/blob/master/themes/doom-dracula-theme.el#L42-L123).
