### ISSUE TITLE
font-lock-doc-face almost invisible

### ISSUE THREAD

**Issue by memeplex** [hlissner/emacs-doom-themes#205]
font-lock-doc-face inherits font-lock-comment-face but overrides the foreground color with a color that is too dark, almost indistinguishable from the default background, so docstrings are unreadable (try, for example, to read a python docstring).

This happens at least in the tomorrow night theme (don't know if the same applies to other doom themes).

**Comment by hlissner** [comment]
I don't see this. Are you using terminal or GUI emacs? 

I had a look at [your theme customizations](https://gitlab.com/memeplex/home/blob/master/.emacs.d/init.el#L115) and spotted this: https://gitlab.com/memeplex/home/blob/master/.emacs.d/init.el#L115, which appears to be setting `font-lock-doc-face` to the same color as `font-lock-comment-face`. Perhaps that is the cause?

**Comment by memeplex** [comment]
I think I did that as a workaround for this issue. I will take a look later.

**Comment by memeplex** [comment]
I'm not being able to reproduce this anymore (neither standalone, nor terminal, nor client/server). This is really weird, my other non-reproducible report (https://github.com/hlissner/emacs-doom-themes/issues/211) was closely related to this one, even the color is the same (#6a6b6a). Maybe something in my emacs daemon got broken at some point and both reports were later tainted by that problem, maybe I was using a broken development build from emacs-26 branch, I couldn't say... sorry.

**Comment by hlissner** [comment]
No problem! Perhaps this was resolved by your suggested fix in #210?

**Comment by memeplex** [comment]
Mmm, it might be so, will disable it later and see what happens.
