### ISSUE TITLE
Magit inactive bars are almost unreadable in City Lights

### ISSUE THREAD

**Issue by r-darwish** [hlissner/emacs-doom-themes#209]
![image](https://user-images.githubusercontent.com/1383193/43261050-040b2d28-90e4-11e8-8022-320bf116f89b.png)

**Comment by memeplex** [comment]
Are you using emacsclient?

This looks like another case of https://github.com/hlissner/emacs-doom-themes/issues/210.

See also https://github.com/magit/magit/issues/3526. I have been debugging the issue and now we have a clear picture of what is happening.

**Comment by r-darwish** [comment]
I don't use emacsclient. I launch Emacs 26.1 in KDE.

**Comment by hlissner** [comment]
As of 1cdc201 this should be fixed. Feel free to reopen this if that isn't the case!
