### ISSUE TITLE
cannot change linum forebackground(color) with doom-one-theme

### ISSUE THREAD

**Issue by FirstLoveLife** [hlissner/emacs-doom-themes#212]
I have tested with -Q. But no matter what I do `Linum face:`, always nothing changed.

**Comment by hlissner** [comment]
What did you try? Did you use `set-face-attribute`? `custom-set-faces`?

**Comment by FirstLoveLife** [comment]
@hlissner I have cuztomize in `Easy Customization`
![image](https://user-images.githubusercontent.com/37442588/43621532-9f25a316-970a-11e8-971c-9a81d2528632.png)

**Comment by FirstLoveLife** [comment]
Ok, it is not doom-theme's problem

**Comment by hlissner** [comment]
No problem! Glad it is fixed.
