### ISSUE TITLE
Support anzu faces

### ISSUE THREAD

**Issue by seagle0128** [hlissner/emacs-doom-themes#214]
[anzu](https://github.com/syohex/emacs-anzu) is a great package for Emacs. Can you please support `anzu` in `doom-themes`? The original faces look good but not compatible for `doom`.

**Comment by fuxialexander** [comment]
emm, I believe the anzu information is shown in doom-modeline

**Comment by seagle0128** [comment]
@fuxialexander Yes. But the default faces of anzu in the buffer are not good enough for doom themes IMO.

**Comment by seagle0128** [comment]
Actually I found a simple solution below, but not sure if add more faces.

Adding this to `doom-themes-common-faces`.
```elisp
      (anzu-replace-highlight :background base0 :foreground red :strike-through t :weight 'bold) 
      (anzu-replace-to :background base0 :foreground green :weight 'bold) 
```

**Comment by hlissner** [comment]
Sorry for the late response! I've added those two faces to doom-themes-common, which should resolve this issue. Feel free to reopen it if that isn't the case.

**Comment by seagle0128** [comment]
Thank you!
