### ISSUE TITLE
Possible to override specific theme settings in our private config.el?

### ISSUE THREAD

**Issue by skalfyfan** [hlissner/emacs-doom-themes#216]
I use `(load-theme 'doom-dracula t)` in my config.el but would like to override a couple settings in this theme. Specifically I'd like to override this setting:

https://github.com/hlissner/emacs-doom-themes/blob/master/themes/doom-dracula-theme.el#L166

Is this easily possible with a hook or something? 🤔 

Thanks!

**Comment by hlissner** [comment]
Perhaps `set-face-foreground` is what you want:

```elisp
(load-theme 'doom-dracula t)
(set-face-foreground 'markdown-header-face "#FFFFFF")
```

You can refer to Doom's colors for the current theme with the `doom-color` function:

```elisp
(set-face-foreground 'markdown-header-face (doom-color 'green))
```

This works with `doom-darken` and `doom-lighten` too:

```elisp
(set-face-foreground 'markdown-header-face (doom-darken 'green 0.2))

(set-face-foreground 'markdown-header-face (doom-lighten 'yellow 0.4))

(set-face-foreground 'markdown-header-face (doom-darken "#FFFFFF" 0.4))
```

**Comment by skalfyfan** [comment]
@hlissner Actually I just tried this:
```
;;; theme and customized theme changes
(load-theme 'doom-dracula t)
(set-face-foreground 'markdown-header-face (doom-color 'magenta))
```

and got when I tried to re-make I got:
```
--------------------------------------------------

There was an unexpected error:
  Error in private config (doom-private-error)
  config.el
  (error Invalid face markdown-header-face)
```
🤔

**Comment by hlissner** [comment]
Ah, then that code must be run after markdown-mode is loaded. Since you appear to be using Doom, the `after!` macro can help:

```elisp
(load-theme 'doom-dracula t)
(after! markdown-mode
  (set-face-foreground 'markdown-header-face (doom-color 'magenta)))
```

For posterity (if any non-Doom users that stumble on this), this is the non-Doom version of this:

```elisp
(load-theme 'doom-dracula t)
(with-eval-after-load 'markdown-mode
  (set-face-foreground 'markdown-header-face (doom-color 'magenta)))
```
