### ISSUE TITLE
About doom-nord dark theme

### ISSUE THREAD

**Issue by hanmoi-choi** [hlissner/emacs-doom-themes#219]
This is query regarding this line, https://github.com/hlissner/emacs-doom-themes/blob/master/themes/doom-nord-theme.el#L54

Is there any specific reason using `darkish` color ("#2d2d2d") for Foreground when terminal is term-256 supported?
This setting give me all darkish color when I am using my emacs as terminal one.

**Comment by hlissner** [comment]
Good catch. This appears to have been an oversight. As of d385615 this should be fixed. Let me know if that isn't the case and I'll reopen this.

Thanks for letting me know!
