### ISSUE TITLE
highlight when using jump-char.el

### ISSUE THREAD

**Issue by casouri** [hlissner/emacs-doom-themes#222]
The problem:

The highlight of current match of [jump-char](https://github.com/lewang/jump-char) is hard to see, if the matched char is on a keyword, it is even impossible to find it:

<img width="707" alt="screen shot 2018-09-19 at 10 17 47 pm" src="https://user-images.githubusercontent.com/13118647/45792042-2d6d0c80-bc5a-11e8-8b80-c76b6b3a600a.png">

To reproduce:

1. start emacs `emacs -q`
2. load jump-char: Either copy the code to a buffer or download it and open the file and `eval-buffer`.
3. (Inside doom-one-theme.el) `(add-to-list 'load-path default-directory)`.
4. (Inside doom-one-theme.el) `eval-buffer`.
5. Disable blink cursor mode: `M-x blink-cursor-mode`
6. `M-x jump-char-forward` then type a char, use `;` to go to next match

Matched char is highlighted just like the face when the blinking cursor is blinked off, which is hard to see.

**Comment by hlissner** [comment]
Thanks for the detailed bug report! As of 1fb359d, this should be fixed. 

Let me know if that isn't the case and I'll reopen this.

**Comment by casouri** [comment]
Thanks!
