### ISSUE TITLE
No selection in terminal with doom-tomorrow themes

### ISSUE THREAD

**Issue by averrin** [hlissner/emacs-doom-themes#223]
From discord.

doom-tomorrow themes as selection color use `(doom-lighten bg 0.1)` which means selection will be invisible in non-gui env due to 
```lisp
 ;; name        gui       256       16
 ((bg         '("#1d1f21" nil       nil          ))
```

**Comment by hlissner** [comment]
An oversight on my part! As of 0227a47 this should be fixed. Let me know if that isn't the case and I'll reopen this. Thanks for letting me know!
