### ISSUE TITLE
What kind of theme will be accepted?

### ISSUE THREAD

**Issue by casouri** [hlissner/emacs-doom-themes#229]
I made a nice theme that I'd like to share. But I don't know if there is a standard about what kind of theme will be accepted into doom-themes.

Also not sure about what kind of theme will be considered a "good" theme, any standard, rule, convention?

**Comment by hlissner** [comment]
Honestly, I hadn't thought about it. If I like it and it isn't just a quick palette swap, I accept it. However, that may change soon. I'd prefer you you start your own repo that pulls in this package to use as a framework.

I may even separate these themes into independent repos at some point.

**Comment by casouri** [comment]
That sounds cool! It's trivial to create my own theme with doom-themes, I'll give you that.
