### ISSUE TITLE
How is base0 - base8 defined?

### ISSUE THREAD

**Issue by casouri** [hlissner/emacs-doom-themes#232]
I see you didn't quite go with base16. So I suppose the guidelines base16 provided isn't of much use.

For me to create my own theme, the first thing is to tweak the `bg`, `bg-alt` and all nine colors from `base0` to `base8` so they look good. 

But because there isn't (or I didn't find) a clear guideline on how is every color used, so I used a "try and error" style when choosing my colors for `base0-8`.

Also, is it possible to simply define a `base0` and have all other base colors calculated from it?
Something like:

```
base0 xxx
base1 (doom-base1 base0)
...
```
This is just a side question, my main concern is still the lack of a guildline.

As a reference,  the guideline [base16](http://chriskempson.com/projects/base16/) has:

```
base00 - Default Background
base01 - Lighter Background (Used for status bars)
base02 - Selection Background
base03 - Comments, Invisibles, Line Highlighting
base04 - Dark Foreground (Used for status bars)
base05 - Default Foreground, Caret, Delimiters, Operators
base06 - Light Foreground (Not often used)
base07 - Light Background (Not often used)
base08 - Variables, XML Tags, Markup Link Text, Markup Lists, Diff Deleted
base09 - Integers, Boolean, Constants, XML Attributes, Markup Link Url
base0A - Classes, Markup Bold, Search Text Background
base0B - Strings, Inherited Class, Markup Code, Diff Inserted
base0C - Support, Regular Expressions, Escape Characters, Markup Quotes
base0D - Functions, Methods, Attribute IDs, Headings
base0E - Keywords, Storage, Selector, Markup Italic, Diff Changed
base0F - Deprecated, Opening/Closing Embedded Language Tags, e.g. <?php ?>
```

**Comment by hlissner** [comment]
Yes, doom-themes' baseN has nothing to do with the base16 guildelines. base1-7 represent shades from bg to fg, with base0 being black (usually darker than bg) and base8 being white (usually lighter than fg). It's reversed in light themes.

There is no guideline for these because there is no standard use for each of them. They're simply there to offer some more options for each theme.

I've been meaning to rethink them, but I haven't gotten around to it.

**Comment by casouri** [comment]
Cool, I got it.
