### ISSUE TITLE
citation lines are unreadable in message-mode

### ISSUE THREAD

**Issue by Benaiah** [hlissner/emacs-doom-themes#242]
In each theme, the foreground color used for citation lines in emails is very similar (or, in the case of `doom-nova`, identical) to the background color, making them difficult to read or even invisible. The involved face appears to be `message-cited-face`.

**Comment by hlissner** [comment]
Sorry for the tremendously late reply. If you're still experiencing this, could you show me a screenshot?

**Comment by Benaiah** [comment]
@hlissner no worries about taking too long to reply, I appreciate you getting back to me! Thanks for helping maintain such a nice set of themes!

Here are screenshots of `doom-nova`, `doom-one`, and no theme (I have colors set in `.Xresources` so it doesn't look like the default Emacs theme, but that doesn't affect the readability of `message-cited-face`) displaying an email in message-mode.

![unreadable-message-mode-face-doom-nova](https://user-images.githubusercontent.com/1425133/58836566-a7a6bb00-8648-11e9-9a24-a65b8b948a59.png)
![unreadable-message-mode-face-doom-one](https://user-images.githubusercontent.com/1425133/58836573-abd2d880-8648-11e9-90f2-e713ae4e448c.png)
![unreadable-message-mode-face-default-theme](https://user-images.githubusercontent.com/1425133/58836614-bee5a880-8648-11e9-9b11-f5cc20a08748.png)

**Comment by hlissner** [comment]
That is peculair. However, the default color for `message-cited-face` is `magenta`, and neither doom-nord nor doom-one changes this, so I'm skeptical that that _is_ in fact `message-cited-face`. Could you place your cursor over it and do `M-x describe-char`?

At the bottom of the new help buffer you'll find a list of overlays and text properties at point, including the active faces:

![image](https://user-images.githubusercontent.com/510883/60356362-0efa2580-99d1-11e9-978a-9874f24ed8c9.png)

It would help us figure out what faces are really at play here.
