### ISSUE TITLE
Org mode latex highlighting

### ISSUE THREAD

**Issue by memeplex** [hlissner/emacs-doom-themes#243]
Please set org-latex-and-related-faces to a sensible value. At least in tomorrow night it doesn't seem to be set at all.

**Comment by hlissner** [comment]
What would a sensible value be? A brief scan through the latest org only turns up the `org-latex-and-related` face. Is that what you meant? It doesn't appear to be set in any of this package's themes, but judging from its default, it should be set to `yellow`. Is that sensible?

**Comment by memeplex** [comment]
I think yellow is not the better choice because this face is used in three different scenarios:

1. Only super/subscripts are highlighted
2. Latex directives all highlighted
3. Entire latex chunks (inline and display) are highlighted

For 3 yellow would be too much. I think it could be sensible to inherit from some not too colorful tex mode face.

**Comment by hlissner** [comment]
As of ebd69f0 this issue should be resolved -- I've made the latex a brighter white (for most dark themes), so it should be much more visible without being too domineering.

Side-note: TIL that `(setq org-highlight-latex-and-related '(native))` will enable native highlighting for latex blocks in org.

Let me know if you don't think this resolves the issue and I'll reopen it. Thanks for bringing it to my attention!
