### ISSUE TITLE
set-mark won't work  in ssh terminal when using dark-one theme

### ISSUE THREAD

**Issue by iromise** [hlissner/emacs-doom-themes#244]
Hi, dark-one is really a good theme, but it `set-mark-command` does not work when in ssh terminal...

**Comment by hlissner** [comment]
I can't imagine that doom-themes has anything to do with that. Could you be more specific about how `set-mark-command` isn't working? What behavior are you expecting and observing?

**Comment by iromise** [comment]
Sorry, it is my fault.
