### ISSUE TITLE
[Question] How to display emoji ?

### ISSUE THREAD

**Issue by azzamsa** [hlissner/emacs-doom-themes#251]
Hi

How do you display/render emoji in magit log. I find [emacs-emojify](https://github.com/iqbalansari/emacs-emojify) around, but I don't find it's used in your doom-emacs config ?

Thank you for doom :)

**Comment by hlissner** [comment]
Yes, that is what is being used in that screenshot. I don't personally use it, but its [creator](https://github.com/fuxialexander/) does.

**Comment by azzamsa** [comment]
Wow. Thank you for complete answer :). Really need that information.

And thank you for Doom :)
