### ISSUE TITLE
Icons won't load for treemacs

### ISSUE THREAD

**Issue by perezd** [hlissner/emacs-doom-themes#264]
Treemacs version:
treemacs-20190104.1527

doom-themes version:
doom-themes-20190214.627

emacs version:
GNU Emacs 25.2.2

Screenshot:
![screenshot from 2019-02-18 16-25-41](https://user-images.githubusercontent.com/20598/52982243-dd75ab80-3399-11e9-932f-4b5e2f15007e.png)

I did run M-x all-the-icons-install-fonts and it looked like it worked.
Any ideas?

**Comment by perezd** [comment]
Looks like the fonts that got downloaded are broken:
![image](https://user-images.githubusercontent.com/20598/52982668-36464380-339c-11e9-9111-edc83b37b914.png)

**Comment by perezd** [comment]
Workaround: download them manually here and put them in ~/.local/share/fonts
https://github.com/domtronn/all-the-icons.el/tree/master/fonts

**Comment by hlissner** [comment]
This is a [known issue with all-the-icons](https://github.com/domtronn/all-the-icons.el/issues/134). Sorry to say, until it is resolved, you'll have to install its fonts manually.

**Comment by perezd** [comment]
Sounds good, we can leave this here for others as a workaround at least!

**Comment by hlissner** [comment]
This appears to [have been resolved upstream](https://github.com/domtronn/all-the-icons.el/issues/134), so I'll close this issue. Thanks for bringing it to my attention!

**Comment by mandarvaze** [comment]
I have a "related" issue. 
I think all-the-icons fonts are installed correctly - cause I get "language" icons elsewhere (e.g. Ivy switch buffers)

But I do not get "nice" icons in treemacs. e.g. I see just 3 types of icons
1. folder
2. document (.txt and .md both get same icon)
3. code - .py as well as .yml get an icon that looks like html/tags icon (It is too small, so I'm not sure. But it is definitely not "python" icon, I see elsewhere)

**Comment by mustaqimM** [comment]
@hlissner I now recently switched to using treemacs and also see that the font icons don't show:
![image](https://user-images.githubusercontent.com/24436622/78499291-4c999500-773f-11ea-832a-f86473a34ace.png)
The icons work everywhere else like the dashboard

**Comment by ema2159** [comment]
@mustaqimM they're loading, but you're using the minimal theme which is the default. You have to enable the colorful theme which assigns different icons for each file type.

**Comment by mustaqimM** [comment]
@ema2159 thanks so much, I managed to enable it with:
`(setq doom-themes-treemacs-theme "doom-colors")`
