### ISSUE TITLE
Thin diff fringe

### ISSUE THREAD

**Issue by BrandonShega** [hlissner/emacs-doom-themes#265]
Hello!

Currently using the doom-dracula theme and loving it.  I had a question though, in the screenshot that shows the doom-one theme, the diff fringe is very thin, maybe 1-2 pixels.  I can't seem to achieve this, mine is massive taking up the entire fringe.

Is there a configuration setting I'm missing that does this?

![diff-fringe](https://i.imgur.com/2gqI2MA.png)
vs
![skinny-diff-fringe](https://i.imgur.com/yT7aAoM.png)

**Comment by hlissner** [comment]
You can resize the fringe with `(fringe-mode '4)` (which is the size I use in my screenshots).

I hope that helps!

**Comment by BrandonShega** [comment]
Thank you! I tried so many combinations of that, but that one worked.

**Comment by gjm** [comment]
@hlissner I'm sorry for hijacking this but I'm having the same problem... Your fix works. If I eval `(fringe-mode '8)` it changes my fringe size. But when I put it in `~/.doom/config.el` it doesn't work...

**Comment by davidbudzynski** [comment]
For me (fringe-mode) doesn't work at all. for example, the size of tildes at the end of the buffer and vc-gutter still remain the same.

**Comment by hlissner** [comment]
@gjm @davidbudzynski If you're both using Doom, you need to wrap it in `(after! git-gutter-fringe ...)`.

**Comment by davidbudzynski** [comment]
I tried both 
``` 
(after! git-gutter-fringe
  (fringe-mode '27))
```
and 
```
(after! vi-tilde-fringe-mode
  (fringe-mode '27))
```
I think the fringe is gets wider but the git gutter and vi tilde size stays the as small as it was, both of them appear to be centered in the middle of the fringe.
