### ISSUE TITLE
Fix doom-nord according to nord-emacs

### ISSUE THREAD

**Issue by rememberYou** [hlissner/emacs-doom-themes#266]
First of all, I would like to thank you for these wonderful themes, I have just discovered the existence of your package today ☺️

Being a great fan of the `nord-theme`, I was surprised to see that the `doom-nord` _(right side of the picture)_ is different from the [nord-theme](https://github.com/arcticicestudio/nord-emacs) _(left side of the picture)_ managed by [arcticicestudio](https://github.com/arcticicestudio).

![nord-theme](https://user-images.githubusercontent.com/6253527/53696102-09deee00-3dc4-11e9-98cc-262d34a7a254.png)

Since there are `doom-nord` and `doom-nord-light`, should we create `doom-nord-dark` (or replace `doom-nord`) that uses the same color layout and color code as the classic `nord-theme`?

Thank you once again for your amazing work.

**Comment by hlissner** [comment]
Do you use [solaire-mode](https://github.com/hlissner/emacs-solaire-mode)? It may account for these differences.

Unfortunately, I don't use doom-nord (or nord), and do not maintain it enough to comment on the correctness of these faces. I don't think it needs to be split up into more themes, only corrected, if it is indeed incorrect. A PR would be appreciated.

**Comment by rememberYou** [comment]
Thank you for your reply.

Well, I don't use `solaire-mode`. It will be a pleasure to fix that in a pull request as soon as I can have the time to do that.

**Comment by ema2159** [comment]
@rememberYou there was indeed a problem with the background color. We fixed it so now it should look good! Also, I encourage you to use `solaire`! It really makes your Emacs look much better

**Comment by rememberYou** [comment]
@ema2159 thank you for the fix, it looks better now 😊

**NOTE:** I will give a try to `solaire-mode`
