### ISSUE TITLE
Git gutter is missing inner color with doom themes

### ISSUE THREAD

**Issue by BrandonShega** [hlissner/emacs-doom-themes#268]
Hi!

Sorry, more fringe issues, I wasn't sure if I should reopen the old issue I created in regards to the size of the fringe.

Here is how my fringe with git gutter looks with the dracula theme:

![Dracula Theme](https://i.imgur.com/2HNVjDV.png)

and here is how it looks with the Doom One theme (which I'm currently using)

![Doom One Theme](https://i.imgur.com/liWVux8.png)

and Doom Dracula:

![Doom Dracula](https://i.imgur.com/Bfgx0QA.png)

It's like the inner portion of the bar isn't being colored for some reason.  Is this a conflict with another setting I might have?

**Comment by BrandonShega** [comment]
I solved this by just customizing the face, I'm not sure if that's what you did @hlissner for your screenshots.

I noticed that the `diff-hl-*` faces are not themed in the .el files.

**Comment by CSRaghunandan** [comment]
@BrandonShega I also ran into the same issue. I customized the face as well, in my emacs.d config files.

Maybe this is worth reopening again?

**Comment by hlissner** [comment]
@BrandonShega I use git-gutter. What you saw in my screenshots were custom bitmaps I defined for them.

Anyhow, as of 2526456 I've added matching backgrounds to the diff-hl faces, which should resolve this issue.

**Comment by hlissner** [comment]
For posterity, if folks want to undo this, use:

```elisp
(custom-set-faces
  '(diff-hl-change ((t (:background nil)))
  '(diff-hl-delete ((t (:background nil)))
  '(diff-hl-insert ((t (:background nil))))
```
