### ISSUE TITLE
split window is completely subdued in doom-theme

### ISSUE THREAD

**Issue by maindoor** [hlissner/emacs-doom-themes#270]
Hi,
Is it by design that if the window is split, the window split border is subdued in doom-theme ?
For example look at the screenshot of doom-Iosvkem
on the right hand side you have to be careful to figure that the window is split. Is this intentional  in doom-themes ?

**Comment by hlissner** [comment]
Yes, that is intentional. If you modify the `vertical-border` face (or `window-divider` face if you use `window-divider-mode`) you can make it more visible: e.g.

```elisp
(set-face-foreground 'vertical-border "grey80")
(set-face-foreground 'vertical-border "#999999")
(set-face-foreground 'vertical-border (doom-color 'red))
```

If you use `window-divider-mode` (in GUI Emacs), you can increase the size of the borders:

```elisp
(setq window-divider-default-bottom-width 4 ; in pixels
      window-divider-default-right-width 4)
(window-divider-mode +1)
```

Hope that helps!

**Comment by maindoor** [comment]
Yes, that helps, thanks! I'll close the issue.
