### ISSUE TITLE
all-the-icons-dsilver is too dark

### ISSUE THREAD

**Issue by seagle0128** [hlissner/emacs-doom-themes#272]
`all-the-icons-dsilver` is too dark and almost invisible in `doom-one` and other dark themes.

**Comment by hlissner** [comment]
04c147f should make it (and the other silver faces) brighter. Let me know if that's bright enough.

**Comment by seagle0128** [comment]
Thanks, @hlissner .

Now it looks as below. The color of icons are `all-the-icons-dsilver`. It's better if the color is a little bit lighter IMO.

![image](https://user-images.githubusercontent.com/140797/56714205-b30fe800-6766-11e9-9322-3a8962bfae42.png)

  
![image](https://user-images.githubusercontent.com/140797/56714355-26b1f500-6767-11e9-95a2-77c98580bb22.png)

**Comment by hlissner** [comment]
Sorry for the terribly late response. I made all-the-icons-dsilver a brighter in b5435a6, so I'll consider this resolved.

**Comment by seagle0128** [comment]
Thank you!
