### ISSUE TITLE
Possible to load theme from .Xresources?

### ISSUE THREAD

**Issue by willbush** [hlissner/emacs-doom-themes#274]
I was wondering if it is possible to convert these themes into `.Xresources` files in order to save on startup time? 

I tried using [color-theme-x](https://github.com/ajsquared/color-theme-x), but I couldn't get it to work. If it doesn't look as good as setting through lisp, then I probably wouldn't use it. However, I'm wondering if I can save the 0.035s - .075s time I'm measuring with esup loading `doom-vibrant` during startup vs loading [this theme](https://github.com/ajsquared/color-theme-x/blob/master/themes/XResources-molokai) via the `.Xresources` file. It's a silly micro-optimization, I know, but I am guess I'm inspired by the speed of doom-emacs.

**Comment by hlissner** [comment]
From a brief scan of color-theme-x, it parses very specific sexps (`color-theme-*` functions and `color-theme-install` calls), which is the old (Emacs <24.4, iirc) way of defining themes. So this won't work with Doom themes (or modern Emacs themes defined with `deftheme`). 

Perhaps https://github.com/cqql/xresources-theme is more up your alley; though it only grabs a few select color variables from your Xresources. I once tried to adapt it to a Doom theme (https://gist.github.com/hlissner/d2a73281dcc709ff20537d36c016f934) but never went anywhere with it -- I haven't even tested it.

Besides that, sorry to say I'm unaware of any projects that can do this.

**Comment by willbush** [comment]
Alright, thanks for looking into that!
