### ISSUE TITLE
DONE items in org-mode have the same color as current-line

### ISSUE THREAD

**Issue by apc** [hlissner/emacs-doom-themes#278]
This seems to be an issue with `doom-nova`. DONE items are [set to `base5` in `doom-themes-common.el`](https://github.com/hlissner/emacs-doom-themes/blob/master/doom-themes-common.el#L1181), but [so is `current-line`](https://github.com/hlissner/emacs-doom-themes/blob/master/themes/doom-nova-theme.el#L76) in `doom-nova`. Seems like an easy fix, but not sure whether this is the intended behavior or not.

**Comment by hlissner** [comment]
Sorry for the terribly late response. As of b5435a6 this should be resolved. If that isn't the case let me know and I will reopen this issue. Thanks for bringing it to my attention!
