### ISSUE TITLE
error: Invalid face underline, :color, (doom-darken vertical-bar 0.2)

### ISSUE THREAD

**Issue by gregf** [hlissner/emacs-doom-themes#280]
Trying to load a theme on emacs 26.2. This has been broken for me a while thought it might have got fixed tried to use it again tonight same error.

This is the error:

```
error: Invalid face underline, :color, (doom-darken vertical-bar 0.2)
````

While using the following config

```
(use-package doom-themes
    :init (load-theme 'doom-vibrant t))
```

**Comment by hlissner** [comment]
Sorry for the late response. As of 986eecd this should be fixed. Let me know if that isn't the case and I will reopen this issue. Thanks for bringing it to my attention!
