### ISSUE TITLE
Theme Request: Fairyfloss

### ISSUE THREAD

**Issue by ShaneKilkelly** [hlissner/emacs-doom-themes#287]
Main github repo: http://sailorhg.github.io/fairyfloss

Example screenshot:

![image](https://user-images.githubusercontent.com/1540054/59345205-89efea80-8d07-11e9-9818-af776d2c605e.png)

There is a partial conversion for emacs here: https://github.com/sailorhg/fairyfloss/pull/3, but it's got some weird colors going on in places like the magit UI.

**Comment by ema2159** [comment]
If Mr. Lissner lets me, I'll implement this one

**Comment by ema2159** [comment]
I have green lights now so expect to see this soon 😁

**Comment by ema2159** [comment]
Almost there!
![fairy](https://user-images.githubusercontent.com/17773218/62001612-8b0b8a00-b0b1-11e9-96f1-77f17507227f.png)

**Comment by ema2159** [comment]
Done, it's been added. Please test it and tell me if you find any weird faces. I used it and didn't found any issues besides some magit faces which I fixed

**Comment by ShaneKilkelly** [comment]
Very nice, thanks!

I'm testing on spacemacs, and it all looks very good so far. One small point, maybe the current-line highlight is a little too strong?

![image](https://user-images.githubusercontent.com/1540054/62198445-8aa51480-b379-11e9-952e-579103c695ad.png)

Otherwise, this looks real nice, :tada:

**Comment by ema2159** [comment]
That's using `hl-line`? If it is, then yes, it's too strong. I'll check in VS Code and use the same color

**Comment by ema2159** [comment]
@ShaneKilkelly done, It's now lighter and smoother. Report here if you find more things like that!

**Comment by ShaneKilkelly** [comment]
Thanks!

**Comment by chase-dwelle** [comment]
Surprised that I like the theme as much as I do. One question though, I have this blue color ("blue" -- #268bd2 in the theme) that I have not seen in any of the screenshots that does not have enough contrast with the background (can be seen with the ```infile = open(rfile, 'rb')``` line in the attached

![image](https://user-images.githubusercontent.com/9752548/63030478-01f99e80-be78-11e9-9c0e-2ba79646fc66.png)

Personally I think something like #85f3bc, a pastel green, is easier to differentiate from the background:

![image](https://user-images.githubusercontent.com/9752548/63032880-48e99300-be7c-11e9-94e2-9a1de8368011.png)

Is this something that can be changed, or is the original "blue" color preferred by most?

**Comment by ema2159** [comment]
You're right. I don't quite remember where I took that blue from. Although a pastel green would do the work, I personally think it would be better to find a blue alternative, given that it's the `blue` variable what we're changing.

**Comment by ema2159** [comment]
@chase-dwelle how about this color I just made up (lol)?:
#55b3cc
It's still blueish while having a much better contrast .

**Comment by chase-dwelle** [comment]
Yes that works; here it is in the same screenshot.

![image](https://user-images.githubusercontent.com/9752548/63036902-99182380-be83-11e9-907c-5d400562d9ba.png)

**Comment by ema2159** [comment]
Done, it should be up in the next update

**Comment by chase-dwelle** [comment]
Found some other issues with font faces in org-mode, especially with scheduled faces. The inherited faces from the base theme end up with nearly the same color in scheduled faces and the background. I suggest borrowing from doom-dracula:

```
   (org-scheduled :foreground green)
   (org-scheduled-previously :foreground yellow)
   (org-scheduled-today :foreground orange) 
```

**Comment by ema2159** [comment]
Hi @chase-dwelle!, Would you please show me an screenshot?

**Comment by chase-dwelle** [comment]
Here is my screenshot using the base fairy floss theme: 

<img width="593" alt="image" src="https://user-images.githubusercontent.com/9752548/65375616-52c19b80-dc5d-11e9-9682-ccef31b8e3f7.png">

Borrowing the following definitions from doom-dracula gives the image below. I'm guessing that there are some font face decisions in the base theme that can lead to lack of readability in some of the darker themes, which is why doom-dracula has so defined faces.
```
   (org-scheduled :foreground green)
   (org-scheduled-previously :foreground yellow)
   (org-scheduled-today :foreground orange)
```

<img width="85" alt="image" src="https://user-images.githubusercontent.com/9752548/65375663-b6e45f80-dc5d-11e9-80d1-b83ec5cba3bf.png">

**Comment by ema2159** [comment]
@chase-dwelle sorry for the late reply. How about now?

**Comment by chase-dwelle** [comment]
Yes works well. Thanks you!
