### ISSUE TITLE
too much contrast of dired entries in helm-buffers-list

### ISSUE THREAD

**Issue by wauisaui** [hlissner/emacs-doom-themes#289]
First, @hlissner, thanks for this great theme pack. Enjoying it much.

I know you don't use helm but ... I have seen that the colors of dired entries in the helm list of buffers does not want to follow the spirit of dark themes. 

![image](https://user-images.githubusercontent.com/7604826/59969586-dd8be080-951e-11e9-8122-f91e6f2d682e.png)

**Comment by hlissner** [comment]
Would you be able to pinpoint what faces helm uses, that should be fixed?
