### ISSUE TITLE
doom-neotree don't work in emacsclient -c

### ISSUE THREAD

**Issue by arkhan** [hlissner/emacs-doom-themes#29]
hello i have this:

``` emacs-lisp
(use-package doom-themes
    :ensure t
    :init
    (load-theme 'doom-molokai t)
    :config
    (add-hook 'find-file-hook 'doom-buffer-mode)
    (add-hook 'minibuffer-setup-hook 'doom-brighten-minibuffer)
    (validate-setq org-fontify-whole-heading-line t
                   org-fontify-done-headline t
                   org-fontify-quote-and-verse-blocks t)
    (when (display-graphic-p)
      (require 'doom-neotree)
      (validate-setq doom-neotree-file-icons nil)))
```

when launch emacs, work fine, but in emacsclient -c dont work,

i eval this expression (display-graphic-p) and return t

Thanks

**Comment by hlissner** [comment]
What OS are you running? And is `emacsclient -c` opening terminal or GUI emacs?

**Comment by arkhan** [comment]
I'm using GNU/Linux, and launch emacsclient with dmenu_run

**Comment by hlissner** [comment]
Sorry for the late reply. I'm looking into this now. Could you run this `(framep-on-display)` and tell me what it returns?

**Comment by arkhan** [comment]
I'm running eva-expression for (framep-on-display), get this:

x

**Comment by hlissner** [comment]
Sorry for the late reply, but I recently discovered this may be the same issue as #73 -- I [talked about a solution in that thread](https://github.com/hlissner/emacs-doom-themes/issues/73#issuecomment-312319122).

Please have a look at that and see if that solves your issue.

**Comment by arkhan** [comment]
Great now it works
thanks
