### ISSUE TITLE
Centaur-tabs theming

### ISSUE THREAD

**Issue by ema2159** [hlissner/emacs-doom-themes#291]
Hello mr. @hlissner, I've been working on a new tabs plugin soon to be released on MELPA (https://github.com/ema2159/centaur-tabs) people really have been liking the plugin so far (see reddit post), the thing is, I've been working to try and theme this properly with doom-themes however I have a problem. I am able to theme it properly without solaire-mode like this:
![DeepinScreenshot_select-area_20190628183528](https://user-images.githubusercontent.com/17773218/60377376-9183e480-99d3-11e9-8359-d2a2152a5224.png)

However with solaire mode it looks like this (note that the current tab should match de the buffer color, not otherwise):

![DeepinScreenshot_select-area_20190628183737](https://user-images.githubusercontent.com/17773218/60377403-d90a7080-99d3-11e9-9f68-5e0871564fa4.png)

How can I make Solaire-mode work with my plugin properly so I can theme it properly and submit a PR?

I really want my plugin to be properly themed and for it to work nice with the best theme plugins like this or Kaolin themes so please tell me how to proceed so we work together and provide a quality theming that people can enjoy!

**Comment by ema2159** [comment]
I managed to theme it properly. I submitted a PR, let me know if it's alright

**Comment by hlissner** [comment]
Hi! Sorry for the late reply, I'm in the middle of a major rewrite of this package. With #292 does centaur-tabs look right with Doom themes when solaire-mode is disabled? I fear it may not, and that the changes in #292 will only work for solaire-mode users. If that turns out to be the case, Perhaps a better solution would be to remap centaur-tab's faces? e.g. https://github.com/hlissner/emacs-solaire-mode/blob/master/solaire-mode.el#L121-L133, or advising `solaire-mode-swap-bg` to swap centaur's faces as well?

**Comment by ema2159** [comment]
Hi Mr. Lissner, don't worry, I know you're a very busy man. The theming with and without solaire-mode for text-editing buffers is the same, it changes for buffers like dired for example like this but it doesn't look too bad neither. It looks like this:

Without solaire-mode:
![DeepinScreenshot_select-area_20190701100018](https://user-images.githubusercontent.com/17773218/60451133-a38aa080-9be8-11e9-9bb9-b9edbd4f9759.png)

With solaire-mode:
![DeepinScreenshot_select-area_20190701100237](https://user-images.githubusercontent.com/17773218/60451129-9ec5ec80-9be8-11e9-842f-96b0c2725804.png)

I'll close the aleready existing PR and open a new one. It's just putting the same code but in the doom-themes-base.el instead.
