### ISSUE TITLE
tabs in dired

### ISSUE THREAD

**Issue by cwhatley** [hlissner/emacs-doom-themes#293]
I use your theme + treemacs-dired-icons and noticed that in the last update, there's a big tab space between the icons in dired and the filename.

Might be worth adding something like this to address the formatting, but perhaps this too unusual a combo to bother with:

```(add-hook 'dired-mode-hook #'doom-themes-setup-treemacs)```

**Comment by hlissner** [comment]
Could you offer a screenshot of the problem? Are you suggesting I write a `doom-themes-setup-treemacs` or did you actually mean `doom-themes-treemacs-config`? Are you using `doom-themes-treemacs-config`? I imagine this must be because the treemacs icon theme contains whitespace. If that's the problem, I'm not sure what to do about that. Shouldn't treemacs-dired-icons trim icons before displaying them, since, unlike treemacs, dired isn't hierarchical?

**Comment by cwhatley** [comment]
`doom-themes-setup-treemacs` exists already and you use it as a treemacs hook: https://github.com/hlissner/emacs-doom-themes/blob/facec00bd5ac4e2633419a85b5cb551aad954f3b/doom-themes-ext-treemacs.el#L31

The treemacs icon has a tab after the icon and the default value of tab-width leads to these gaps. If you add your doom-themes-setup-treemacs to dired-mode-hook it sets the tab width and things look fine.

With whitespace-mode turned on to reveal the tab:
![image](https://user-images.githubusercontent.com/573757/60514206-fe82cd00-9ca6-11e9-8862-e8f8e5de7ff0.png)

Without:
![image](https://user-images.githubusercontent.com/573757/60514220-07739e80-9ca7-11e9-99a8-6df1a09aceb1.png)

**Comment by hlissner** [comment]
Ah, I see the problem. 3571d46 should fix this issue. Let me know if that isn't the case and I will reopen it. Thanks for bringing it to my attention and helping me figure it out!

**Comment by cwhatley** [comment]
Great!

**Comment by cwhatley** [comment]
That's actually not working for me. I only see the tab-width take effect when I turn treemacs-icons-dired-mode off and then on again because it is a "super-global" mode active in all buffers, so the hook is only called once on startup.

This should do the trick:
```
  (add-hook 'treemacs-icons-dired-mode-hook (lambda () (add-hook 'dired-mode-hook #'doom-themes-setup-tab-width)))
```

**Comment by hlissner** [comment]
As of 119668c that should be fixed. Let me know. Thanks for the help!
