### ISSUE TITLE
Minibuffer font too dark in doom-tomorrow-night

### ISSUE THREAD

**Issue by ianpan870102** [hlissner/emacs-doom-themes#295]
I really love the Doom-tomorrow-night theme, however I've always found the minibuffer prompt font to be too dark blue (e.g. when finding files or switching buffers). Please consider tuning up the contrast and use a slightly lighter blue.

**Comment by hlissner** [comment]
11e43d5 should fix this. Let me know if that isn't the case and I will reopen this issue. Thanks for bringing it to my attention!

**Comment by ianpan870102** [comment]
Brilliant! Thanks for the prompt reply too!
