### ISSUE TITLE
doom-themes overrides the border face of ivy-posframe

### ISSUE THREAD

**Issue by AmaiKinono** [hlissner/emacs-doom-themes#296]
`doom-themes` defines its `ivy-posframe-border` face:

https://github.com/hlissner/emacs-doom-themes/blob/11e43d518cbf4a4a1116de8330994512005d1c56/doom-themes-base.el#L696

But it's also defined in the `ivy-posframe` package, with a gray background:

https://github.com/tumashu/ivy-posframe/blob/ce7505d61cf6e7dd85884d3edf4003d9257d15f7/ivy-posframe.el#L227

`doom-themes` overrides the default definition in my case, causing an invisible border. This should be removed or redefined.

**Comment by hlissner** [comment]
That was intentional to avoid this:

![image](https://user-images.githubusercontent.com/510883/60747694-6119e880-9f87-11e9-838b-c2346647803b.png)

So we have:

![image](https://user-images.githubusercontent.com/510883/60747699-72fb8b80-9f87-11e9-9769-49b89a3f49a2.png)

It can be changed with `set-face-background`, after your theme has been loaded:

```elisp
;; after (load-theme 'doom-one t)
(set-face-background 'internal-border "grey50")
;; or
(doom-themes-set-faces 'doom-one
  '(internal-border :background "grey50"))
```

**Comment by AmaiKinono** [comment]
`ivy-posframe` has a customizable variable `ivy-posframe-border-width`, set it to 0 to get rid of the border. But the default value is 1, and it seems to be like 10 in your screenshot. I guess you may did something like

``` emacs-lisp
(setq ivy-posframe-parameters '((internal-border-width . 10)))
```

**Comment by hlissner** [comment]
That's right. `internal-border-width` was increased to pad the child frame, and when padded, the border looks terrible if it doesn't match its background. The way I see it, the `border-width` frame parameter exists for the purpose of an outer border and the internal border exists for padding, so padding should extend the background of the frame.

**Comment by AmaiKinono** [comment]
Thanks for the explanation. Now I noticed the effect, and I agree that internal border should have the background color. However, I've read the documentation of `posframe-show`, there are only internal border attributes, no outer border, and `ivy-posframe` actually does something like this:

``` emacs-lisp
(apply #'posframe-show
       ivy-posframe-buffer
       ...
       :internal-border-width ivy-posframe-border-width
       ...)
```

So it's like there's no such thing as an outer border in the `posframe` packages. Maybe I should suggest the author to implement this.

**Comment by AmaiKinono** [comment]
Hi. [Here](https://github.com/tumashu/posframe/issues/34#issuecomment-510952055) is my conclusion. It's possible to have outer border using the `:override-parameters` property of `posframe-show`, like

``` emacs-lisp
(posframe-show buffer-name
 ...
 :override-parameters '((border-width . 2)
                        (border-color . "gray"))
 ...)
```

But it wouldn't show on GTK builds (i.e. for most Linux users), and would show as a 1 pixel line on Windows, despite of the parameters you specified. So you are doing it right, but it's the problem of Emacs itself.

**Comment by ema2159** [comment]
@AmaiKinono, shall I close his issue now?

**Comment by AmaiKinono** [comment]
@ema2159 Yes, please.

**Comment by ema2159** [comment]
Sorry, you're right. It was a typo
