### ISSUE TITLE
Why I don't have these icons in magit?

### ISSUE THREAD

**Issue by vityafx** [hlissner/emacs-doom-themes#300]
Mine:

![](https://i.imgur.com/FohmFFu.png)

Yours:

![](https://raw.githubusercontent.com/hlissner/emacs-doom-themes/screenshots/doom-nord.png)

Everything is installed, doom themes, doom-modeline, all the icons. Anything else I need to install? Also, how does it know what icon to show - for a bug or a feature?

**Comment by hlissner** [comment]
I apologize for misleading you, but those icons aren't part of this package. However, [here's a guide on how to get it](http://www.modernemacs.com/post/pretty-magit/).

**Comment by vityafx** [comment]
Oh, yes, I had already figured it out before your comment but forgot to close it :) Yes, this is "Pretty Magit" package. I think, we should add a list of packages visible on each screenshot for people who expect these screenshots to become live on their pc after installing doom themes. Such things are fonts, pretty magit on some packages, solaire-mode sometimes. Maybe I missed something, but I think it is a good idea :)
