### ISSUE TITLE
dired-directory and dired-marked are usually very similar

### ISSUE THREAD

**Issue by d125q** [hlissner/emacs-doom-themes#304]
For example, in `doom-one` both `dired-directory` and `dired-marked` have `magenta` color.  The only difference is that `dired-marked` has bold weight, but that is not a very obvious difference.

Instead, I suggest that we add some discerning feature to `dired-marked`, like a `highlight` background.

**Comment by hlissner** [comment]
As of 31c3eb0 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
