### ISSUE TITLE
Treemacs config lost control of width

### ISSUE THREAD

**Issue by ianyepan** [hlissner/emacs-doom-themes#306]
After invoking doom-themes-treemacs-config (which I love a whole lot!) I've been experiencing some width adjusting flashes in the Treemacs sidebar. So whenever I open the Treemacs sidebar it would start with half a centimetre wider than it should be, and then quickly auto-adjust itself after 500 milliseconds (approx.), resulting in a (kinda annoying) width flash whenever I call Treemacs.

How should I fix this? It happens regardless if I have the icons turned on or off. But the problem goes away if I don't use doom-themes-treemacs-config.

**Comment by hlissner** [comment]
I cannot reproduce this with or without `doom-themes-treemacs-config`, or on vanilla Emacs. In fact, treemacs resists any resizing at all to the window by setting `window-size-fixed` to non-nil inside the treemacs buffer. With that disabled, in vanilla Emacs it resizes fine. Is this in vanilla Emacs you're reproducing this?

**Comment by ianpan870102** [comment]
Yes I'm running my own config of vanilla Emacs (27.0.50) and these are the code regarding treemacs-config:

```
  (use-package doom-themes :config (doom-themes-treemacs-config))

  (use-package treemacs
    :after evil
    :config
    (global-set-key (kbd "s-1") 'treemacs)
    (setq treemacs-fringe-indicator-mode nil
          treemacs-silent-refresh t
          treemacs-silent-filewatch t
          treemacs-file-event-delay 1000
          treemacs-file-follow-delay 0.1
          window-size-fixed t)
    (use-package treemacs-evil
      :after treemacs
      :config
      (evil-define-key 'treemacs treemacs-mode-map (kbd "l") 'treemacs-RET-action)
      (evil-define-key 'treemacs treemacs-mode-map (kbd "h") 'treemacs-TAB-action))
    (use-package treemacs-projectile :after treemacs projectile)
    (use-package treemacs-magit :after treemacs magit))
```

When in treemacs if I type C-h v window-size-fixed, it returns 'width', which is a non-nil value as you mentioned.

**Comment by ema2159** [comment]
Maybe it also has to do with Emacs Plus

**Comment by hlissner** [comment]
@ianpan870102 Do you still see this issue?
