### ISSUE TITLE
Add Visual Studio Dark theme

### ISSUE THREAD

**Issue by ZelCloud** [hlissner/emacs-doom-themes#310]
The visual studio themes I would say are pretty great, and having the same theme on both emacs and visual studio would be sweet.

https://docs.microsoft.com/en-us/visualstudio/extensibility/ux-guidelines/color-value-reference-for-visual-studio?view=vs-2017

**Comment by ema2159** [comment]
This package now has new collaborators so we'll be able to be more active and implement more themes. This suggestion surely will be taken into consideration.

**Comment by seagle0128** [comment]
It's duplicated with #279 .

**Comment by ema2159** [comment]
@seagle0128 kinda! He was asking for all of them jaja

**Comment by seagle0128** [comment]
Oh, share all themes? Damn, maybe need a translator 😢

**Comment by ema2159** [comment]
Jajajaja yes. (I wont implement any light themes though 😂)

**Comment by ema2159** [comment]
@ZelCloud Done! check it out.
