### ISSUE TITLE
Is there an easy to disable variable pitch (fonts with different sizes) for the theme "doom-dracula" (and possibly all the themes)?

### ISSUE THREAD

**Issue by mrbig033** [hlissner/emacs-doom-themes#312]
### Runtime Environment

- MX Linux 18
- [i3wm](https://i3wm.org/) version 4.13
- [i3/config](https://github.com/mrbig033/dotfiles/blob/master/i3/config)
- [dotfiles](https://github.com/mrbig033/dotfiles)
- GNU Emacs 27.0.50
- Org mode version 9.2.3
- Evil version 1.2.14
- [~/.emacs.d](https://github.com/mrbig033/emacs)

### Issue

Fonts with different sizes cause a bunch of little inconsistencies (just to give an example, the modeline keeps moving up and down when I move in the agenda), and I don't find them very pleasing. Can I disable them altogether? And possibly for all doom themes?

**Comment by hlissner** [comment]
Sorry for the tremendously late response: I'm not aware of any way to globally disable variable font sizes. You'd have to know the offending faces and adjust them on a face-by-face basis. 

A google search yields this advice:

```elisp
(advice-add 'face-spec-set-2 :around
            (lambda (f face frame attrs)
              (funcall f face frame (plist-put attrs :height 1.0)))
```

But I haven't tried it myself.

Also, in recent commits of `doom-themes` I've removed :height properties from org's and ledger's headings, which should be two steps in the right direction.

Hope that helps.

**Comment by tom10x** [comment]
I use this to equalize the font size:

```
(set-face-attribute 'org-level-1 nil :height 1.0)
```

**Comment by hlissner** [comment]
@tom10x That is for the other dracula-theme for Emacs. This issue is about this package's dracula-theme, which doesn't set `:height` for org-level-N faces.

In any case, there hasn't been any response to this issue is quite some time, so I'll consider it resolved.

**Comment by tom10x** [comment]
@hlissner  Oh, it's probably a version-thing. I just noticed your commit. My elpa/doom-themes-2.1.6/doom-dracula-theme.el - which I got from melpa-stable - still contains this

```
   (org-level-1 :background base1 :foreground level1 :height 1.2 :weight 'bold)
```

Here's my complete doom-themes setup in case it might help someone else who's lagging behind.

```
(use-package doom-themes
  :config
  (load-theme 'doom-dracula t)
  (set-face-attribute 'org-level-1 nil :height 1.0)

  ;; Enable flashing mode-line on errors
  (doom-themes-visual-bell-config)

  ;; Corrects (and improves) org-mode's native fontification.
  (doom-themes-org-config))
```

**Comment by hlissner** [comment]
Ah, that reminds me, we haven't made a release in a while. I'll fix up the tests and do one soon.
