### ISSUE TITLE
mode-line face

### ISSUE THREAD

**Issue by seagle0128** [hlissner/emacs-doom-themes#317]
In vanilla Emacs, the face of `mode-line` includes `background`, `foreground` and `box` attributions. However, the `foreground` attribute is missing in `doom-themes`, which is displayed as `unspecified`.

I checked `doom-themes-base`, the definition of `mode-line` is fine.
```elisp
(mode-line :background bg :foreground fg :distant-foreground bg)
```

But in the themes files, e.g. `doom-one-theme.el`, `mode-line` face is redefined with `modeline-fg`, `modeline-bg`, etc. And `modeline-fg` is set to `nil`. So `foreground` attribute is missing. I have no idea of the reason. Perhaps I missed something here? But I observe in some cases, the mode-line colors may be displayed incorrectly, e.g. while unfocusing the frame and waiting for a while, switching frames back and forth (especially on dual monitors), etc. I have to use the workaround as https://github.com/seagle0128/.emacs.d/blob/987ae4d03fcaf8884634a3fb002e636014cfda8f/lisp/init-ui.el#L74 to fix it. IMO, the simple solution is setting `modeline-fg` to `fg` (or similar colors).

I am using GNU Emacs 27.0.50 on macOS Mojave, and this issue exists on Emacs 26.2/Ubuntu 18.04 in my testing. Please help to check. Thanks!

**Comment by ema2159** [comment]
Which themes have this problem?

**Comment by seagle0128** [comment]
AFAIK, all themes have this issue. But it's easy to fix it.

```elisp
;; Line 94
(modeline-fg     fg)
```

**Comment by hlissner** [comment]
As of 90078d2 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by seagle0128** [comment]
Thank you! It works.
