### ISSUE TITLE
doom-challenger-deep: not enough contrast for header-line

### ISSUE THREAD

**Issue by sebasmonia** [hlissner/emacs-doom-themes#320]
I see that it is defined in core as having the same color as the mode line, but it's really hard to distinguish the header row in tabulated-list-mode with this theme.

Changing the color, or adding an underline, would be great.

**Comment by ema2159** [comment]
Please upload an screenshot.

**Comment by sebasmonia** [comment]
![Packages-Default](https://user-images.githubusercontent.com/1651857/63180408-73b62180-c00b-11e9-9909-758615aa0bf1.png)

This is how it looks by default in for example, packages.
Adding an underline with the same color that is used for identifiers (just to highlight the difference, I'm terrible at design and there's probably a better way to do this):

![Packages-Added underline](https://user-images.githubusercontent.com/1651857/63180472-96e0d100-c00b-11e9-9d4c-6cb90dad76d2.png)

```(face-spec-set 'header-line '((t :underline "#906cff")))```

**Comment by sebasmonia** [comment]
The current patch in my config is `(face-spec-set 'header-line '((t :background "#23214b")))` which gives:

![2019-08-20 07_19_54- emacs - Emacs](https://user-images.githubusercontent.com/1651857/63350604-f5af8e80-c31a-11e9-90ab-8cbeedc15fad.png)

**Comment by ema2159** [comment]
If I'm not wrong, that has to do more with `solaire-mode`

**Comment by sebasmonia** [comment]
Unless it comes included with doom-themes, I _do not_ use `solaire-mode`.

**Comment by hlissner** [comment]
As of 814e4a2 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
