### ISSUE TITLE
vterm lighter colors

### ISSUE THREAD

**Issue by seanfarley** [hlissner/emacs-doom-themes#324]
This is a follow-up to a discussion on discord about using `vterm`'s `:background` attributes to get lighter colors.

Currently, I have this set to get a gray-ish color in the `nord` theme:

```lisp
(set-face-attribute 'vterm-color-black nil
                    :background "#9099AB")) ;; a very bright grey
```

**Comment by hlissner** [comment]
I'm a bit hazy on the specifics of this discussion. Are you requesting a lighter background for `vterm-color-black` for the nord theme?

**Comment by seanfarley** [comment]
Hmm, that is a good question. Digging up the discussion on discord (searching for `vterm-color-black`), I remembered it was this:

> I'm hoping that maybe someone here can help me with emacs colors not quite looking the same as iTerm2 draws it:

![67801712_694097461035373_5789335981924548608_n](https://user-images.githubusercontent.com/20887/71788558-66103100-2fd8-11ea-8cfb-b51f05ecd53e.png)

![68850771_899496593758041_7377139190292545536_n](https://user-images.githubusercontent.com/20887/71788562-6dcfd580-2fd8-11ea-8986-04e1023ebae6.png)

> The second one is emacs (vterm-mode, specifically)
I'd like to try and get it to match the first one, if possible, but I don't know how to find out what color that is

`flat` replied (a few messages down):

```lisp
(set-face-attribute 'vterm-color-red nil
                    :foreground (get-red-color)
                    :background (get-bright-red-color))
```

and Gagbo followed up with:

> Doom-themes usually only have 1 variant of red/blue/green... And we can't just take doom-lighten or doom-darken for the 'bright' version because it depends on the theme (is it a dark or a light theme ?)

So, I guess my request is to somehow figure out the bright version automatically?

**Comment by obar** [comment]
> and Gagbo followed up with:
> 
> > Doom-themes usually only have 1 variant of red/blue/green... And we can't just take doom-lighten or doom-darken for the 'bright' version because it depends on the theme (is it a dark or a light theme ?)
> 
> So, I guess my request is to somehow figure out the bright version automatically?

Not following the overall question but it might be relevant to point to [`doom-blend`](https://github.com/hlissner/emacs-doom-themes/blob/ddb9880c6884cbb99ec2e3a970cc765044bd5ee4/doom-themes.el#L267-L269). If you blend with a high `base` (eg `base8`), you get a darker color in a light theme and lighter color in a dark theme. With `base0` the opposite will happen. Hope that is helpful.

**Comment by seanfarley** [comment]
I have no idea what the current status of this issue is

**Comment by seanfarley** [comment]
I don't think this is an issue anymore (just commented out my hack and the colors seem correct) so I'll go ahead and close it
