### ISSUE TITLE
opera-light: contrast problem with childframe

### ISSUE THREAD

**Issue by alexandergraul** [hlissner/emacs-doom-themes#328]
I use doom and enabled company and ivy to use childframes:
```elisp
(doom! :completion
       (company
        +childframe)      ; the ultimate code completion backend
       (ivy               ; a search engine for love and life
        +childframe
        +icons
        +fuzzy))
```

When I tried out opera-light, I can't make out what line I am currently on in. In the screenshot below I have the first row selected (I pressed enter after taking the screenshot to see what line I was one).
![opera-one-childframe](https://user-images.githubusercontent.com/19352524/63772267-080c6800-c8d9-11e9-960f-639eaf40113c.png)

**Comment by ema2159** [comment]
@alexandergraul are you using `ivy-posframe`?

**Comment by alexandergraul** [comment]
Yes, that is what doom installs with `ivy +childframe`.

**Comment by ema2159** [comment]
Sorry, I forgot about this. It really easy to solve
