### ISSUE TITLE
Support for org-agenda

### ISSUE THREAD

**Issue by rjww** [hlissner/emacs-doom-themes#33]
Would love to see the theme extended into Org-mode's agenda view.

**Comment by hlissner** [comment]
Certainly. Could you offer a screenshot or two of how the agenda view looks to you? I'm still working on a huge overhaul of org-mode in my emacs.d, so I'm having some trouble telling apart my org-agenda from vanilla!

**Comment by rjww** [comment]
Sure, here are a few shots. The first one is the agenda with vanilla Org-mode faces from **doom-one**. The second is the agenda with some Org-mode face overrides I've pushed in my config (just throwing this one in there as a suggestion, because I think Org needs less visual differentiation). Last shot is the calendar in **doom-one**, which as you can see looks awesome and clean.

<img width="1440" alt="agenda-1" src="https://cloud.githubusercontent.com/assets/13082015/21847653/ef592caa-d84c-11e6-9155-778df3212c7b.png">
<img width="1440" alt="agenda-2" src="https://cloud.githubusercontent.com/assets/13082015/21847658/f78fd446-d84c-11e6-9386-ffde18b1af89.png">
<img width="1440" alt="calendar" src="https://cloud.githubusercontent.com/assets/13082015/21847659/f951cabe-d84c-11e6-879e-84244473211d.png">

**Comment by hlissner** [comment]
It has been a while, and many org-mode (and org-agenda) faces have been added recently. If you are still using this theme, do you think its org-agenda support is sufficient now?

**Comment by hlissner** [comment]
org-agenda support should be good enough that we can consider this resolved. Thanks for the screenshots!

**Comment by yiufung** [comment]
It looks great on org-agenda, but seems some settings are overwritten in org-habit faces. 

Normally, it would look like this (zenburn):

![2018-09-18-234351_629x156_scrot](https://user-images.githubusercontent.com/1023375/45699526-b887cd00-bb9c-11e8-9d04-20de0d7d8c06.png)

In all doom-themes, the foreground and background becomes same color and effectively hides it. 

![2018-09-18-234040_695x159_scrot](https://user-images.githubusercontent.com/1023375/45699443-85ddd480-bb9c-11e8-814a-ddaff7b1a79d.png)
![2018-09-18-234105_644x423_scrot](https://user-images.githubusercontent.com/1023375/45699450-88d8c500-bb9c-11e8-9ae8-de3f1ba0f96a.png)

Would you mind taking a look?

**Comment by hlissner** [comment]
@yiufung Thanks for letting me know. This should've been addressed in https://github.com/hlissner/emacs-doom-themes/commit/aaf04351c004d6dd311f3d7e9a48c3a0fff3d839. Please update and let me know if you think it needs more work.

**Comment by yiufung** [comment]
Works great, thanks!
