### ISSUE TITLE
[Feature request] Customize PDFtools midnight mode

### ISSUE THREAD

**Issue by ashfaqfarooqui** [hlissner/emacs-doom-themes#338]
Change the colors of pdfview mighnight mode to match those of the theme.

Similar to this issue elsewhere: https://github.com/bbatsov/zenburn-emacs/issues/238

**Comment by ashfaqfarooqui** [comment]
The solution seems pretty straight forward. I use this:
```lisp
  (setq pdf-view-midnight-colors '("#bbc2cf" . "#282c34"))
```
and its fixed. The two numbers are foreground and background. 


```lisp
  (setq pdf-view-midnight-colors '(bg . fg))
```

It should be a straightforward fix, but I haven't tested it sufficiently to say it doesn't break anything else.

**Comment by hlissner** [comment]
As of f650b39 this should be resolved. Let me know if that isn't the case and I'll reopen the issue. Thanks for bringing it to my attention!

**Comment by LibreDrip** [comment]
Not working again. Outside of the config file it works with:

`
(setq pdf-view-midnight-colors (cons (doom-color 'fg) (doom-color 'bg)))
`

but it is reset on for instance theme change.
