### ISSUE TITLE
Visual bell doesn't work in some themes

### ISSUE THREAD

**Issue by seagle0128** [hlissner/emacs-doom-themes#339]
https://github.com/hlissner/emacs-doom-themes/blob/668250b967c0d4060653f318480854bbc7d97c17/doom-themes-ext-visual-bell.el#L12

These new changes (with `face-remap-add-relative`) brought regression issues for some themes, e.g. doom-snazzy. While it does work with the legacy codes.

What's more, I think the `doom-visual-bell` face is not compatible with `doom-modeline`. It should be like this.

```elisp
(defface doom-visual-bell `((t (:background ,(face-foreground 'error))))
  "Face to use for the mode-line when `doom-themes-visual-bell-config' is used."
  :group 'doom-themes)
```

**Comment by hlissner** [comment]
I've fixed the face, but I'm not sure how else this doesn't work. Could you expand on "regression issues"?

**Comment by seagle0128** [comment]
It works well on my env and no side effects are found. Thank you!
