### ISSUE TITLE
Switching between tomorrow-day/night breaks ivy match colors

### ISSUE THREAD

**Issue by memeplex** [hlissner/emacs-doom-themes#341]
Here I started emacs with doom-tomorrow-day:

![image](https://user-images.githubusercontent.com/2845433/66609507-a144c480-eb8f-11e9-8da6-d69b805eaec6.png)

This is after switching to doom-tomorrow-night and returning back to doom-tomorrow-night:

![image](https://user-images.githubusercontent.com/2845433/66609599-e537c980-eb8f-11e9-87ab-6d35c8e03e7f.png)

**Comment by memeplex** [comment]
I'm not sure whether this counts as a bug or not. Maybe it's recommended practice to disable previous theme before applying a new one. For example, you can advice `load-theme` as:

```
(defadvice load-theme (before theme-dont-propagate activate)
  (mapcar #'disable-theme custom-enabled-themes))
```

**Comment by ema2159** [comment]
Precisely! If you don't disable the enabled themes before loading another one this kind of problems will arise. 
For example, let saw we have a theme1 and theme2, and a faceX. If theme1 sets the background and foreground properties of faceX, but theme2 just sets faceX's foreground property, when loading theme2, theme1's background property will persist in faceX.

**Comment by ema2159** [comment]
@memeplex shall I close the issue?

**Comment by memeplex** [comment]
I'm doing it, thanks!
