### ISSUE TITLE
Unhighlighted lines are using bg-alt with Oceanic Next

### ISSUE THREAD

**Issue by beojan** [hlissner/emacs-doom-themes#343]
![image](https://user-images.githubusercontent.com/3727925/67195133-537e5680-f3f0-11e9-8ca1-8a450ebc6f2a.png)

**Comment by hlissner** [comment]
Are you using solaire-mode? If so, does `(solaire-mode-swap-bg)` fix the issue?

**Comment by beojan** [comment]
Yes, but the line below the modeline (not sure what that's called) is now in `bg-alt`. 

The problem might be because `bg-alt` is lighter than `bg` in this theme. Perhaps `bg-alt` should be switched to something darker (like `#15222a`) in combination with `(solarire-mode-swap-bg)`.

**Comment by beojan** [comment]
I tried this (by hacking the theme file in `.local/straight/...`, and it seems to work well.

**Comment by ema2159** [comment]
> bg-alt should be switched to something darker

I've thought about this before, I think this the way to go. I would like to see how it is in other editors before though to take the color from there.

**Comment by ema2159** [comment]
Done! I hope the results are as expected, if not, don't be afraid to reopen the issue!
