### ISSUE TITLE
dashboard from doom-emacs standalone?

### ISSUE THREAD

**Issue by thorstengrothe** [hlissner/emacs-doom-themes#346]
Hi,
Is it possible to run the dashboard from doom-emacs standalone with doom-themes? I hope this is the right place to ask this question?

Regards
Thorsten

**Comment by hlissner** [comment]
This is not possible. Doom's dashboard is built specifically for Doom. There are no plans to extract it into its own plugin. I'd recommend looking into [dashboard.el](https://github.com/emacs-dashboard/emacs-dashboard), as an alternative. 

As an aside, besides the fact that doom-emacs uses doom-themes, there isn't any other relation between the two projects. This would be better asked [on the Doom Emacs issue tracker](https://github.com/hlissner/doom-emacs/issues).

**Comment by thorstengrothe** [comment]
Thank you for the fast response and the hint for Doom Emacs issue tracker, sorry for the noise here.
I know dashboard.el but doom dashboard is better in my opinion, well that's it ...

**Comment by hlissner** [comment]
Not a problem! I'm happy to help, and to hear you like Doom's dashboard. I'll look into making it a standalone package, but it will be a while until I get to it. In any case, I will consider this issue resolved. Cheers!
