### ISSUE TITLE
doom-city-lights not working correctly

### ISSUE THREAD

**Issue by BeneathCloud** [hlissner/emacs-doom-themes#349]
I loaded doom-city-lights, and it seems that some parts are not being rendered correctly.
I just uses doom-themes without doom-emacs, but if I use doom-emacs, the city-lights theme can be rendered correctly.
Below is the capture in sml-mode:
(e.g. the numbers should be red)
<img width="1440" alt="截屏2019-10-2623 19 26" src="https://user-images.githubusercontent.com/19836675/67620948-10d0da00-f847-11e9-89f5-13306738b3e3.png">

**Comment by hlissner** [comment]
This is because doom-emacs uses the [highlight-numbers](https://github.com/Fanael/highlight-numbers) plugin.
