### ISSUE TITLE
Org outline background doesn't look so good

### ISSUE THREAD

**Issue by r-darwish** [hlissner/emacs-doom-themes#357]
![image](https://user-images.githubusercontent.com/1383193/68746791-001fb280-0602-11ea-81cf-880a0797f4c8.png)

[Here](https://github.com/hlissner/emacs-doom-themes/blob/50da9726732e1f26fa0e4dd63f3f8041016db47d/doom-themes-base.el#L1206) the doom theme sets a background for `outline-1` in all the themes. Specifically in org mode it looks somewhat like a glitch. If the title has an ellipsis then the background stretches until the ellipsis, and if does not, it stretches until the end of the line. Also, the background doesn't effect the priority.
I think that this background should be removed.

**Comment by hlissner** [comment]
The outline backgrounds (and :height's) were removed in fd12839, so I'll consider this resolved.

**Comment by chuxubank** [comment]
> The outline backgrounds (and :height's) were removed in [fd12839](https://github.com/hlissner/emacs-doom-themes/commit/fd12839e9aef8d0d413c94578632f8429e9cd8cd), so I'll consider this resolved.

The `height` or `weight` should not be removed, since themes like `doom-dracula` do great job in displaying them. Without these configs, the outline is less distinguishable.

**Comment by hlissner** [comment]
@chuxubank :weight was not removed -- org headings are still bold -- only their :height's and :background's were. I removed :weight from some of them because they're inheriting from another face that was already bold (so it was redundant).

If you'd like to bring :height's back, add this to your config:

```elisp
(custom-set-faces
 `(org-level-1 ((t (:inherit outline-1 :height 1.2)))))
```

**Comment by chuxubank** [comment]
@hlissner Get it.

Nice solution, thanks a lot!
