### ISSUE TITLE
doom-tomorrow-day bg color and bg-alt color reversed

### ISSUE THREAD

**Issue by mgourd** [hlissner/emacs-doom-themes#362]
<img width="707" alt="Screen Shot 2019-12-05 at 10 21 15 AM" src="https://user-images.githubusercontent.com/29856997/70198381-b54d1280-1749-11ea-8798-d64b628abf8f.png">

I'm using Emacs plus 26.3
macOS 10.15

**Comment by hlissner** [comment]
The theme's `bg` and `bg-alt` are the right way around, but `solaire-mode` expects you to call `solaire-mode-swap-bg` for themes where they need to be swapped. Doom Emacs' `:ui doom` module should've done this for you. It has been fixed there. Thanks for bringing it to our attention.
