### ISSUE TITLE
Popup border separator

### ISSUE THREAD

**Issue by rakanalh** [hlissner/emacs-doom-themes#369]
Hello,

When showing multiple popups, there is no border separating those popups which makes it a bit confusing visually as to which is what. 
![DeepinScreenshot_20200104014301](https://user-images.githubusercontent.com/195829/71757112-ac0fac80-2e93-11ea-84f4-4c273d30c64e.png)

In the screenshot attached, i have the rustic compilation popup and below that a terminal (vterm) and it can be noticed that it's hard to tell there are two popups because of the lack of the separator.

**Comment by hlissner** [comment]
@rakanalh Turn on `window-divider-mode` and a border should become visible.

**Comment by rakanalh** [comment]
as discussed on Discord, 
```
(custom-set-faces! '(window-divider :foreground "white"))
```

is what works to change the color of window-divider which on `tomorrow-night` uses a color that is very close to the base color of the theme.

**Comment by hlissner** [comment]
As of c563e6f the window border should be much more visible. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
