### ISSUE TITLE
Gruvbox light?

### ISSUE THREAD

**Issue by mpardalos** [hlissner/emacs-doom-themes#373]
Is there any chance to include the gruvbox light theme? The dark theme is the main theme I use from here and I think it would be nice to have a matching light version. 

It's already ported here, with a few variations: https://github.com/morhetz/gruvbox.

**Comment by ema2159** [comment]
How different it's from the dark version? The syntax remains the same am I right?

**Comment by mpardalos** [comment]
I think so. It should simply be a change in the colors

**Comment by ema2159** [comment]
Ok cool, I'll try to do it soon.

**Comment by ema2159** [comment]
Merged!
