### ISSUE TITLE
treemacs root icon broken?

### ISSUE THREAD

**Issue by mattsawyer77** [hlissner/emacs-doom-themes#378]
Hello (and apologies if this isn't the right repo for this issue...):

It seems the treemacs root icon is now mapped to something incorrect? 

![Screen Shot 2020-01-22 at 12 03 50 PM](https://user-images.githubusercontent.com/236582/72930006-d379cc80-3d0f-11ea-9897-4c0fce032b29.png)

I switched the treemacs buffer to text-mode and took a look at the character that looks like "fi":
```
             position: 2 of 451 (0%), column: 1
            character:  (displayed as ) (codepoint 61441, #o170001, #xf001)
              charset: unicode (Unicode (ISO10646))
code point in charset: 0xF001
               syntax: w 	which means: word
             category: L:Left-to-right (strong)
             to input: type "C-x 8 RET f001"
          buffer code: #xEF #x80 #x81
            file code: #xEF #x80 #x81 (encoded by coding system utf-8)
              display: by this font (glyph code)
    mac-ct:-*-Arial Rounded MT Bold-bold-normal-normal-*-36-*-*-*-p-0-iso10646-1 (#xC0)

Character code properties: customize what to show
  general-category: Co (Other, Private Use)
  decomposition: (61441) ('')

There is an overlay here:
 From 1 to 13
  face                 hl-line
  priority             -50
  window               [Show]


There are text properties here:
  display              [Show]
  face                 (:family "github-octicons" :height 1.44 :inherit treemacs-root-face)
  font-lock-face       (:family "github-octicons" :height 1.44 :inherit treemacs-root-face)
  fontified            t
  rear-nonsticky       t
```

I've tried cleaning out .emacs.d and reinstalling doom from scratch, switching themes, etc. but I'm not sure what's going on here.

**Comment by ema2159** [comment]
I had a similar problem before but I'm not sure this is the case. I had a package which for some arbitrary reason modified some of my icons. Did the icons worked properly before for you? When did it start looking like that?

**Comment by hlissner** [comment]
Are you sure you've installed all-the-icons icon fonts? e.g. `M-x all-the-icons-install-fonts`. 

If you're on Windows, this will only download them, you'll need to install them manually afterwards.

If you're on mac/linux this should download and install them for you.

**Comment by Nollo** [comment]
Same issue here.
`all-the-icons` is installed and I see correct icons in modeline for example.

**Comment by hlissner** [comment]
Hmm, I'm seeing this problem too. I'm not sure what changed. I suspect treemacs. It's the only package in the stack that is active.

**Comment by ema2159** [comment]
In which theme does this happen?

**Comment by mattsawyer77** [comment]
I checked a couple of doom themes, city lights and challenger deep.

**Comment by Alexander-Miller** [comment]
I don't think that's on me. All I did recently is use a different icon in https://github.com/Alexander-Miller/treemacs/commit/d539f7bfa0cf97383a3e15688d904c14d4d94aa9, but that's just a different png file, I haven't made any fundamental changes here.

The face and font-lock-face properties being set points to changes made by doom. Is it normal for the display property being used anyway? That is how tre(emacs) displays images.

To make sure this is not a pure treemacs problem you can clone the package and run `make clean-start` (you will also need cask).  That will start a clean emacs instance with only treemacs and its dependencies loaded. 

Doom is using straight.el for package management, right? Then you should be able to specify which version you want to use. If the cause is a change in treemacs you can track it down with a simple binary search.

**Comment by ema2159** [comment]
That's really odd. Those changes are on me but the only thing I changed was this: 3d3ebfc, and it's not causing me any problems. Could that be the source of the problem?

**Comment by mattsawyer77** [comment]
@ema2159 I tried reverting your commit locally, and it fixed the problem. The root icon looks like a book again.

**Comment by ema2159** [comment]
Hmmm, that's odd, it's weird that that happens with that icon specifically but not with other icons. Could you try the colorful theme instead of the atom one and see if the file icons display correctly?

**Comment by mattsawyer77** [comment]
@ema2159 I don't think I have that theme installed. Did you mean, try a non-doom theme?

**Comment by ema2159** [comment]
That comes with doom-themes. Just before `(doom-themes-treemacs-config)` you have to put `(doom-themes-treemacs-theme "doom-colors")`

**Comment by mattsawyer77** [comment]
Ah, I thought you meant the main doom-theme. I switched the treemacs theme to "doom-colors" and I see different icons, but the original issue with the root icon is still there.

**Comment by ema2159** [comment]
I'm sorry, that's indeed the cause of the error. The face assigned inherits another font-family overwriting the all-the-icons font. The thing is, I don't quite understand why the error doesn't happen to me. I'll fix it right away.

**Comment by ema2159** [comment]
@mattsawyer77 please tell me if the last commit fixes your issue.

**Comment by Nollo** [comment]
@ema2159 it works for me

Thanks :)

**Comment by mattsawyer77** [comment]
@ema2159 that did fix it. thanks!
