### ISSUE TITLE
doom themes override other themes' colors

### ISSUE THREAD

**Issue by Nathan-Furnal** [hlissner/emacs-doom-themes#381]
Hi, 

I initally opened an [issue](https://github.com/kunalb/poet/issues/18) at `poet-theme` because it wasn't displaying properly but when I removed `doom-themes` it did display properly. So it turns out that `doom-themes` seems to override the faces' colors.

How can I fix this?

Thanks a ton for the hard work

**Comment by ema2159** [comment]
Do you have both loaded at the same time?

**Comment by Nathan-Furnal** [comment]
Yes ! I'm loading both to have a function switch from poet to doom-material when it's the evening

**Comment by ema2159** [comment]
Ok, are you disabling one theme before enabling the other?

**Comment by Nathan-Furnal** [comment]
I'm not, that was my mistake, for posterity, I used that function thanks for the quick answer :
```

(defadvice load-theme (before clear-previous-themes activate)
  "Clear existing theme settings instead of layering them"
  (mapc #'disable-theme custom-enabled-themes))
```

**Comment by ema2159** [comment]
Awesome!
