### ISSUE TITLE
treemacs file name misalignment

### ISSUE THREAD

**Issue by taigacute** [hlissner/emacs-doom-themes#387]
like this pic
![image](https://user-images.githubusercontent.com/41671631/73591588-61815e80-452b-11ea-977a-782609409d8d.png)

## config
```elisp
(use-package doom-themes
  :init
  (defun load-doom-one ()
    (load-theme 'doom-one :no-confirm)
    (solaire-mode-swap-bg))
  :hook (after-first-make-frame . load-doom-one)
  :config
  ;; Global settings (defaults)
  (setq doom-themes-enable-bold t    ; if nil, bold is universally disabled
        doom-themes-enable-italic t) ; if nil, italics is universally disabled
  ;; Enable flashing mode-line on errors
  (doom-themes-visual-bell-config)
  ;; or for treemacs users
  (setq doom-themes-treemacs-theme "doom-colors") ; use the colorful treemacs theme
  (doom-themes-treemacs-config)
  ;; Corrects (and improves) org-mode's native fontification.
  (doom-themes-org-config))

(use-package solaire-mode
  :when (or (daemonp) (display-graphic-p))
  :defer t
  :config
  (solaire-global-mode +1)
  :hook
  ((change-major-mode after-revert ediff-prepare-buffer) . turn-on-solaire-mode)
  (minibuffer-setup . solaire-mode-in-minibuffer))

```

**Comment by taigacute** [comment]
if i removed `(doom-themes-treemacs-config)` . it works well.

**Comment by hlissner** [comment]
There are a number of file extensions that our treemacs plugin doesn't correctly set. The ones I'm aware of: nix, go, and .gitignore files.

Since I don't use treemacs/neotree anymore I haven't gotten around to fixing this. A PR is welcome!

**Comment by ema2159** [comment]
This is more of an `all-the-icons` problem in fact. The thing is, not all the icons come from the same font family, so they don't have the same width and they constantly cause problems like this one.

**Comment by taigacute** [comment]
@ema2159  yes, i tried some others themes like base16-theme. got same problem

**Comment by ema2159** [comment]
I will close this issue given there's nothing much that can be done here. If in a near future I find a solution I'll submit it to all the icons.

**Comment by hlissner** [comment]
You can try increasing the tab-width in the treemacs buffer:

```elisp
(add-hook 'treemacs-mode-hook (lambda () (setq tab-width 2)))
```
