### ISSUE TITLE
Using (doom-themes-treemacs-config) also changes the faces configuration for treemacs-icons-dired-mode

### ISSUE THREAD

**Issue by CSRaghunandan** [hlissner/emacs-doom-themes#388]
As the title implies, setting the `doom-themes-treemacs-config` also change the respective faces in dired when `treemacs-iconcs-dired-mode`

Can I do something to disable the faces in dired being changed? Because it looks completely off. Attached screenshot below for reference.

![screenshot-2020-02-02_19-13-38](https://user-images.githubusercontent.com/5226809/73609111-652ae900-45f0-11ea-9f24-4fcd2b9e10ca.png)

**Comment by ema2159** [comment]
I don't think that's something to be fixed here. We just use Tremmacs's API to configure it's icons, and nothing more than that. The real problem here is that you're using treemacs-icons-dired, which grabs the exact same icons from treemacs and puts them in dired (hence the name). A solution would be to use another plugin like all-the-icons-dired instead (that's what I use), to display the same icons, but without the chevrons in the directory icons.

**Comment by CSRaghunandan** [comment]
> I don't think that's something to be fixed here. We just use Tremmacs's API to configure it's icons, and nothing more than that. The real problem here is that you're using treemacs-icons-dired, which grabs the exact same icons from treemacs and puts them in dired (hence the name). A solution would be to use another plugin like all-the-icons-dired instead (that's what I use), to display the same icons, but without the chevrons in the directory icons.

I see, so the problem is with treemacs API then? So, does this issue belong in treemacs issue tracker?

How is the performance of all-the-icons-dired when a directory has many files/folders. If it is acceptable I don't mind using it.

And, what are chevrons in the directory icons?

**Comment by ema2159** [comment]
I don't think that's an issue, the package just does what it's supposed to, and I think the problem really is that treemacs-icons-dired it's supposed to be used with treemacs's default theme. all-the-icons-dired works pretty well and it's easy to configure!

The chevrons are the ">" symbols at the left of the directory icons.

**Comment by CSRaghunandan** [comment]
I see, I'll give `all-the-icons-dired` a try and see how it works.

Thanks

**Comment by CSRaghunandan** [comment]
@hlissner I think I found what the problem here is.

The function `doom-themes-fix-treemacs-icons-dired-mode` in `doom-themes-ext-treemacs` is supposed to set the `tab-width` to `1` inside dired-buffers, but for some reason, its failing to do so and you end up the result I showed in screenshot in the first post.

For now, I'm manually setting the local variable for `tab-width` in `dired` buffers to 1 as a temporary workaround.

Hope this helps you to fix the problem.

**Comment by hlissner** [comment]
I've fixed `doom-themes-fix-treemacs-icons-dired-mode` in aa215ed. Let me know if that isn't the case and I'll reopen the issue. Thanks for bringing it to my attention!

**Comment by CSRaghunandan** [comment]
> I've fixed `doom-themes-fix-treemacs-icons-dired-mode` in [aa215ed](https://github.com/hlissner/emacs-doom-themes/commit/aa215edcc22577ad89a6e6c8943623fb09d1b783). Let me know if that isn't the case and I'll reopen the issue. Thanks for bringing it to my attention!

Thanks, I'll check it out and get back to you.

**Comment by CSRaghunandan** [comment]
@hlissner issue is fixed after updating to the latest commit.

Thank you :)
