### ISSUE TITLE
Using doom-themes-treemacs-config changes the font in treemacs

### ISSUE THREAD

**Issue by CSRaghunandan** [hlissner/emacs-doom-themes#389]
I'll attach a screenshot for reference. All the others have a different font except for treemacs when using `doom-themes-treemacs-config`. Was this intentional ? If so, can I revert to using the same font as the default one I'm using in emacs?

Thanks

**Comment by ema2159** [comment]
Yes, this is intentional, and yes, you can revert that by setting the treemacs faces that you want changed after the theme loads.

**Comment by CSRaghunandan** [comment]
How do I change the font via set-face-attribute? Can you please give an example?

**Comment by ema2159** [comment]
What faces do you want changed? Please show me!

**Comment by CSRaghunandan** [comment]
I want the filenames/directory names in treemacs to be changed to the default font I use.

But after doing a quick search of faces under treemacs, looks like there are many faces which needs to be changed. I'd rather not do that, I guess I will just use it as it is.

Thanks

**Comment by ema2159** [comment]
You're welcome brother!

**Comment by hlissner** [comment]
@CSRaghunandan You're probably talking about the variable pitch fonts. `(setq doom-themes-treemacs-enable-variable-pitch nil)` will disable it.
