### ISSUE TITLE
`challenger-deep` comments in active Org source blocks are illegible

### ISSUE THREAD

**Issue by matthew-piziak** [hlissner/emacs-doom-themes#390]
In `challenger-deep`, `secondary-selection-face` has background #565575 and `font-lock-comment-face` has _foreground_ #565575, which makes comments disappear in active Org source blocks.

![challenger-deep](https://user-images.githubusercontent.com/6801001/73615300-b0cf9980-45d4-11ea-815c-4983850055bb.png)

**Comment by ema2159** [comment]
Nice catch, I'll solve it as soon as possible

**Comment by ema2159** [comment]
Wait a second, that isn't a default org source block am I right? What do I need to do to reproduce the problem? I use org, but not much so there's functionalities I'm not aware of.

**Comment by hlissner** [comment]
@ema2159 

1. Load challenger-deep theme.
2. Open an org file, 
3. Create a src block, say:

   ```elisp
   #+BEGIN_SRC elisp
   ;; Here are some useful comments
   (message "Hello world")
   #+END_SRC
   ```

4. Place cursor inside the src block
5. Press `C-c '` to invoke `org-edit-special`
6. While the "edit buffer" is open, the original src block is highlighted with `secondary-selection-face`, apparently.

**Comment by ema2159** [comment]
Nice! Ok, I'll fix it then

**Comment by matthew-piziak** [comment]
Thank you @ema2159! Looks great!

![deep](https://user-images.githubusercontent.com/6801001/73795480-bb2a9880-4778-11ea-8a3b-4eca529fbdf9.png)

**Comment by ema2159** [comment]
You're welcome brother!
