### ISSUE TITLE
Screenshot for outrun-electric

### ISSUE THREAD

**Issue by alphapapa** [hlissner/emacs-doom-themes#393]
@ema2159 outrun-electric needs a screenshot.  :)  

![eoe](https://user-images.githubusercontent.com/601365/73796223-52402200-4772-11ea-94ec-8786939e0fe3.png)

This isn't DOOM, but it still looks nice, so feel free to use it.  It's Elisp code using https://github.com/alphapapa/prism.el.  Or feel free to decline if it's not quite what you're looking for.  I just think people should have a chance to see what they're missing by not using this theme!  :)

**Comment by ema2159** [comment]
That's very nice! I've been a little bit lazy with the screenshots and I've postponed them for too long already so this helps a lot. Could you take another one showing a little bit of the UI? Like showing treemacs/nerd-tree or Ivy/helm? It would be great if you could do that!

**Comment by ema2159** [comment]
Done! Updated all the screenshots from all themes (made them all equal because my OCD wouldn't let me do it any other way). Thank you for finally make me do it! I've postponed it for too long :sweat_smile:

**Comment by alphapapa** [comment]
https://www.reddit.com/r/emacs/comments/ezetx0/doomthemes_screenshots_updated_good_time_to_go/  :)

**Comment by ema2159** [comment]
Thanks man! You're awesome!
