### ISSUE TITLE
Got an error when open treemacs

### ISSUE THREAD

**Issue by taigacute** [hlissner/emacs-doom-themes#395]
```
treemacs-RET-action: Wrong type argument: listp, #(" 	" 1 2 (face (:family "github-octicons" :height 1.44 :inherit doom-themes-treemacs-root-face) font-lock-face (:family "github-octicons" :height 1.44 :inherit doom-themes-treemacs-root-face) display (raise -0.12) rear-nonsticky t))
```
![image](https://user-images.githubusercontent.com/41671631/73933287-15f9f680-4917-11ea-8cf9-7379d8436023.png)

**Comment by ema2159** [comment]
Do you have all the icons fonts installed?

**Comment by hlissner** [comment]
Please include a backtrace when reporting errors. To produce one, enable debug-on-error with `M-x toggle-debug-on-error`, then recreate the error.

**Comment by thinkiny** [comment]
Debugger entered--Lisp error: (wrong-type-argument listp #(" \011" 1 2 (face (:family "github-octicons" :height 1.44 :inherit doom-themes-treemacs-root-face) font-lock-face (:family "github-octicons" :height 1.44 :inherit doom-themes-treemacs-root-face) display (raise -0.12) rear-nonsticky t)))
  treemacs--evade-image()
  treemacs-RET-action(nil)
  funcall-interactively(treemacs-RET-action nil)
  call-interactively(treemacs-RET-action nil nil)
  command-execute(treemacs-RET-action)

**Comment by hlissner** [comment]
This appears to be an upstream issue, with the `treemacs--evade-image` function assuming that the `display` text property will always return a list. This would fix it:

```diff
 (defun treemacs--evade-image ()
   "The cursor visibly blinks when on top of an icon.
 It needs to be moved aside in a way that works for all indent depths and
 `treemacs-indentation' settings."
   (when (eq major-mode 'treemacs-mode)
     (beginning-of-line)
-    (when (eq 'image (car (get-text-property (point) 'display)))
+    (when (eq 'image (car-safe (get-text-property (point) 'display)))
       (forward-char 1))))
```

Please report this [upstream](https://github.com/Alexander-Miller/treemacs).

**Comment by Alexander-Miller** [comment]
> This would fix it

That's an option. However I did recently push a patch (in relation to the dired-icon + diff-hl issue) that would change every icon to be a string with a display property. So in theory this the image evasion logic should now always be safe.
 @taigacute try again with an up-to-date treemacs, the error shouldn't happen anymore then.

**Comment by taigacute** [comment]
@Alexander-Miller   not fixed ..

**Comment by hlissner** [comment]
@taigacute Do you use Doom Emacs, per chance? (If not, ignore this:) If so, you'll need to re-pin the treemacs package to the latest commit by adding this to `~/.doom.d/packages.el`:

```elisp
(package! treemacs :pin "05d264ae8c")
```

Then run `doom update`

**Comment by Alexander-Miller** [comment]
Hold up, you guys had it right. The patch is necessary either way, and has just been pushed. @taigacute  try again.

**Comment by taigacute** [comment]
@Alexander-Miller  it works! closed.
