### ISSUE TITLE
doom-opera-light: highlight and cursor color mismatch

### ISSUE THREAD

**Issue by Kaali** [hlissner/emacs-doom-themes#397]
Cursor over an highlight hides the text:

<img width="431" alt="Screenshot 2020-02-12 at 10 54 40" src="https://user-images.githubusercontent.com/30772/74318667-5b3e7e00-4d86-11ea-861f-185ea2238b7b.png">

**Comment by ema2159** [comment]
Gotcha. I'll fix it soon.

**Comment by ema2159** [comment]
@Kaali how do you reproduce this?

**Comment by Kaali** [comment]
I can reproduce it with Emacs 27 (exact commit 0304f53) by starting Emacs without any configuration. Then installing `doom-themes` and `evil-mode` from MELPA.

Enable `evil-mode` and disable `cursor-blink-mode`. Then do a search for a string that exists with '/'. You should see that result. By default evil-mode will hide the highlight after a delay, but for example with doom-emacs it doesn't and the highlight will stay like that.

You can also reproduce this quite easily with doom-emacs, by just using the theme and doing a search.

**Comment by ema2159** [comment]
Done!
