### ISSUE TITLE
Improve lsp-ui-sideline support

### ISSUE THREAD

**Issue by rakanalh** [hlissner/emacs-doom-themes#399]
In doom emacs, activating the `lsp` tool means that lsp-ui is used as well. 

The current version of the themes, specifically `tomorrow-night` which i am using (so not 100% sure about the other themes) has problems such as:

1. The peek layout is not distinguishable (background, border) from the buffer containing it.
2. peek highlight face isn't set on all of the themes apart from `acario-(dark|light)`.

**Comment by gagbo** [comment]
Relevant faces :
https://github.com/hlissner/emacs-doom-themes/blob/1f51ed72282fffc0459dd3e2d059592e8a62c3b6/themes/doom-acario-dark-theme.el#L243-L245

I think a `:foreground highlight` for `lsp-ui-peek-highlight` would be a nice default, and for the `sideline-symbol-info`, reverting the doom-blend call (`comments bg 0.85`) to have a better fallback in 256-color environments would be enough imo

**Comment by gagbo** [comment]
It is actually a problem because now when I switch themes I have very bad colors for the lsp-ui features

**Comment by gagbo** [comment]
@ema2159 Can you edit the title as it's related to `lsp-ui-sideline` and not really `lsp-ui-peek` ?

**Comment by ema2159** [comment]
I don't use lsp that much. I've noticed there's a lot of lsp faces missing in the base file though, I'll need to give it a check soon.

**Comment by gagbo** [comment]
I added a few there https://github.com/hlissner/emacs-doom-themes/pull/412

**Comment by gagbo** [comment]
Can be closed (by #412  )
