### ISSUE TITLE
comment highlighting doesn't work

### ISSUE THREAD

**Issue by Red-Portal** [hlissner/emacs-doom-themes#40]
```LISP
(setq doom-enable-bold t
     doom-enable-italic t

     doom-one-brighter-modeline t ;; doom one specific
     doom-one-brighter-comments t);; commands
(add-hook 'minibuffer-setup-hook 'doom-brighten-minibuffer)
```

this is my current setting
however comments are not hightlighting

**Comment by hlissner** [comment]
Sorry for the late response: could you offer a screenshot of the issue? As well as other information, including emacs version and major mode this occurs in?

Also, just in case: doom-one-brighter-* need to enabled before the theme is loaded (with `load-theme`). I just realized that my README.md loads the theme before adjusting the settings (derp!). I'll fix that soon.

**Comment by Red-Portal** [comment]
![2016-12-15_19-52-32](https://cloud.githubusercontent.com/assets/18320033/23607799/ae0db91e-02a9-11e7-80cf-fa2ca48d0583.jpg)

this is a photo of my state.
[this](https://github.com/Red-Portal/.emacs.d) is the repo of my init file.

one of the symptoms I experienced,
was that if I switch from spacemacs-theme to doom-theme by `load-theme`,
the comments get properly highlighted just for that emacs instance.

**Comment by hlissner** [comment]
Have you tried moving the `(load-theme 'doom-one)` forward, ahead of your `(setq ...)` statements?

**Comment by Red-Portal** [comment]
![2016-12-08_19-21-45](https://cloud.githubusercontent.com/assets/18320033/23645649/8ca894cc-0350-11e7-86fe-d4697bc5a48e.jpg)

Manuall calling `load-theme`, moving `load-theme` up doesn't work

**Comment by Red-Portal** [comment]
I solved the problem. It seems one of the packages I'm using (I suspect `telephone-line` but I'm not sure) is conflicting with doom-theme. Changing the loading order fixed the problem. Also, this problem was not doom-theme specific. Spacemacs-theme also had the problem of comment highlighting.

**Comment by Red-Portal** [comment]
Restarted emacs and the problem came up again. Just calling `load-theme` on doom-theme doesn't work. Manually calling `load-theme` to spacemacs-theme and then changing to doom-themes seems to solve the problem. Huhmm... really strange

**Comment by hlissner** [comment]
Sorry for the delay. I am investigating this again. Has recent updates changed your situation at all?

Have you tried the theme on vanilla emacs? e.g. `emacs -Q` and then:

```emacs-lisp
(add-to-list 'load-path "path/to/doom-themes")
(require 'doom-themes)
(setq doom-one-brighter-comments t)
(load-theme 'doom-one t)
```

I suspect another plugin is interfering. Perhaps `custompackages/font-lock+`? I'm not familiar with font-lock+ to say.
