### ISSUE TITLE
How to best customize a theme color?

### ISSUE THREAD

**Issue by obar** [hlissner/emacs-doom-themes#404]
I'm wondering about customization at an earlier level than individual faces. Is it possible to make overrides of a theme with specific customizations, like changing the `comments` color (beyond the use of the `<theme>-brighter-comments` that exists in many themes)? Change what `green` means for a theme? Or does one have to customize each face where that color is used with `doom-themes-set-faces`?

**Comment by hlissner** [comment]
At the moment, there is no way to do this, no. I'm working on [a rewrite of our API](https://github.com/hlissner/emacs-doom-themer) that will introduce inheritance, that should allow you to, but until then the easiest option is to copy the doom theme you want locally and modify it.

**Comment by obar** [comment]
Thanks! Looking forward to that.

**Comment by ianpan870102** [comment]
Personally I'm using the :custom-face attribute in the use-package macro. Here is one example that I'm currently using, hope it helps!
```emacs-lisp
(use-package doom-themes
  :custom-face ; for solarized dark
  (font-lock-constant-face      ((t (:foreground "#2aa198"))))                       ; solarized cyan
  (highlight-numbers-number     ((t (:foreground "#2aa198"))))                       ; solarized cyan
  (diff-hl-change               ((t (:background "#2aa198" :foreground "#2aa198")))) ; solarized cyan
  (show-paren-match             ((t (:foreground "white" :background "#174652"))))
  (highlight-symbol-face        ((t (:background "#073642")))) ; region (base0)
  :config
  (setq doom-themes-enable-bold nil)
  (load-theme 'doom-solarized-dark t))
```
