### ISSUE TITLE
Spacegray: 'hidden' heading asterisks are visible in org mode

### ISSUE THREAD

**Issue by yoavm448** [hlissner/emacs-doom-themes#405]
The heading asterisks are visible in org mode with spacegray theme, when they're supposed to be hidden (they are in other themes).
![image](https://cdn.discordapp.com/attachments/484105925733646336/678343813844172801/unknown.png)

Henrik said on Discord that its just a matter of tweaking the `org-hide` and `solaire-org-hide-face` faces.

**Comment by ilautar** [comment]
I have the same with zenburn theme.

package.el: (package! zenburn-theme)
config.el: (setq doom-theme 'zenburn)

**Comment by ema2159** [comment]
@ilautar zenburn is not a theme from this package! It is probably bbatsov's zenburn. It's theme specific so I can only solve Spacegrey.

**Comment by ilautar** [comment]
@ema2159 I know, I just mention it if the root cause is outside theme itself.

**Comment by ema2159** [comment]
Found this is a problem with `org-bullets` which hard codes the colors if I'm not wrong. I'm going to see if the repo is still active.

**Comment by ilautar** [comment]
Not sure if this might be the case, but spacemacs is using different version, from here: https://github.com/emacsorphanage/org-bullets

It has few fixes compared to https://github.com/sabof/org-bullets.

Actually, this one with fixes is from ELPA, and the one in straight is old one.

**Comment by ema2159** [comment]
It does. The thing is, I can fix the issue for spacegrey but only for the case where org bullets is disabled.

**Comment by ilautar** [comment]
One more thing which might be related (or not). Now looking at it, the problem in my case is not that asterix (*) has wrong color, they are not hidden (as in removed from visible buffer). This has side-effect of indenting lines 2x (once for visible * and once for replacement space). But this increased indent (2 chars instead of 1) might be by design?

**Comment by ema2159** [comment]
How about this: https://github.com/integral-dw/org-superstar-mode?
