### ISSUE TITLE
[Outrun-electric] vertical border face invisible

### ISSUE THREAD

**Issue by ianpan870102** [hlissner/emacs-doom-themes#406]
In outrun-electric, the vertical-border foreground has the same colour as the background, making a vertical split border invisible. A dark violet (#3f3863) would perhaps be more suitable.

**Comment by ema2159** [comment]
@ianpan870102 can you show me a screenshot?

**Comment by ianpan870102** [comment]
Sure thing. In both screenshots below, I'm splitting the scratch buffer vertically:

### Before
<img width="1440" alt="Screenshot 2020-02-19 at 00 45 56" src="https://user-images.githubusercontent.com/36686900/74757682-4fd0e280-52b1-11ea-9310-ae2c19618cf5.png">

### After
<img width="1440" alt="Screenshot 2020-02-19 at 00 45 34" src="https://user-images.githubusercontent.com/36686900/74757700-54959680-52b1-11ea-9904-85e08ee17037.png">

**Comment by ema2159** [comment]
I used the theme's base5 color, I don't know if that's alright.
