### ISSUE TITLE
caddr is not available on 25.x

### ISSUE THREAD

**Issue by seagle0128** [hlissner/emacs-doom-themes#410]
`caddr` and `cdddr` are not defined in Emacs 25.x.

https://github.com/hlissner/emacs-doom-themes/blob/86424ab3f912f0fc3dfa824144dbba7b95ddfd6f/doom-themes-ext-treemacs.el#L98

https://github.com/hlissner/emacs-doom-themes/blob/86424ab3f912f0fc3dfa824144dbba7b95ddfd6f/doom-themes-ext-treemacs.el#L247

**Comment by gagbo** [comment]
It's pretty old :( But then again https://github.com/hlissner/emacs-doom-themes/blob/master/doom-themes.el#L12

I guess one solution might be to patch this, tag the version for melpa-stable and then upgrade the requirements

**Comment by seagle0128** [comment]
That's definitely a solution. But it's not a good idea to drop 25.x for a theme extension.

**Comment by hlissner** [comment]
> But it's not a good idea to drop 25.x for a theme extension IMO.

Agreed. This should be fixed as of ecffdf8. Thanks for letting me know!

**Comment by seagle0128** [comment]
@hlissner cdddr should be changed as well.

**Comment by hlissner** [comment]
Whoops. Done.

**Comment by seagle0128** [comment]
Cool! Thank you, @hlissner .
