### ISSUE TITLE
Add zenburn theme

### ISSUE THREAD

**Issue by nixmaniack** [hlissner/emacs-doom-themes#415]
I'm not sure if you're accepting such additional theme request but I wanted to see if it's possible since I'm using doom-themes tooling and other doom-themes. 

Reference: https://github.com/bbatsov/zenburn-emacs

Thanks for these awesome set of hight quality themes.

**Comment by ema2159** [comment]
Zenburn could be a pretty nice addition! We would need some time to implement it though.

**Comment by rubic** [comment]
When I assign `(setq doom-theme 'doom-zenburn)` in `config.el` and restart emacs:

  "`xref-file-location-column is already defined as something else than a generic function`"

I can set `doom-theme` to any other value without getting this error.
