### ISSUE TITLE
[feature-request] Support scaling of org-level-* headings when using variable-pitch face

### ISSUE THREAD

**Issue by nixmaniack** [hlissner/emacs-doom-themes#416]
Would it be possible to support `variable-pitch` for `org-level-*` [or at least for level-{1,4}] headings perhaps under a theme variable which toggles this setting?

If it's acceptable, I can give this a try in a PR.

**Comment by hlissner** [comment]
I don't know what you mean by _adding_ support for it. As far as I know the theme supports it just fine. How did you intend on implementing this?

Side note: I'd like to inherit a few select org faces (like `org-code` and `org-table`) from the `fixed-pitch` face, so variable-pitch-mode will render org buffers more sanely. I'll accept a PR to that end.

**Comment by nixmaniack** [comment]
Sorry unclear message. What I meant is support actual different `height`s for different org-levels when using variable-pitch face. 

e.g. [solarized theme](https://github.com/bbatsov/solarized-emacs) does this with theme variable [`solarized-scale-org-headlines`](https://github.com/bbatsov/solarized-emacs/blob/67376b3c41000368d39b3100087f7fdbb7d4097b/solarized-faces.el#L1390-L1401).

**Comment by nixmaniack** [comment]
So use of `variable-pitch` could also be an option as not everyone wants to use variable-pitch in text-editor.

**Comment by hlissner** [comment]
Sorry for the late response. I've decided not to implement a variable like this because a one-off use of `custom-set-faces` is trivial and enough to address this:

```elisp
(custom-set-faces
  '(org-level-1 ((t (:height 1.4))))
  '(org-level-2 ((t (:height 1.3))))
  '(org-level-3 ((t (:height 1.15))))
```

This should work regardless of variable-pitch-mode, mixed-pitch-mode, or other plugins.

In any case, thanks for bringing it to my attention. Hope that helps!

**Comment by ujikol** [comment]
But this seems to fail when for (text-scale-adjust).

I use the nice poet-theme which has faces defined like this:
`(org-level-1 ((t (:inherit default :foreground ,header :height (lambda (_x) (poet-theme--height 1.5))))))`

text-scale-adjust works for most text part but has no effects on org headings.
