### ISSUE TITLE
Add Rouge theme

### ISSUE THREAD

**Issue by lxbarbosa** [hlissner/emacs-doom-themes#417]
Hi, in my transition to porting my Linux/BSD dotfiles to Windows, I've used VSCode for a bit and found an awesome theme there:

Rouge by Josef: https://github.com/josefaidt/rouge-theme

![Rouge Theme](https://raw.githubusercontent.com/josefaidt/rouge-theme/master/img/rouge-desktop-1_4.png)

**Comment by ema2159** [comment]
Looks pretty nice! You'll have to give us some time though, there's plenty of themes in line.

**Comment by lxbarbosa** [comment]
@ema2159 
Take your time, ephemeral is my new passion for now! hehe

**Comment by ema2159** [comment]
@lxbarbosa you can thank @karetsu for Ephemeral! He did a great job both with Ephemera an Horizon.

**Comment by lxbarbosa** [comment]
@ema2159 
I will properly hug him once I find him! hehe

**Comment by lxbarbosa** [comment]
Thanks! 

92493e65039c7cadd17e3ba645ed10eea7c243f0
