### ISSUE TITLE
[Bug] Mismatch parentheses make cursor disappear in Doom Horizon

### ISSUE THREAD

**Issue by ianpan870102** [hlissner/emacs-doom-themes#419]
Due to the way doom-horizon handles mismatch parentheses error highlights, the cursor appears to be "hidden into the background".

**Comment by ema2159** [comment]
Hey! Could you post a screenshot and a set of instructions to reproduce?

**Comment by ianpan870102** [comment]
Absolutely! Consider this simple reproduction:
### Here's how doom-one correctly handles it:
#### Picture 1: Cursor is at the correct closing paren
<img width="644" alt="Screenshot 2020-03-17 at 00 26 38" src="https://user-images.githubusercontent.com/36686900/76779255-07401280-67e6-11ea-8f39-c84cbed46e01.png">

#### Picture 2: Cursor has moved one position to the right (and landed on the dangling extra closing paren)
<img width="644" alt="Screenshot 2020-03-17 at 00 26 49" src="https://user-images.githubusercontent.com/36686900/76779268-0b6c3000-67e6-11ea-9d08-426161aef09e.png">

### Now see how the colour design in doom-horizon makes the cursor disappear

#### Picture 1: Cursor is at the correct closing paren
<img width="670" alt="Screenshot 2020-03-17 at 00 23 02" src="https://user-images.githubusercontent.com/36686900/76778965-9d276d80-67e5-11ea-9010-32d2866f466f.png">

#### Picture 2: Cursor has moved one position to the right (and landed on the dangling extra closing paren)
<img width="669" alt="Screenshot 2020-03-17 at 00 23 18" src="https://user-images.githubusercontent.com/36686900/76779023-afa1a700-67e5-11ea-896f-38ad1799e0a2.png">
Notice that in the second picture where the cursor is on the mismatched paren, it seems as if the cursor has disappeared.
