### ISSUE TITLE
Missing fonts in the modeline

### ISSUE THREAD

**Issue by wilhelmy** [hlissner/emacs-doom-themes#420]
When I installed doom-emacs, I said "yes" when it asked whether or not to install the extra fonts for symbols. I'm getting weird stuff in the modeline though, see image.

![image](https://user-images.githubusercontent.com/4211529/76716105-52e3b500-672f-11ea-989b-d96c703c708d.png)

Any ideas?

**Comment by ema2159** [comment]
What system are you on?

**Comment by wilhelmy** [comment]
Slackware 14.2+, running emacs 26.3

**Comment by ema2159** [comment]
Probably you have to install the fonts (all-the-icons' fonts). I think that the function to install the fonts works on some systems like Ubuntu, Arch etc but for other types of systems usually the user has to install the fonts manually.

**Comment by wilhelmy** [comment]
Alright, I'll look into it. Thanks for the pointer.

**Comment by wilhelmy** [comment]
What strikes me as weird is that most of the icons work, like for instance in neotree
![image](https://user-images.githubusercontent.com/4211529/76789819-e5cb3080-67bd-11ea-8234-1db3774ee3e7.png)
but also in the modeline, so I assume at least some of the fonts are found.
![image](https://user-images.githubusercontent.com/4211529/76789928-26c34500-67be-11ea-9a03-43d58a7128be.png)
Any ideas?

**Comment by wilhelmy** [comment]
```
$ fc-list |grep /home/mw
/home/mw/.local/share/fonts/file-icons.ttf: file\-icons:style=icons
/home/mw/.local/share/fonts/fontawesome.ttf: FontAwesome:style=Regular
/home/mw/.local/share/fonts/all-the-icons.ttf: all\-the\-icons:style=Regular
/home/mw/.local/share/fonts/weathericons.ttf: Weather Icons:style=Regular
/home/mw/.local/share/fonts/octicons.ttf: github\-octicons:style=Regular
```
They're definitely in the list as well.

**Comment by ema2159** [comment]
No, then the fonts are definitely installed, something else is happening. Could you go through the troubleshooting section from all-the-icons repo and see if there's a particular font family that's giving you problems?

**Comment by wilhelmy** [comment]
Seems material-design-icons.ttf isn't installed by doom-emacs. After manually downloading that, putting it with the others and re-running ` (all-the-icons-install-fonts)`, it works now. However this seems to be a bug in either doom-emacs or all-the-icons.

**Comment by ema2159** [comment]
It's very unlikely that it is a Doom bug, since Doom uses all-the-icons' function for installing the fonts. Also, that function has been the same and it's worked for quite some time, it is very unlikely that the function is the problem, but it may be. Also, it could had been a problem during the fonts installation. A way of verifying this is if you delete the fonts and run the functions again and see if the same error occurs.

**Comment by wilhelmy** [comment]
It may have been an http error, I don't think I'll be able to reproduce it.

**Comment by EwanDawson** [comment]
I had the very same issue. Downloading and installing the Material Design font file at https://github.com/google/material-design-icons/blob/master/iconfont/MaterialIcons-Regular.ttf and restarting Emacs resolved the issue for me.
