### ISSUE TITLE
color of diff-hl

### ISSUE THREAD

**Issue by taigacute** [hlissner/emacs-doom-themes#424]
The color of diff-hl it's wired  on doom-tomorrow-night., it's fine on `doom-one`.
![image](https://user-images.githubusercontent.com/41671631/77169556-a4f05600-6af4-11ea-9323-095436c7fba0.png)
![image](https://user-images.githubusercontent.com/41671631/77169630-c94c3280-6af4-11ea-931a-4260a2324e2a.png)

on doom-one 
![image](https://user-images.githubusercontent.com/41671631/77169592-b20d4500-6af4-11ea-8c3c-b0cc3bbd1982.png)
![image](https://user-images.githubusercontent.com/41671631/77169613-c18c8e00-6af4-11ea-8b68-16e44e529345.png)

**Comment by hlissner** [comment]
Was this fixed?

**Comment by taigacute** [comment]
@hlissner  i use the `custom-face` to fix this.
