### ISSUE TITLE
Visual issues in doom-horizon

### ISSUE THREAD

**Issue by nikhil-prabhu** [hlissner/emacs-doom-themes#425]
Hey. I'd like to thank you guys for these amazing set of themes. I love all of them, and find myself switching between them quite often (and sometimes can't even decide which one to stick with, because they're all so good).

I was using doom-vibrant until today. Today, I'd switched to doom-horizon. However, I'm facing 2 issues with the theme. The first one is with the doom-modeline when doom's visual bell triggers. While the entire modeline flashes in red, some elements on the modeline still have the original background, which looks weird.

![doom-horizon-modeline](https://user-images.githubusercontent.com/39860598/77219220-a142ea80-6b59-11ea-8063-9cbad573ad3b.png)

Secondly, I'm using the solaire-mode package, and I've set `solaire-mode-remap-fringe` to `nil`. While this worked properly with doom-one and doom-vibrant, it doesn't work on doom-horizon (and with some of the other themes too, like doom-challenger-deep, etc).

![doom-horizon-fringe](https://user-images.githubusercontent.com/39860598/77219260-03035480-6b5a-11ea-88e9-a4097d127278.png)

Finally, while this isn't an issue, I've also noticed that doom-horizon doesn't highlight the buffer's major mode (with a bolder font and different color) in the modeline. I love the doom-horizon theme, and I'd definitely switch to it permanently if there was a fix for these issues.

**Comment by ema2159** [comment]
The fringe and the mode-line major mode colors were fixed. Regarding the visual bell issue, I think that's an issue with the way those items are being propertized, which I think it's not fixable here. Maybe @hlissner or @seagle0128  can give you an answer to that.

**Comment by seagle0128** [comment]
@ema2159 After quick checking the codes, I think the root cause is the background of `doom-modeline-info` was overriden.

``elisp
(doom-modeline-info :background base1 :foreground cyan)
```

BTW,  `solaire-mode-line-face` and `solaire-mode-line-inactive-face` are missing in some themes, like `molokai`, `monokai-classic`, `monokai-pro`,  `snazzy`, etc. That cause `visual-bell` functionality doesn't work.

**Comment by ema2159** [comment]
Thanks, @seagle0128! @nikhil-prabhu problems you addressed have been fixed. Please tell me if there's any problem with them and I'll be glad to help.

**Comment by seagle0128** [comment]
Thanks, @ema2159 . The issue of `doom-horizon` has been fixed. Will you fix the issue about `solaire-mode` in other themes I mentioned above?

**Comment by ema2159** [comment]
@seagle0128 of course! I will look it up soon

**Comment by nikhil-prabhu** [comment]
@seagle0128 @ema2159 Thank you so much for your response. I updated doom-themes now and tried out doom-horizon again. However, the fringe issue doesn't seem to be fixed. The visual bell is working fine now, though.

**Comment by ema2159** [comment]
@nikhil-prabhu what would be the expected outcome?

**Comment by nikhil-prabhu** [comment]
@ema2159 The fringe looks thick between buffers and the background color doesn't match (screenshot attached).
![emacs-fringe](https://user-images.githubusercontent.com/39860598/79220300-5f177b00-7e71-11ea-9c3c-e9c3122d0660.png)
And I apologize for the late reply. I didn't check Github for quite a while.

**Comment by ianpan870102** [comment]
@nikhil-prabhu Off topic question here: where did you get the doom-xcode theme? I couldn't find it anywhere

**Comment by ema2159** [comment]
@ianpan870102 there's a PR for it. It hasn't been merged though!

Btw, I missed this, I'll be looking into that fringe problem again soon.
