### ISSUE TITLE
Add Henna Theme

### ISSUE THREAD

**Issue by Marcos-H** [hlissner/emacs-doom-themes#426]
Hey, could you add Henna to this fine theme collection of yours?
https://github.com/httpsterio/vscode-henna
![henna](https://user-images.githubusercontent.com/39503566/77219868-9c117b80-6b18-11ea-8824-4b3fc5e969d0.png)

**Comment by ema2159** [comment]
Nice!. It may take some time though.

**Comment by ema2159** [comment]
It's really close to be merged so stay tuned.
