### ISSUE TITLE
cider support

### ISSUE THREAD

**Issue by andreyorst** [hlissner/emacs-doom-themes#428]
[cider](https://cider.mx/) defines a lot of faces that look out of place with `doom-one`:

![image](https://user-images.githubusercontent.com/19470159/77509826-7f5da680-6e7e-11ea-8013-558b89b8c89f.png)
![image](https://user-images.githubusercontent.com/19470159/77509852-8c7a9580-6e7e-11ea-86ad-cbf5a52114e0.png)

I'm working through those by finding matching face that will not break semantics, these I've changed so far:

```emacs-lisp
  (use-package cider
    :custom-face
    (cider-error-highlight-face ((t (:inherit flymake-error))))
    (cider-fringe-face ((t (:inherit flymake-warning))))
    (cider-fragile-button-face ((t (:box (:line-width 1 :color nil :style nil)
                                         :inherit (font-lock-warning-face)))))
    (cider-deprecated-face ((t (:inherit smerge-upper))))
    (cider-instrumented-face ((t (:box (:line-width -1 :color "#ff6c6b" :style nil))))))

**Comment by hlissner** [comment]
I added cider faces to our base template in 98bd753. I've derived their settings from their original faces, so they may still need additional tweaking. Let me know if you can think of ways to improve it. Thanks for bringing it to my attention!

**Comment by andreyorst** [comment]
> I've derived their settings from their original faces, so they may still need additional tweaking. Let me know if you can think of ways to improve it.

Thanks! I'll test this in a couple of days and report if something is wrong then

**Comment by andreyorst** [comment]
@hlissner button faces are not themed, but I've never ever seen a button in CIDER mode, so I don't think it's high priority to fix.

**Comment by hlissner** [comment]
> @hlissner button faces are not themed, but I've never ever seen a button in CIDER mode, so I don't think it's high priority to fix.

What face does cider use for buttons? And can you provide a screenshot? I don't use cider so I'm developing this blind.

That said, I'm sure I got [all cider's faces](https://grep.app/search?q=%28defface%20cider-&filter[repo][0]=clojure-emacs/cider). I commented out the ones that didn't need theming (because they inherited from other faces that were already themed, or didn't require any additional styling).

**Comment by andreyorst** [comment]
These faces seem to use box not found in default buttons of doom themes (buttons are usually flat)

![image](https://user-images.githubusercontent.com/19470159/120543722-511a1600-c3f5-11eb-840e-c37df05a2fb9.png)

**Comment by hlissner** [comment]
There doesn't seem to be a problem:

+ `cider-stacktrace-promoted-button-face` extends from `error` (which is themed).
+ `cider-stacktrace-suppressed-button-face` extends from `widget-inactive` (which inherits `shadow`, which is themed).
+ The `cider-stacktrace-*-button-face` and `cider-fragile-button-face` faces use the released-button and pressed-button styles for their `:box`es, which is fine for buttons in our themes.
+ `cider-fragile-button-face` inherits from `font-lock-warning-face`, which we also themed.

**Comment by andreyorst** [comment]
I see, thanks for explaining!

I also noticed that `cider-result-overlay-face` is a bit dark in `doom-one`, and makes text less contrast:

![image](https://user-images.githubusercontent.com/19470159/120684434-5768ca80-c4a7-11eb-98c3-59981032fc0b.png)

It seems to look fine on dark themes 

![image](https://user-images.githubusercontent.com/19470159/120684490-694a6d80-c4a7-11eb-8513-fd11764e895c.png)

Additionally, it seems that fon't lock leaks into the box border (seen on the screenshots above)

Setting this face `:color` attribute to a concrete color, like `"#5B6268"` (doom-one's base5 foreground) actually fixes that:

![image](https://user-images.githubusercontent.com/19470159/120685350-68fea200-c4a8-11eb-9c0a-ae7eb95de2e8.png)
