### ISSUE TITLE
Incomplete local themes

### ISSUE THREAD

**Issue by timokratia** [hlissner/emacs-doom-themes#436]
The doom themes in my folder `~/.emacs.d/.local/straight/repos/emacs-doom-themes/themes` are incomplete and seem not updated: only 36 theme files are in the folder, few themes are missing even after `doom update`, such as `doom-monokai-pro` and `doom-rouge`.

What should I do to get all the doom themes? Thanks for your suggestions in advance. Cheers!

**Comment by ema2159** [comment]
Try with `M-x straight-pull-all`

**Comment by yoavm448** [comment]
Doom pins all its packages to specific commits for stability. The pins for `doom-themes` were recently updated to make the new themes accessible, to update the pins in doom's source do `doom upgrade`, which would also pull `doom-themes` accordingly.

**Comment by timokratia** [comment]
Thanks for the hints and explanation, my local themes are up-to-date now. 

(Looks like it's time for me to read the docs beyond the get-started and FAQs. Anyway, more themes, yay!)
