### ISSUE TITLE
Theme 'doom-monokai-pro' not working

### ISSUE THREAD

**Issue by theaupoulat** [hlissner/emacs-doom-themes#437]
When setting up my theme to the monokai pro port (or even the monokai classic one) like this:
`(setq doom-theme 'doom-monokai-pro)`

after refreshing emacs, I get this error message  when I open emacs :
`Error in a Doom startup hook: doom-init-theme-h, (error "Unable to find theme file for 'doom-monokai-pro'`

(i get a random light theme instead)

**Comment by deuill** [comment]
Perhaps you haven't updated to the latest version of `doom`? AFAIK the version is pinned, and I'm using both themes fine on the latest version.

**Comment by theaupoulat** [comment]
It was indeed that ! Thanks 🙏
