### ISSUE TITLE
Horizon theme looks broken in terminals

### ISSUE THREAD

**Issue by rabbitinspace** [hlissner/emacs-doom-themes#438]
Hi!
I wanted to set `doom-horizon` as my main theme but found that it uses weird bg color in terminals:

![20200411_06h56m48s_grim](https://user-images.githubusercontent.com/31989081/79024049-25224c80-7bc5-11ea-8874-85a31433ea19.png)

I've tried to fix it by setting bg color to nil in the theme but looks like it's not the right way to do it since it also messes with other colors as well.

Some details: emacs 26.3, term kitty (same issue also in alacrity and iterm2).

**Comment by hlissner** [comment]
This is more likely `solaire-mode`'s fault. Add this to your `~/.doom.d/config.el` if you intend to use Doom Emacs with a daemon + terminal Emacs:

```elisp
(after! solaire-mode
  (solaire-global-mode -1))
```

**Comment by rabbitinspace** [comment]
I've tried disabling solarie mode as you said but `emacsclient` is closing (crashing?) right after start. When launching emacs in standalone mode I can only see this error:
```
condition-case: Error in a Doom startup hook: doom-init-theme-h, (wrong-type-argument stringp ("#fdf0ed" "brightwhite"))
```

Well, I suppose the theme is not intended to be used with terminal emacs? I'll go back to the standard one then. 

Thanks for your help! I'm going to close the issue.

**Comment by ema2159** [comment]
The thing is that there are many themes which do not have a proper terminal version. It's hard because not all themes can be implemented with the limited terminal colors.
