### ISSUE TITLE
One light version

### ISSUE THREAD

**Issue by ragloo** [hlissner/emacs-doom-themes#44]
Very nice themes !
Do you plan to support the one light version ?

Many thanks for those awesome themes :)

**Comment by hlissner** [comment]
Thank you! And yes, I do plan to make the one-light version (and others). I simply haven't gotten around to it yet. Feel free to subscribe to this issue and I'll close this issue once it's up!

**Comment by mckinley-olsen-oc** [comment]
@ragloo this should be available now with https://github.com/hlissner/emacs-doom-themes/pull/96

**Comment by ragloo** [comment]
Great, many thanks for the feedback :)

Le ven. 11 août 2017 à 19:49, McKinley Olsen <notifications@github.com> a
écrit :

**Comment by hlissner** [comment]
doom-one-light is now available, thanks to @ztlevi, so I'll close this.
