### ISSUE TITLE
contrast issues with tomorrow-day theme and solair mode

### ISSUE THREAD

**Issue by andreyorst** [hlissner/emacs-doom-themes#442]
Here's Treemacs on the left, and org buffer on the rigth:

![image](https://user-images.githubusercontent.com/19470159/79647317-deca8000-81b8-11ea-8aac-2d825966aa3d.png)

It's hard to see gray on gray, and light purple almost fades into the background.

**Comment by ema2159** [comment]
tell me if now it's ok
