### ISSUE TITLE
Theme helm-rg

### ISSUE THREAD

**Issue by wurosh** [hlissner/emacs-doom-themes#448]
`helm-ag` is now in the Emacs Orphanage. Helm-rg is an actively developed, solid alternative with a simpler API. I think it would be worth covering it as well.

**Comment by ema2159** [comment]
Hi! We can definitely include it, but I personally don't use Helm, so a PR is welcome!

**Comment by hlissner** [comment]
As of 4ebac17 this issue should be resolved. I've derived their settings based off their their original faces and they may still need more tweaking, but this should be a good first step. In any case, thanks for bringing it to my attention!
