### ISSUE TITLE
all-the-icons-octicon shows the wrong icons on Windows

### ISSUE THREAD

**Issue by ShadyAlfred** [hlissner/emacs-doom-themes#450]
I installed all-the-icons, but wrong icons are still displayed all over Emacs Doom. I tried to run `M-x all-the-icons-insert-octicon` and the results are the same. Material icons doesn't seem to have the same issue, material icons are correctly shown. But the github icons show wrong and different icons.
https://i.ibb.co/y8f5FVP/image.png

**Comment by hlissner** [comment]
Did you run `M-x all-the-icons-install-fonts` or accept when it asked you to install fonts during `doom install`? If so, there is an extra step for Windows users: double click the downloaded font files to install them.

**Comment by ShadyAlfred** [comment]
I did do that after the download.

**Comment by ShadyAlfred** [comment]
It's weird, because the material icons work correctly.

**Comment by ShadyAlfred** [comment]
I think this is related domtronn/all-the-icons.el#106, but I'm not sure. Disabling `font-lock` didn't make much difference.

**Comment by ShadyAlfred** [comment]
I have found the solution. domtronn/all-the-icons.el/issues/174, [last reply](https://github.com/domtronn/all-the-icons.el/issues/174#issuecomment-568233958). Please, add it to the Read Me file for whoever faces this problem.
