### ISSUE TITLE
How to get rid of the highlight in org-mode #begin_src or #begin_example start and ending lines

### ISSUE THREAD

**Issue by alienman5k** [hlissner/emacs-doom-themes#453]
I love emacs-doom-themes, but there is one little thing that has been bothering me so much. And that is in org-mode I love to have plenty of src code blocks, I don't like the highlight of the opening and ending line. 

The problem for me is that when the source or example block are collapsed it shows a highlight in the parent header, which to me does not look good as seems like unnecessary noise. 

Is there any way to change that setting? 

Example below:
[![Screen-Shot-2020-05-04-at-3-31-34-PM.png](https://i.postimg.cc/cCBr1832/Screen-Shot-2020-05-04-at-3-31-34-PM.png)](https://postimg.cc/YLjpb0bz)

**Comment by hlissner** [comment]
You can customize faces with `custom-set-faces` (or the [custom-set-faces!](https://github.com/hlissner/doom-emacs/blob/develop/docs/api.org#custom-set-faces) macro, for users of Doom Emacs). The faces you want to modify are `org-block-begin-line` and `org-block-end-line`:

```elisp
(custom-set-faces
  '(org-block-begin-line ((t (:background nil))))
  '(org-block-end-line   ((t (:background nil)))))
```
