### ISSUE TITLE
Can slant option be added for all themes

### ISSUE THREAD

**Issue by wisemonkey** [hlissner/emacs-doom-themes#459]
some themes implement
:slant 'italic
while others don't.
Can this be added to all themes or is it just a preference?

**Comment by ema2159** [comment]
It usually depends on the theme. For example, themes like fairy floss have their keywords on italics, so in our implementation, we set those keywords to italic. However, if you would like the same feature on another theme that doesn't have its keywords like that, you'd have to put `(set-face-attribute 'font-lock-keyword-face nil :slant 'italic)` in your config for example.

**Comment by ema2159** [comment]
@wisemonkey hey! Have you figured it out yet?

**Comment by wisemonkey** [comment]
I added following code to theme (doom-ephemeral): (Not very good solution cause breaks packages)

`   (font-lock-comment-face :inherit 'italic :foreground comments :background (if doom-ephemeral-comment-bg (doom-lighten bg 0.05)))
   (font-lock-doc-face :inherit 'font-lock-comment-face :foreground doc-comments)
   (font-lock-builtin-face :inherit 'italic :foreground builtin)
;;   (font-lock-keyword-face :inherit 'bold :foreground keywords)
   (font-lock-keyword-face :inherit 'italic :foreground keywords)

   (font-lock-preprocessor-face :foreground magenta :slant 'italic)
`

I'm yet to find way to do it without changing theme.

**Comment by ema2159** [comment]
Which packages does it break?

**Comment by wisemonkey** [comment]
Sorry that's just my assumption:
What would happen after package upgrades? I'm assuming it would bring in code without those lines.

**Comment by ema2159** [comment]
Oh now I get it, you added it inside the theme. No! You have to add it in your config. Show me your config! (The part where you set the theme)

**Comment by wisemonkey** [comment]
I don't load theme with ~/.emacs 
I just use M-x load-theme, and try to use different themes.

~/.emacs mostly have all elpa package loading,

**Comment by ema2159** [comment]
Ok, then you should create an advice which configures your themes each time you load it! I'll try to give you an example later.

**Comment by ema2159** [comment]
``` elisp
(advice-add #'load-theme :after (set-face-italic 'font-lock-keyword-face t))
```
That snippet should do what you want. You can add several advices for all the font-lock faces you want.

**Comment by ema2159** [comment]
I'll close this for now! Feel free to reopen if you need further assistance.
