### ISSUE TITLE
Incorrect doom flavor in mutiterm

### ISSUE THREAD

**Issue by EndlessDex** [hlissner/emacs-doom-themes#46]
I use doom-molokai and it works for most buffers, but when I open multiterm, doom-one is used instead.

**Comment by hlissner** [comment]
Ah, doom-molokai has been neglected (since I use doom-one). I'll revisit it some time next week and investigate this issue.

In the meantime, could you post a screenshot of the problem? The problem isn't clear from your description.

**Comment by EndlessDex** [comment]
![screenshot from 2017-04-11 21-38-56](https://cloud.githubusercontent.com/assets/17400677/24938862/6d8c15da-1eff-11e7-93ee-e276fb646a68.png)

The left frame is multiterm and the right is a .c buffer. The themes for the two buffer types are different. 

When I originally cloned doom, the theme was universal across all buffer. However, I recently pulled for the first time in several months and the theme was no longer universal.

**Comment by hlissner** [comment]
I'm assuming you reopened because the problem has returned? I'm afraid I don't see the issue. They look like they share the same theme. Do you mean that the colors are different?
