### ISSUE TITLE
Unreadable text in *eww* input boxes with doom light themes

### ISSUE THREAD

**Issue by nikhil-prabhu** [hlissner/emacs-doom-themes#460]
Hi. I'd recently noticed an issue with using `eww` when one of the light doom theme variants are loaded (checked with `doom-one-light`, `doom-acario-light`, `doom-solarized-light` and `doom-tomorrow-day`). When an input box in a webpage is focused, it becomes almost invisible. And the text typed into it is unreadable. For example, typing text into the search box on Wikipedia:

#### doom-acario-light
![Screenshot from 2020-05-11 12-30-23](https://user-images.githubusercontent.com/39860598/81533341-a5ce9700-9383-11ea-8849-14e27da0823e.png)

#### doom-one-light
![Screenshot from 2020-05-11 12-30-42](https://user-images.githubusercontent.com/39860598/81533451-db738000-9383-11ea-8f03-5a5465068917.png)

It doesn't seem to affect Emacs' inbuilt input boxes, however (like the ones in the customization buffer)

**Comment by hlissner** [comment]
Sorry for the late response. Thanks to physmacs on our Discord I was able to fix this in b14e53f. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
