### ISSUE TITLE
[Solarized Dark] Inconsistencies with the original solarized

### ISSUE THREAD

**Issue by ianpan870102** [hlissner/emacs-doom-themes#463]
Hi @ema2159 how've you been? Hope you are well.

I was looking at the original solarized theme the other day and found some inconsistencies between that and doom-solarized-dark. I believe you'd be interested to know.

I wasn't sure if some of them were intentional (to boost readability or variety of colours), but I assumed the goal was to have it as identical as the original as possible.

Anyhow, I have collected as many as I could (so far) and will list them here in terms of "face categories". Here are some of the categories and their "should-be" colours according to the original theme. I hope it helps if you decide to change them, I'm also glad to submit a PR if you agree.

```emacs-lisp
; category      ; should be    ; current colour
;-----------------------------------------------
(constants        cyan)        ; magenta
(variables        fg)          ; violet
(numbers          cyan)        ; magenta
(vc-modified      cyan)        ; orange
```

The last one is not necessarily an inconsistency, but I found vc-modified (currently orange) to be way too similar to vc-deleted (red), especially in solarized's colour palette. I suggested cyan above, but of course it can be blue or yellow, which are another two colours widely used in Visual Studio Code and Sublime Text to indicate change.

Let me know what you think!

-Ian

**Comment by ema2159** [comment]
Hey @ianpan870102! Hope you're doing well too. I'll do the changes you advise since that's the right thing to do in order to make the theme as close as possible to the original. Thanks for the feedback! Curiously, yesterday I was working a little bit in Solarized. Do you want to submit the PR or do you want me to do the changes?

**Comment by ianpan870102** [comment]
Hi @ema2159 I'm doing well!
I haven't forked for a PR yet -- since you've already been working on solarized, sure go ahead and make the changes! Greatly appreciated :-)

**Comment by ema2159** [comment]
Perfect! I will do that as soon as I can.

**Comment by ema2159** [comment]
Ian, just one question. Where are you looking for the colors? I'm asking because in VS Code's implementation constants are orange and numbers are magenta.

**Comment by ianpan870102** [comment]
> because in VS Code's implementation constants are orange and numbers are magenta.

I noticed that too, also VSCode solarized's foreground is a lot brighter than the original specs -- that's why I didn't regard VSCode as the standard for this theme.

I actually referred to the various screenshot of programming languages on [solarized's official github page](https://github.com/altercation/solarized) and cross-compared the languages that I know: C/C++, Java, JavaScript, Python etc. The **constants, variable-names, and numbers** are consistently using **cyan, fg, and cyan** respectively.

One phenomenon that I noticed was the reserved usage of magenta -- perhaps the author simply found it too "popping" (Helmholtz–Kohlrausch effect I guess) and used it only on very special occasions (like TODO keywords).

**Comment by ema2159** [comment]
You're right. It seems that everybody freestyles their own version of Solarized! I think your changes are appropriate but, what if we leave the constants magenta just for the sake of using the color just a little bit?

**Comment by ianpan870102** [comment]
@ema2159 For sure! That makes sense. After all, if someone "really" wants to stick to the original solarized dark theme as much as possible for whatever reason, a simple `:custom-face` tweak can solve it.

Here's an example for other people who might come across this thread:

```emacs-lisp
(use-package doom-themes
  :custom-face
  (font-lock-constant-face      ((t (:foreground "#2aa198")))) ; cyan
  (highlight-numbers-number     ((t (:foreground "#2aa198")))) ; cyan
  (diff-hl-change               ((t (:background "#2aa198" :foreground "#2aa198")))) ; cyan
  (show-paren-match             ((t (:foreground "white"))))
  :config
  (load-theme 'doom-solarized-dark t))
```

**Comment by ema2159** [comment]
Also, people can do `(setq doom-solarized-dark-brighter-text t)` to make the fg color brighter as often seen in other implementations!
