### ISSUE TITLE
[doom-theme-base.el] Adding a new face: highlight-symbol-face

### ISSUE THREAD

**Issue by ianpan870102** [hlissner/emacs-doom-themes#464]
[Highlight symbol](https://github.com/nschum/highlight-symbol.el) is a semi-popular package that I personally swear by. It allows the highlighting of all occurrences of current symbol at point, which is a widely supported feature in most modern editors. Currently, doom-themes have no support for this face, so it fall backs to highlight-symbol-face's default, a gray background.
Preferably, dark doom-themes can have a slightly lighter background (using doom-lighten?) for this face and light doom-themes can have a slightly darker background (using doom-darken?) for this face.

Here's one example usage (manually tweaked):

```emacs-lisp
(highlight-symbol-face        ((t (:background "#174652"))))
```

And here's the result -- notice how `add-hook` is automatically highlighted with a slightly lighter background **that is still consistent with the solarized-dark theme**.

![image](https://user-images.githubusercontent.com/36686900/81817431-49c06a00-955f-11ea-9ada-04b88da6b7d2.png)

**Comment by ema2159** [comment]
You're right. The funny thing is I've been using the package for quite some time now, inheriting the highlight face. I think the right thing would be to either use the highlight or the region faces. Which one do you think it's best?

**Comment by ema2159** [comment]
I'm lying, I use the `highlight-thing` package which provides slightly more functionality, but it's the same idea.

**Comment by ianpan870102** [comment]
> I'm lying, I use the highlight-thing package which provides slightly more functionality, but it's the same idea.

Haha, I tried both highlight-thing and highlight-symbol, and somehow ended up with the latter. But yeah they provide pretty much the same functionality.

> I think the right thing would be to either use the highlight or the region faces. Which one do you think it's best?

For some of the doom themes that I've used, I believe `region` is the more appropriate face to use. **However**, I'm worrying that some future ports of doom themes will have some high contrast region face -- which might make highlight-thing/highlight-symbol go 'crazy' with the highlights at point. That's why I think it's best to use `doom-lighten` (for dark themes) and `doom-darken` (for light themes).

What do you think of this approach?

**Comment by ema2159** [comment]
I was thinking the same. For example, in Solarized, using region would be barely noticeable, however, since `doom-themes-base` doesn't distinguish between light and dark themes, and since there are more dark than light themes, I think it would be best to default to `doom-lighten` and then adjust in the light themes when necessary.

**Comment by hlissner** [comment]
>  however, since doom-themes-base doesn't distinguish between light and dark themes

It can if you use [this syntax](https://github.com/hlissner/emacs-doom-themes/blob/master/doom-themes-base.el#L299-L301).

**Comment by ema2159** [comment]
Done!

**Comment by ianpan870102** [comment]
@ema2159 @hlissner Brilliant! cheers
