### ISSUE TITLE
doom-sourcerer, visual mode is the same as org source code block

### ISSUE THREAD

**Issue by AxelBohm** [hlissner/emacs-doom-themes#468]
In the doom-sourcerer theme. The background color of the current line when in visual mode (evil) is the same as the background color of org mode source code blocks which makes visual selection in these source code blocks invisible.
In normal mode:
![2020-05-18-171308_947x341_scrot](https://user-images.githubusercontent.com/28197445/82229647-08e39f00-992b-11ea-821f-26da91064ecd.png)
And here visual line mode:
![2020-05-18-171319_947x341_scrot](https://user-images.githubusercontent.com/28197445/82229658-0a14cc00-992b-11ea-93bb-53fbe42472c7.png)

**Comment by ema2159** [comment]
Screenshot please!

**Comment by ema2159** [comment]
Wait. I think we've faced a similar issue with another theme. I'll give it a check.
