### ISSUE TITLE
How to Use Additional Themes?

### ISSUE THREAD

**Issue by kingbari** [hlissner/emacs-doom-themes#469]
I added the below configuration to my `init.el` file, but it causes the error, 
`Error (use-package): doom-themes/:config: Unable to find theme file for ‘doom-palenight’`

If I change `'doom-palenight` to `'doom-one` the theme loads, therefore the issue _appears_ to be with the installation/usage of _additional_ themes. How am I supposed to install/use additional themes? Thanks!

```
(use-package doom-themes
  :config
  (doom-themes-org-config)
  (load-theme 'doom-palenight t)
  :init
  (setq doom-themes-enable-bold t
        doom-themes-enable-italic t))
```

**Comment by hlissner** [comment]
Replace that config with `(setq doom-theme 'doom-palenight)`, and make sure the `:ui doom` module is enabled.

Since you did not include your `M-x doom/info`, as the issue template instructed, I cannot determine anything about your setup. Please include it, if the issue persists.

**Comment by ema2159** [comment]
Are you using MELPA Stable?

**Comment by kingbari** [comment]
> Are you using MELPA Stable?

Yes, I'm using MELPA Stable.

> EDIT: Ah, thought this was in a different repo, my bad.
> 
> Try this instead:
> 
> ```emacs-lisp
> (require 'doom-themes)
> (load-theme 'doom-palenight t)
> ```
> 
> Also: how are you installing the package?

To clarify, on another machine I installed "full" doom using these [instructions](https://github.com/hlissner/doom-emacs#install). However, in this case I only installed `emacs-doom-themes` using `(use-package doom-themes ...)`. From your reply, I gather that I have to separately install the additional themes. I _assumed_ that the ([checked](https://github.com/hlissner/emacs-doom-themes#theme-list)) additional theme packages were bundled in `doom-themes` package.

**Comment by ema2159** [comment]
Well, that's the cause. Our the Melpa Stable version hasn't been updated in a while! You should go for the "regular" Melpa version which is constantly updated and improved, that also implying that it has all the themes.

**Comment by kingbari** [comment]
> Well, that's the cause. Our the Melpa Stable version hasn't been updated in a while! You should go for the "regular" Melpa version which is constantly updated and improved, that also implying that it has all the themes.

 That in fact was the cause 🤦‍♂️ Switching from `Melpa Stable` to _just_ `Melpa` resolved the "issue." Thanks for the help!

**Comment by ema2159** [comment]
Awesome! I'm glad to help.
