### ISSUE TITLE
[doom-gruvbox] Add contrast options?

### ISSUE THREAD

**Issue by ianpan870102** [hlissner/emacs-doom-themes#470]
The original gruvbox has 3 contrast for both dark and light versions: hard, medium, and soft. This makes `3 * 2 = 6` variations in total.
AFAIK, it is simply the change in the background colour -- all other colours are not touched.
Here are the colours I've extracted, if anyone is interested in adding the option. IMHO, there's no need to "create a new theme", we just have to have a variable that controls the contrast. (Something similar to `(setq doom-solarized-dark-brighter-text t)`)
```none
* Just the background colours:
---------------------------------
dark-hard:              #1d2021
dark-medium (default):  #282828
dark-soft:              #32302f
light-hard:             #f9f5d7
light-medium (default): #fbf1c7
light-soft:             #f2e5bc
```
Here are the colour references: https://github.com/morhetz/gruvbox

**Comment by ianpan870102** [comment]
I've experimented a bit with 2-way boolean values:
```emacs-lisp
(defcustom doom-gruvbox-contrast-dark-hard nil
  "If non-nil, background will be darker, turning the theme into gruvbox-dark-hard."
  :group 'doom-gruvbox-theme
  :type 'boolean)
```
Let me know what's the best practice to use multiple choices like `'hard` `'soft` `'medium` and I'll create a PR.

**Comment by ema2159** [comment]
That feature is already implemented for Gruvbox light! As @jsoa told me, with the dark version it's slightly more difficult but not that much. If you could create a PR it would be great! I've been kinda busy with work recently.

**Comment by ianpan870102** [comment]
@ema2159 Cool! ### I'll check out the implementation for gruvbox-light and send a PR for gruvbox dark soon :-)
P.x. Good luck with your work!

**Comment by ianpan870102** [comment]
Done! PR here: https://github.com/hlissner/emacs-doom-themes/pull/475
Now the users can set
```emacs-lisp
(setq doom-gruvbox-dark-variant "hard")
;; or
(setq doom-gruvbox-dark-variant "soft")
```

**Comment by ianpan870102** [comment]
P.s. For before/after screenshots, please kindly check out the PR conversation here: https://github.com/hlissner/emacs-doom-themes/pull/475

**Comment by obar** [comment]
I think it's safe to close this issue as well as #458 now :+1:  Thanks Ian!

**Comment by ianpan870102** [comment]
You're right, closing issue now!
