### ISSUE TITLE
header-line should not inherit mode-line

### ISSUE THREAD

**Issue by kiennq** [hlissner/emacs-doom-themes#473]
If we ever customize `mode-line` via `face-remapping-alist`, the `head-line` will be affected too.
I don't see the reason why we make one depends on other, this will limited the ability to customize face.

Also, `mini-modeline` is also affected from this https://github.com/kiennq/emacs-mini-modeline/issues/31

Is it good if I can provide a PR to separate `head-line` and `mode-line` face?

**Comment by ema2159** [comment]
Yes! Thanks a lot man. Sorry for the late reply, I've had a couple of busy days.
