### ISSUE TITLE
[Magit] hl-line sometimes doesn't work

### ISSUE THREAD

**Issue by ianpan870102** [hlissner/emacs-doom-themes#482]
So this issue is kind of hard to explain, but I'll try my best. 
I have tried to investigate further, but I thought I'd check with other doom-theme users here first and see if I'm the only facing this problem (in which case it's probably some other part of my config that's messing up).

## Issue:
In a magit buffer, sometimes the `hl-line` will **not** show. I have experimented with a lot of different themes, and this **only** happens with doom-themes. 

## Steps to reproduce:
1. Have your theme set to a doom-theme
2. **Disable** global-hl-line-mode, and **any other** hl-line mode hooks you have hooked to (e.g. prog-mode, dired-mode etc.).
3.  **Restart** Emacs.
4. Visit a magit buffer. _Step 2 is needed because we don't want hl-line-mode to be invoked "in any of the buffers before we arrive at our first magit buffer"_
5. `hl-line` doesn't show up.

## Expectations
Magit is supposed to show `hl-line` no matter what. Unless one explicitly disables hl-line in a magit buffer, which I didn't.

## Other phenomena
If I invoke `hl-line` anywhere in any buffer before entering the first magit instance, magit will show `hl-line` as expected, even if those buffers seemingly have nothing to do with magit.

**Comment by hlissner** [comment]
Sorry for the late response. https://github.com/hlissner/emacs-solaire-mode/commit/b6cc22e2178f405b444cb7e89d8d5705e67f1905 _may_ have fixed this, if you're using solaire-mode. Let me know if that isn't the case and I'll reopen this.

**Comment by ianpan870102** [comment]
Hi @hlissner thanks for getting back. Actually I wasn't using solaire-mode, so I'm afraid the issue is caused by something else..
