### ISSUE TITLE
[doom-horizon] Bug: brighter comment not working (PR on the way!)

### ISSUE THREAD

**Issue by ianpan870102** [hlissner/emacs-doom-themes#486]
In doom-horizon, setting `doom-horizon-brighter-comments` has no effect on the foreground, and the background is a bit too bright for the comments to be readable. Here's my proposal with **before-and-after** screenshots

## Before (notice that comments are hard to read

![image](https://user-images.githubusercontent.com/36686900/84599408-6de7d180-aea4-11ea-8fe3-028c8c549c15.png)

## After (adhere more to the brighter-comments idea)

![image](https://user-images.githubusercontent.com/36686900/84599398-5e688880-aea4-11ea-9034-0bd28736c1a1.png)

**Comment by ema2159** [comment]
I love that you always bring almost always a PR when you open an issue haha! Awesome!
