### ISSUE TITLE
hl-line mode in doom-one has the same color as bg

### ISSUE THREAD

**Issue by andreyorst** [hlissner/emacs-doom-themes#488]
With doom-gruvbox:
<details>
<summary>1</summary>

![image](https://user-images.githubusercontent.com/19470159/84601491-299b0800-ae89-11ea-89de-b7d7c96ee017.png)
</details>
<details>
<summary>2</summary>

![image](https://user-images.githubusercontent.com/19470159/84601497-30297f80-ae89-11ea-82be-45127a8ed43d.png)
</details>
Doom-one:

<details>
<summary>1</summary>

![image](https://user-images.githubusercontent.com/19470159/84601507-459ea980-ae89-11ea-8319-0837ae219ca1.png)
</details>

<details>
<summary>2</summary>

![image](https://user-images.githubusercontent.com/19470159/84601511-4f281180-ae89-11ea-9627-4dd7dae71165.png)
</details>

**Comment by ema2159** [comment]
That's odd.
![image](https://user-images.githubusercontent.com/17773218/84607392-3ceaab00-ae6a-11ea-9619-f754fc25b4df.png)

Are you using something that might be affecting hl-line?

**Comment by andreyorst** [comment]
Hm, I've updated all my packages recently, and it broke. I've thought about
solaire, but without it the problem persists as well. Maybe I should do
clean install

пн, 15 июн. 2020 г., 03:11 Emmanuel Bustos Torres <notifications@github.com

**Comment by ianpan870102** [comment]
@andreyorst Just a wild guess here: but are you **layering** multiple themes **on top of** each other? Before loading doom-one, you gotta make sure to **disable** all other themes too, as Emacs won't do it automatically.

**Comment by andreyorst** [comment]
> @andreyorst Just a wild guess here: but are you **layering** multiple themes **on top of** each other? Before loading doom-one, you gotta make sure to **disable** all other themes too, as Emacs won't do it automatically.

No. The config from screenshots in issue description is the only thing where I interact with themes. Calling `disable-theme` shows only two candidates: `solaire-swap-bg-theme` and `doom-one`. Disabling `solaire-swap-bg-theme` fixes the issue, but background is swapped.

Also, acutally properly removed solaire from my config, and the hl-line color is correct. So perhaps this is a solaire issue?

**Comment by ianpan870102** [comment]
Hmm it does appear to be solaire's issue, judging for your description. I'm not a solaire user so I'm afraid I can't help much in that regard.
Perhaps you could consider opening an issue over there and see whether other users are experiencing the same problem
