### ISSUE TITLE
Solarized light misses extend attribute on some faces

### ISSUE THREAD

**Issue by andreyorst** [hlissner/emacs-doom-themes#498]
Actual:
![image](https://user-images.githubusercontent.com/19470159/88710576-8859cf80-d11f-11ea-9295-21398eb7f759.png)
Expected:
![image](https://user-images.githubusercontent.com/19470159/88710733-bb9c5e80-d11f-11ea-938f-bc5cbfd33b63.png)

```emacs-lisp
(set-face-attribute 'org-block nil :extend t)
(set-face-attribute 'org-block-begin-line nil :extend t)
(set-face-attribute 'org-block-end-line nil :extend t)
```

Maybe there are more faces that were not updated since https://github.com/hlissner/emacs-doom-themes/issues/342

**Comment by andreyorst** [comment]
Also happens with Gruvbox light

**Comment by ema2159** [comment]
Fixed! tell me if it is alright.
