### ISSUE TITLE
Treemacs icon display error

### ISSUE THREAD

**Issue by cxb811201** [hlissner/emacs-doom-themes#500]
**Additional details:**
![image](https://user-images.githubusercontent.com/2104470/88889286-73418580-d272-11ea-8425-ad1db08e4e6a.png)

**System information:**
<details><pre>
((emacs
  (version . "28.0.50")
  (features . "XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER LCMS2")
  (build . "Jul 30, 2020")
  (buildopts "--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --mandir=/usr/share/man --with-gameuser=:games --with-sound=alsa --with-modules --without-gconf --without-gsettings --with-x-toolkit=gtk3 --without-xaw3d --with-xwidgets --without-compress-install 'CFLAGS=-march=ivybridge -O2 -pipe -fno-plt -flto' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop, origin/develop, origin/HEAD 96ab60d40 2020-07-29 16:10:31 -0400")
  (dir . "~/.doom.d/"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/usr/bin/zsh")
  (uname . "Linux 5.7.11 hlissner/doom-emacs#1 SMP PREEMPT Thu Jul 30 11:13:38 CST 2020 x86_64")
  (path "~/.gem/ruby/2.6.0/bin" "~/.go/bin" "~/.cargo/bin" "~/.jenv/shims" "~/.jenv/bin" "~/.local/share/coursier/bin" "~/.emacs.d/bin" "~/.local/bin" "~/.nvm/versions/node/v13.12.0/bin" "/usr/local/bin" "/usr/local/sbin" "/usr/bin" "/usr/lib/jvm/default/bin" "/usr/bin/site_perl" "/usr/bin/vendor_perl" "/usr/bin/core_perl" "~/.antigen/bundles/robbyrussell/oh-my-zsh/lib" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/git" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/gitfast" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/colored-man-pages" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/history" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/z" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/extract" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/encode64" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/web-search" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/urltools" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/tmux" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/docker" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/docker-compose" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/archlinux" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/cargo" "~/.antigen/bundles/djui/alias-tips" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/mvn" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/sbt" "~/.antigen/bundles/zdharma/fast-syntax-highlighting" "~/.antigen/bundles/zsh-users/zsh-autosuggestions" "~/.antigen/bundles/hlissner/zsh-autopair" "~/.antigen/bundles/romkatv/powerlevel10k" "/usr/lib/emacs/28.0.50/x86_64-pc-linux-gnu"))
 (config
  (envfile)
  (elc-files . 0)
  (modules :completion (company +childframe) (ivy +prescient +fuzzy +childframe) :ui doom doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) treemacs vc-gutter (window-select +numbers) workspaces zen :editor file-templates fold format lispy multiple-cursors snippets word-wrap :emacs dired electric (ibuffer +icons) undo vc :term vterm :checkers (syntax +childframe) (spell +aspell) :tools (debugger +lsp) docker editorconfig (eval +overlay) lookup (lsp +peek) magit make pdf :lang data emacs-lisp (go +lsp) json (java +lsp) (javascript +lsp) (markdown +grip) (org +dragndrop +hugo +pandoc +present +pomodoro +journal) plantuml rest (scala +lsp) sh (web +lsp) yaml :config (default +bindings +smartparens) :my (chinese +childframe) ui editor calendar dired magit (translate +childframe) tools lsp markdown plantuml protobuf go (java +google-java-format) scala sql keybindings)
  (packages "n/a")
  (unpin
   (:tools lsp)
   (:lang java)
   dap-mode)
  (elpa "n/a")))
</pre></details>

**Comment by hlissner** [comment]
I cannot reproduce this in vanilla Doom.

![image](https://user-images.githubusercontent.com/510883/88889969-e9140580-d20e-11ea-9f1e-5dabd5346cda.png)

Is there anything more you can tell me about your config? Perhaps a link to it?

**Comment by clement-buchart** [comment]
Hello, 
I think I have the same issue, with 
`(setq doom-themes-treemacs-theme 'doom-colors)`
in my config.

**Comment by ema2159** [comment]
I think recently some icons were modified in all-the-icons.el. I noticed the same with the License icon. I'm going to check.

**Comment by ema2159** [comment]
@clement-buchart, can you please tell me the details of your system? I'm suspecting this may be an issue with an update in the fonts. I've checked all-the-icons.el repo and there doesn't seem to be any change that may be causing this. Moreover, I've seen this problem in a Linux Mint machine, but not in a Windows machine.

**Comment by clement-buchart** [comment]
Hello, 
I'm using doom emacs, here is the output of `doom info` 
```
❯ doom info
((system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/bin/zsh")
  (uname . "Linux 5.8.5-arch1-1 #1 SMP PREEMPT Thu, 27 Aug 2020 18:53:02 +0000 x86_64")
  (path "~/.doom.emacs.d/bin" "~/.gem/ruby/2.7.0/bin" "~/go/bin" "~/.node_modules/bin" "/opt/google-cloud-sdk/bin" "/usr/local/bin" "/usr/bin" "/bin" "/usr/local/sbin" "/opt/flutter/bin" "/usr/lib/jvm/default/bin" "/usr/bin/site_perl" "/usr/bin/vendor_perl" "/usr/bin/core_perl" "~/.antigen/bundles/robbyrussell/oh-my-zsh/lib" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/git" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/command-not-found" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/encode64" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/vi-mode" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/docker" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/httpie" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/thefuck" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/helm" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/terraform" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/ripgrep" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/golang" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/mvn" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/kubectl" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/gcloud" "~/.antigen/bundles/hlissner/zsh-autopair" "~/.antigen/bundles/mafredri/zsh-async" "~/.antigen/bundles/aperezdc/zsh-fzy" "~/.antigen/bundles/zsh-users/zsh-autosuggestions" "~/.antigen/bundles/zsh-users/zsh-syntax-highlighting" "~/.antigen/bundles/zsh-users/zsh-history-substring-search" "~/.antigen/bundles/zsh-users/zsh-completions" "~/.antigen/bundles/romkatv/powerlevel10k" "/usr/lib/emacs/27.1/x86_64-pc-linux-gnu"))
 (emacs
  (dir . "~/.doom.emacs.d/")
  (version . "27.1")
  (build . "Aug 28, 2020")
  (buildopts . "--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-wide-int --with-modules --with-cairo --with-harfbuzz 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now")
  (features . "XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP")
  (traits batch server-running))
 (doom
  (dir . "~/.doom.d/")
  (version . "2.0.9")
  (build . "HEAD -> develop 79c1fcefc 2020-08-31 23:19:31 -0400")
  (elc-files . 0)
  (modules :completion company ivy :ui deft doom doom-dashboard doom-quit hl-todo hydra indent-guides minimap modeline nav-flash ophints (popup +all +defaults) ligatures treemacs vc-gutter vi-tilde-fringe window-select workspaces zen :editor (evil +everywhere) file-templates fold (format +onsave) multiple-cursors parinfer rotate-text snippets word-wrap :emacs dired electric ibuffer undo vc :term vterm :checkers syntax spell grammar :tools ansible (debugger +lsp) direnv docker editorconfig (eval +overlay) (lookup +docsets) (lsp +peek +bindings) magit make (pass +auth) pdf prodigy rgb taskrunner terraform :lang (cc +lsp) data (dart +flutter) emacs-lisp (go +lsp) json (java +lsp) (javascript +lsp) markdown (org +dragndrop +hugo +roam +ipython +pandoc +pomodoro +present) plantuml rest ruby (rust +lsp) sh web yaml :email notmuch :app calendar (rss +org) twitter :config (default +bindings +smartparens))
  (packages (polymode) (import-js) (helm-gitignore) (adoc-mode) (vue-mode) (oauth2) (spotify :recipe (:host github :repo "danielfm/spotify.el")))
  (unpin "n/a")
  (elpa "n/a")))
```

Could it be related to lsp-mode ?
If I open treemacs right after I start emacs, I get this icon 
![image](https://user-images.githubusercontent.com/30914745/91853723-e750be00-ec62-11ea-89de-529698dc0597.png)
But if i open babel.config.js, and refresh the treemacs buffer, I get
![image](https://user-images.githubusercontent.com/30914745/91853774-fb94bb00-ec62-11ea-8154-497ce4e4e819.png)

Note that if i open a file that doesn't start lsp-mode (say, cypress.json) the icons stays the same.

Here are some file that are affected
- babel config
- eslint config
- .project folder (eclipse related)
- pom.xml

They get replaced by a more 'specific', language-related icon, which is bigger that the others.

Hope this helps narrowing it.

**Comment by ema2159** [comment]
@clement-buchart that's indeed the problem. It seems that they forcefully overwrite the icons. An issue should be open in LSP's repository.

**Comment by clement-buchart** [comment]
Could be related to https://github.com/Alexander-Miller/treemacs/issues/712 which has been fixed but isn't yet available in doom emacs.

**Comment by eeshugerman** [comment]
i opened an issue for this here: https://github.com/emacs-lsp/lsp-treemacs/issues/89
