### ISSUE TITLE
doom-gruvbox, doom-modeline, flycheck - similar colors for warnings and errors.

### ISSUE THREAD

**Issue by ocelaiwo** [hlissner/emacs-doom-themes#502]
I use doom-gruvbox with doom-modeline with the following configuration:
```
(setq doom-modeline-checker-simple-format nil)
```
which makes doom-modeline display flycheck errors, warnings and info separately. I noticed that the colors for errors and for warnings are very similar and the warning color, which is usually yellow, is off its meaning:
![image](https://user-images.githubusercontent.com/57271510/88981263-03b5af80-d2df-11ea-9b96-6242c3641c5a.png)
(errors/warnings/info)
In other doom themes there is no such issue, the warning count is yellow.

**Comment by ema2159** [comment]
I'll check it right away.

**Comment by ema2159** [comment]
Fixed.
