### ISSUE TITLE
[outrun-electric] Color mismatch on Emacs 26.3 (nox)

### ISSUE THREAD

**Issue by apiraino** [hlissner/emacs-doom-themes#503]
Hi,

I'm trying to figure out this problem. None of the themes I've tested (outrun-electric, laserwave, acario-dark) appear on my Emacs as I see on the screenshot.

Example: the background color for 256 colors terminals is `#0c0a20` but what I see is `#00005f` (which appears to be `color-17` when I look at `M-x list-colors-display`). All the colors are shifted in a way I don't understand and [don't match the screenshot](https://github.com/hlissner/emacs-doom-themes/blob/screenshots/doom-outrun-electric.png):

![2020-07-31_003858](https://user-images.githubusercontent.com/6098822/88981452-44ed9580-d2c6-11ea-8846-b2bcc5443dff.png)

Some more info:
- Gnome-Terminal with some color customizations (but I think this is not relevant)
- Using Sway/Wayland (but same issue appears also on i3/X11)
- Emacs 26.3 nox
- `echo $TERM` => `xterm-256color`
- I'm using just one theme ("use more theme" option is not checked)
- tried using other terminals (`st`, `kitty`, ...) and colors change in different ways

I believe it's an issue on my end but I can't make sense of all these info I've gathered.

Why some themes use the emacs color names instead of the RGB triplet? (example [acario-dark](https://github.com/hlissner/emacs-doom-themes/blob/180747a4cb848b6378b13bcaf908ea12c95bb4a6/themes/doom-acario-dark-theme.el#L37))

Any suggestion is greatly appreciated - thanks!!

Also, these themes are absolutely gorgeous.

**Comment by hlissner** [comment]
Are you using solaire-mode? If so, turn it off. It doesn't work in the terminal.

**Comment by apiraino** [comment]
I've checked, it's not installed

**Comment by ema2159** [comment]
Is that terminal Emacs? There are some themes that currently doesn't support term Emacs that good. This is the case for Outrun.

**Comment by apiraino** [comment]
@ema2159 you raise a very good point and this is why I explicitely mentioned that I am using `emacs-nox` (no X11), `M-x list-colors-display` lists 256 colors.
I tried installing `emacs-gtk` and `emacs-lucid` on another Ubuntu and the previous command returns ~550 colors (but the theme colors are still off from the screenshot).

So my question is: what are the requirements in order to attain the closest result as possible to the screenshot? Should I install your full Emacs configuration?

**Comment by apiraino** [comment]
After another test I can partially answer my question: installing @ema2159 [full Emacs configuraton](https://github.com/ema2159/emmacs_config) and running `emacs-gtk` I attain the desired behaviour.

If I run `emacs -nw` (no window) I have a palette of only 256 colors so I have a I get a toned-down experience (and that's fair) but still the background if still broken as I mentioned in this issue, see following screenshot:

![2020-08-01_181238](https://user-images.githubusercontent.com/6098822/89105596-9dd24080-d422-11ea-95fe-f976bc67dfc3.png)

**Comment by apiraino** [comment]
I've finally figured that out :tada: 

Emacs support 24bit colors since `26.x` but on Linux you must tell your shell to force this color depth when starting Emacs. This can be done by compiling your own `terminfo` file and use it when starting Emacs (see [GNU's faq](https://www.gnu.org/software/emacs/manual/html_node/efaq/Colors-on-a-TTY.html)).

Now I have more than 500 colors also on the terminal and I'm very close to the result of the screenshot. I assume other differences might be due to other factors (old screenshot, different terminal config, different OS, ...).

I'm closing this issue but if you think this piece of knowledge is useful I can drop two lines in the README explaining the procedure in a PR and save some time for the next terminal user.

**Comment by ema2159** [comment]
Glad to hear that! The README PR sounds great, it would be really useful.
