### ISSUE TITLE
Current line not highlighted in mu4e-headers

### ISSUE THREAD

**Issue by jgoerzen** [hlissner/emacs-doom-themes#504]
Hello,

In mu4e, when advancing through menus, there are two windows visible: mu4e-headers (listing the messages) and mu4e-view, which shows the body of messages.  While advancing through, normally mu4e-view will be focused.

When it is, the highlight for the current line in mu4e-headers disappears, making it difficult to see where you are in the message list.

I tracked this down to this behavior in `core/core-ui.el`:

```
  ;; Not having to render the hl-line overlay in multiple buffers offers a tiny
  ;; performance boost. I also don't need to see it in other buffers.
  (setq hl-line-sticky-flag nil
        global-hl-line-sticky-flag nil)
```

Indeed, I can work around the issue by putting this in my config.el:

```
(after! hl-line
    (setq hl-line-sticky-flag t
          global-hl-line-sticky-flag t)

  )
```

No doubt there is a more focused method to make this change just for mu4e-headers but I don't know what it is.

Thanks!

**Comment by jgoerzen** [comment]
This does seem to be an issue with every theme, so not sure if I should report it to the main doom-emacs project or not.

**Comment by ema2159** [comment]
Since it's a theming issue, it's ok to leave it here.

**Comment by hlissner** [comment]
This is Doom issue, which was fixed in https://github.com/hlissner/doom-emacs/commit/33e7f081a7579238dbb6ad6f2d6c3adf892613ea, so I'll consider this resolved.
