### ISSUE TITLE
doom-dark+ doesn't override shadow face

### ISSUE THREAD

**Issue by ericdallo** [hlissner/emacs-doom-themes#505]
It seems that `doom-dark+` theme doesn't define the emacs `shadow` face [here](https://github.com/hlissner/emacs-doom-themes/blob/master/themes/doom-dark%2B-theme.el#L56-L77) behavior like [this theme does](https://github.com/hlissner/emacs-doom-themes/blob/2c71a9fe4edcdcd8844e60c6cddc5faf954dfc72/themes/doom-ephemeral-theme.el#L131)

Example of the issue using [lsp-headerline-breadcrumb-mode](https://emacs-lsp.github.io/lsp-mode/page/main-features/#breadcrumb-on-headerline) which use that face on the arrows(>):
`doom-dracula`
![image](https://user-images.githubusercontent.com/7820865/89109723-39ab7e80-d41a-11ea-9229-c9dcf28c4b7b.png)

`doom-dark+`
![image](https://user-images.githubusercontent.com/7820865/89109713-24365480-d41a-11ea-850a-7b097eb6c3f5.png)

**Comment by Shourai** [comment]
The same behaviour is also present in the `doom-one` theme, but not in the `doom-vibrant` one.
Though I can't find the `shadow` face in the vibrant version, I assume it is loaded from somewhere else.

As a workaround, I have set the following:

```
(lsp-headerline-breadcrumb-separator-face ((t (:foreground "gray"))))
```
Set the color to your desired color of course.

This can be added to use package as follows:

```
    (use-package lsp-mode
      :ensure t
      :custom-face
      (lsp-headerline-breadcrumb-separator-face ((t (:foreground "gray")))))

```

**Comment by ema2159** [comment]
Question. Wasn't this fixed in 081a375972da90a9203f13bd46a90b06b2dbafa5?

**Comment by ericdallo** [comment]
Good question I didn't have the time to test that theme, have you @Shourai ?

**Comment by ema2159** [comment]
The issue wasn't with the shadow face but with the lsp-headerline-separator face which didn't have any sensible defaults in doom-themes. It should look like this now:
![image](https://user-images.githubusercontent.com/17773218/104369497-31598280-5526-11eb-9db4-d83bf30796de.png)

With doom-one however, it's different. I've never known if it is a bug or a feature, but when the foreground-color of an element is "close" to its background-color, Emacs simply puts both as the background's color, even though when doing  `M-x describe-face` the correct properties are shown. Not even setting the `distant-foreground` property helps, so I'll have to manually patch it. If you know of any other theme where this happens let me know so I can fix it!

**Comment by Shourai** [comment]
Thanks for the information @ema2159!
I can confirm it it working fine now with doom-one theme.
It also works fine with doom-dark+ @ericdallo, I didn't use that theme that's why I haven't checked before.
