### ISSUE TITLE
doom-one is hard to view in ediff (emacs -nw version)

### ISSUE THREAD

**Issue by giaptx** [hlissner/emacs-doom-themes#506]
I'm using doom-one themes in `emacs -nw`

My config with use-package

```
(use-package doom-themes
  :ensure t
  :init (load-theme 'doom-one t)
  :config
  (doom-themes-visual-bell-config)
  (doom-themes-org-config))
```

The result when using `ediff-regions-wordwise`

![Screenshot from 2020-08-04 14-06-47](https://user-images.githubusercontent.com/55086168/89263632-cf821c00-d65b-11ea-8e16-72b9057a2af8.png)

And the result with `doom-gruvbox` is clear
![Screenshot from 2020-08-04 14-09-04](https://user-images.githubusercontent.com/55086168/89263884-399ac100-d65c-11ea-8500-96792291fc21.png)

**Comment by hlissner** [comment]
Is it the same in GUI Emacs? Or just terminal Emacs?

**Comment by giaptx** [comment]
Seems problem from my terminal. I'm using `rxvt-unicode` (my customized color)

I've just tested with `terminator` look better

I discovered when using emacs -nw in `rxvt` doom-one doesn't fill background color. That why I can not have a better view

![Screenshot from 2020-08-04 14-21-54](https://user-images.githubusercontent.com/55086168/89264971-00fbe700-d65e-11ea-9a49-fb60a31d0d66.png)
LEFT: rxvt  | terminator  :RIGHT

**Comment by giaptx** [comment]
Sorry for bother you. If you have any suggestions about terminal, pls tell me. To be honest I don't like to use terminator :(

Thanks

**Comment by giaptx** [comment]
I don't know should I re-open this issue or not.
I discover that the problem is not almost come from which terminal. The issue come from emacs version.

If I use emacs-28 (master branch, I'm using origin/feature/native-comp branch exactly) the doom-one is correct colors.
But if I use emacs version <= 27, doom-one is not correct color. We can easy detect it by looking at background, the background color is not changed follow by doom-one, that why in ediff it is hard to look in my case
