### ISSUE TITLE
Interest in Solarized Light high-contrast variant?

### ISSUE THREAD

**Issue by leungbk** [hlissner/emacs-doom-themes#509]
In the Light doom-themes that I've tried, I've noticed that in a few instances where backgrounds are dark (light), the foreground text also happens to be quite dark (light), making it needlessly difficult to read.

The emacs-solarized repo has a high-contrast variant of its Light theme. Would there be interest in a high-contrast version of doom-solarized-light? If so I can try submitting at some point.

**Comment by ema2159** [comment]
It would be a nice addition, but the best way to do it is to achieve it with some custom variables inside the theme. For example, Gruvbox light has a custom variable that allows users to change between soft, medium and hard variants. This can also be done with Solarized light, adding a high-contrast custom variable.

**Comment by hlissner** [comment]
Now that #570 added `doom-solarized-dark-high-contrast`, a `doom-solarized-light-high-contrast` PR would be welcome.

As this issue isn't directly actionable I will close it, but feel free to follow up here.
