### ISSUE TITLE
Can't enable doom-plain theme

### ISSUE THREAD

**Issue by mmohammadi9812** [hlissner/emacs-doom-themes#520]
Hi there
I'm using emacs version 27.1.50 and doom-emacs version 2.0.9 and `:ui doom` is enabled. `~/.emacs.d/.local/straight/build/doom-themes/` doesn't seem to have doom-plain theme. I tried to put it in `~/.doom.d/themes/` and then load it by adding `(load-theme "doom-plain-theme" t)` to `~/.doom.d/config.el` but it shows this error:
```plain
error in process sentinel: let*: Error in private config: "config.el", (error "Invalid theme name ‘doom-plain-theme’")
```
I tried changing `custom-theme-directory`:
```elisp
(setq! custom-theme-directory (concat doom-private-dir "themes/"))
```
but it didn't seem to change anything.
Any help will be appreciated. Thanks.

**Comment by brongulus** [comment]
It doesn’t show up because doom pins packages to specific commits. Unpin the doom-themes package in packages.el and run doom sync. You don’t need to change the theme directory.

**Comment by mmohammadi9812** [comment]
Yes, it solved the problem. Thank you. Closing issue
