### ISSUE TITLE
[Question] Doom Horizon theme has different background-color in no-window-system mode compared to the window mode

### ISSUE THREAD

**Issue by usetheplatform** [hlissner/emacs-doom-themes#527]
Hello, everyone.

I am wondering, why `doom-horizon` has different background color in `emacs -nw` mode compared to the default one and how can I adjust it back? Please, see the screenshots.
<img width="1183" alt="image" src="https://user-images.githubusercontent.com/58340039/96432213-3fd91c00-120d-11eb-89f2-f0863e8775e8.png">

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/58340039/96431821-ba556c00-120c-11eb-9e07-18b9b3da70f7.png">

Steps to reproduce:

1. Set doom theme in config.el `(setq doom-theme 'doom-horizon)`.
2. Open emacs in no window mode `emacs -nw`.
3. Open emacs in the windowed mode.
4. Observe the difference.

**Comment by hlissner** [comment]
This is solaire-mode trying to remap the background, but your terminal doesn't support 24-bit color. If you intend to use Emacs in the terminal you'll need to disable it:

1. Add `(package! solaire-mode :disable t)` to `~/.doom.d/packages.el`
2. Run `doom sync`
3. Restart Emacs.
