### ISSUE TITLE
Doom One comment colors

### ISSUE THREAD

**Issue by xendk** [hlissner/emacs-doom-themes#528]
I've noticed that a lot of themes (not just for Emacs) prefers to "de-highlight" comments, usually making them grey and "ghosted". My guess is (and I might be wrong here) that most theme authors consider comments as second class citizens to the code, but I think that's a mistake. Good code is mostly self-evident, requiring no comments. But when comments is needed to explain the "why" to the codes "how", or just what exactly is going on, they're just as important as the code itself, if not more.

I've used Emacs default color scheme for many years, and while unsexy in many ways, it did have the advantage of coloring comments in "Firebrick".

So I've come up with the following override for doom-one I'll submit for your consideration:

```elisp
  ;; Make comments starker colors.
  (set-face-foreground 'font-lock-comment-face (doom-lighten 'cyan .5))
  (set-face-foreground 'font-lock-doc-face (doom-lighten 'cyan .25))
```

**Comment by hlissner** [comment]
Most, if not all, of our themes have a `doom-X-brighter-comments` option. [Including doom-one](https://github.com/hlissner/emacs-doom-themes/blob/master/themes/doom-one-theme.el#L14-L17).

**Comment by xendk** [comment]
> Most, if not all, of our themes have a doom-X-brighter-comments option. Including doom-one.

Well, I'm not fan of changing the background too. Think it drowns out hl-line and the cursor.

Oh right, I should be using `custom-set-faces`. BTW, is there a way to adjust the pseudo-colors like `bg` and `bg-alt`, or do I have to figure out how they're used and change the individual faces? I seem to be getting old, I'd like some more contrast.

**Comment by hlissner** [comment]
> Well, I'm not fan of changing the background too. Think it drowns out hl-line and the cursor.

Sorry, I forgot to mention. Themes also have a `doom-*-comment-bg` variable. It defaults to the value of `doom-*-brighter-comments`. When set to `t` comments are made brighter by changing their background. 

This will give you brighter comments without the background:

```elisp
(setq doom-one-brighter-comments t
      doom-one-comment-bg nil)
```

> is there a way to adjust the pseudo-colors like bg and bg-alt

I'm afraid not without copying the them, making your local adjustments, and loading that instead.

**Comment by xendk** [comment]
Oh, hmm... Still darker than the code, but aesthetically pleasing. I'll give it a try and see. When comparing I still think it's a tad too dark, but my colors are pretty screaming, so there might be a bit of Stockholm syndrome yet.

> I'm afraid not without copying the theme, making your local adjustments, and loading that instead.

Ah, OK. That seems a bit overkill now that I've seemed to have nailed down the ones i need to fix.
