### ISSUE TITLE
How can I get a background colour to use it in a case definition

### ISSUE THREAD

**Issue by paaguti** [hlissner/emacs-doom-themes#529]
Hi,

I'm loading the doom-themes using `use-package` and I'm trying to customise some faces. I currently have this

```
:custom-face
  (tab-line ((t (:inherit mode-line :box (:line-width 6 :color "#323845")))))
```

but I would line to get the `:color` definition from the background of the `mode-line` face defined by the theme

Is that possible?

**Comment by hlissner** [comment]
> but I would line to get the :color definition from the background of the mode-line face defined by the theme
>
> Is that possible?

Sorry for the late response. You can get the mode-line background with either:

1. `(doom-color 'modeline-bg)`
2. `(face-background 'mode-line)`

Hope that helps!
