### ISSUE TITLE
Colours for Level 2 and Level 3 headings in doom-gruvbox are the same in org-mode

### ISSUE THREAD

**Issue by lunik1** [hlissner/emacs-doom-themes#535]
The colours for Level 2 and Level 3 headings in `doom-gruvbox` are the same in `org-mode`. There are some colours unused for readings - e.g. magenta - which could be used instead and would help to differentiate at a glance. There has been some discussion previously on changing the `doom-gruvbox` theme in `org-mode` in #452, but this would be a less comprehensive change.

`doom-gruvbox-light` is not affected.

**Comment by hlissner** [comment]
As of 41e170e the third org level in gruvbox now uses magenta. I'm not sure if this is the best choice, but it at least makes the two levels distinct of each other. Thanks for bringing it to my attention!
