### ISSUE TITLE
tab in tab-line-mode doesn't show correctly in inactive buffer

### ISSUE THREAD

**Issue by mdbergmann** [hlissner/emacs-doom-themes#538]
See screenshot.
This happens for pretty much all of the Doom themes.

<img width="372" alt="Bildschirmfoto 2020-11-09 um 18 12 02" src="https://user-images.githubusercontent.com/2143978/98573596-5415b380-22b7-11eb-8311-e82dfd81e0ba.png">

**Comment by hlissner** [comment]
As of 7576beb we now have some reasonable defaults for tab-line's faces, which should resolve this. Let me know if that isn't the case and I'll reopen this. Thanks for bringing it to my attention!
