### ISSUE TITLE
'error Invalid face weight t'

### ISSUE THREAD

**Issue by iburunat** [hlissner/emacs-doom-themes#542]
I'm getting this error:

`Error in package--load-files-for-activation: (error Invalid face weight t)`

when running line "`(load-theme 'doom-one t)`" in my init.el.

The whole bit refering to doom-themes is as follows:

```elisp
(require 'doom-themes)

(setq doom-themes-enable-bold t    
 doom-themes-enable-italic t) 

(load-theme 'doom-one t) ; THIS LINE GIVES ERROR
(doom-themes-neotree-config)
(doom-themes-org-config)
```

## System Information
+ Emacs version: 26.3 (9.0)
+ Emacs Distro: Prelude
+ Operating System: Catalina

Any help appreciated, thanks!

**Comment by hlissner** [comment]
I cannot reproduce this, and the error doesn't seem to be related to doom-themes.

Please produce a backtrace from the error message. It will help determine where it's coming from.

Either:

+ Start Emacs with `emacs --debug-init`
+ Or do `M-x toggle-debug-on-error`, then create the error.

**Comment by iburunat** [comment]
I'm closing this because the error is gone after restarting Emacs :/ I can't trace back the cause now. 
Will reopen if it happens again to follow up. Thank you.
