### ISSUE TITLE
With solarized theme doom-modeline does not show change of Evil Insert and Normal mode

### ISSUE THREAD

**Issue by sieman** [hlissner/emacs-doom-themes#547]
## What happened?
If I using a a modal editing keybinding system like evil-mode or xah-fly-keys then
shows the doom-modeline with doom-one theme a status for insert and normal mode.

A big dot:
-  in green indicates normal mode
-  in blue indicates insert mode

If you are using doom-solarized (dark or light) theme the big dot is always green.

## What did you expect to happen?
When using doom-solarized theme i expect that the modeline shows with diffrent colors normal and insert mode.

## Steps to reproduce
1. use modal editing keybinding system
2. use solarized-theme dark or light
3. toggle between insert and normal mode

## System Information
+ Emacs version: 27.1
+ Emacs Distro: Doom Emacs
+ Operating System: MacOS
+ Installed commit of doom-themes: 74ebd778571a2ba2a490d45a3f4161ea7251e050

**Comment by hlissner** [comment]
Sorry for the late response: as of b0457da this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
