### ISSUE TITLE
Poor contrast for inactive modeline

### ISSUE THREAD

**Issue by avkoval** [hlissner/emacs-doom-themes#55]
Hi,

Thanks for good theme! I have only one issue with default emacs - inactive modeline has the same color as background, making it difficult to visually distinguish.

![](http://scr.ua2web.com/avk/ss_20170509174551_kWnoLmbtzOAH0H0hQvkJ.png)

**Comment by hlissner** [comment]
You can fix this by setting:

```emacs-lisp
(setq doom-one-brighter-modeline t)
```

Sadly, I haven't come up with a reliable way to make this the default in the case the user doesn't use `doom-buffer-mode`.

**Comment by avkoval** [comment]
Does not really help yet :-( From dark themes, only for doom-tomorrow-night the background color color for modeline-inactive is different from background color, for all other current themes:
- doom-molokai
- doom-vibrant it is not.
The problem is only for active frame - in inactive frame all is well. It also depends on where cursor is.

## Inactive frame (all is well)

![](http://scr.ua2web.com/avk/ss_20170516062344_NLtoLKZ2Nwbj1pwaJPoG.png)

## Active frame (cursor at bottom window)

![](http://scr.ua2web.com/avk/ss_20170516062515_LPfVO9c1E6MDw8l8fSgj.png)

## Inactive frame (cursor at top window)

![](http://scr.ua2web.com/avk/ss_20170516062550_0lYFhUIXTPw4C8UIInxs.png)

**Comment by avkoval** [comment]
Hi Henrik,
yes, looks better. Problem disappeared for doom-one and doom-tomorrow-night. Please fix for:
 
- doom-molokai

Padded modeline also looks well.

**Comment by hlissner** [comment]
Sorry for the delay. After the recent upload, molokai should look slightly different (and this issue should be fixed). Can you confirm?

**Comment by avkoval** [comment]
Yes, all is well now. THanks @hlissner  ;-)
