### ISSUE TITLE
Changing region highlight in doom-nord makes highlightted item in Ivy hard to read

### ISSUE THREAD

**Issue by onnyyonn** [hlissner/emacs-doom-themes#550]
## What happened?
It's possible to change the colour of the highlighted region in doom-nord by changing `doom-nord-region-highlight` to `'frost` or `'snowstorm`. This makes highlighted item in Ivy unreadable because of light text on light background.

## Steps to reproduce
1. `(setq doom-theme 'doom-nord)` and `(setq doom-nord-region-highlight 'snowstorm)` in `config.el`.
2. `doom sync` and restart emacs.
3.  Press `M-x`

![Screenshot_20201213_171310](https://user-images.githubusercontent.com/963267/102011548-e1db3780-3d6a-11eb-9b70-670d7643fc7c.png)

## System Information
+ Emacs version: 27.1
+ Emacs Distro: Doom Emacs

**Comment by ema2159** [comment]
Please tell me if the fix applied is sufficient

**Comment by onnyyonn** [comment]
Yes, this works as expected now. Thanks.
