### ISSUE TITLE
How to disable auto paired characters

### ISSUE THREAD

**Issue by apapsch** [hlissner/emacs-doom-themes#551]
Emacs is auto inserting matching parentheses and other characters even in fundamental mode. I was looking around, trying some promising settings, but auto pairing still happens. I am doomed. Please gurus, help me find a way to disable auto pairing.

## System Information
+ Emacs version: 27.1
+ Emacs Distro: Doom Emacs
+ Operating System: Arch (EndeavourOS derivate)
+ Installed commit of doom-themes: 74ebd77

**Comment by ymarco** [comment]
Did you see https://github.com/hlissner/doom-emacs/blob/develop/docs/faq.org#how-to-disable-smartparensautomatic-parentheses-completion?
```emacs-lisp
(remove-hook 'doom-first-buffer-hook #'smartparens-global-mode)
```

**Comment by apapsch** [comment]
I overlooked that, thanks! (Also I don't know why I filed the issue here in emacs-doom-themes.)
