### ISSUE TITLE
Treemacs theme must use root-open & root-closed icons

### ISSUE THREAD

**Issue by Alexander-Miller** [hlissner/emacs-doom-themes#553]
I have recently introduced 2 distinct icons for open and closed root nodes, so the treemacs theme must now define icons for both `root-open` and `root-closed` extensions instead of the one icon for the `root` extension as it does now.

Without it you get problems like https://github.com/Alexander-Miller/treemacs/issues/752, so it's a must-have. I'll add a temporary workaround, but it'll be removed again in a month or two.

**Comment by ema2159** [comment]
Thanks for letting us know! I will try to prioritize this issue.
