### ISSUE TITLE
Doom themes and gnus cause strange emacs lock up

### ISSUE THREAD

**Issue by mcraveiro** [hlissner/emacs-doom-themes#554]
## What happened?

Hi, thanks very much for a great theme, which I use daily. I have a very strange problem, which I am sure is related to my configuration, but I cannot figure out how to get to the bottom of it. For some reason, about a month ago or so, I started to experience a hard emacs lock up whenever I try to start gnus under the doom theme. The error happens just as gnus is about to draw the screen with the articles, etc.

To debug this, I have tried:

- toggling debug on error: nothing comes up.
- kill ```USR1``` and ```USR2```: emacs does not respond to anything other than ```SIGKILL```.

If I start emacs without doom themes, using an old style theme or with ```-Q``` for example, then gnus works just fine.

Any ideas that could help investigate this problem are greatly appreciated.

## What did you expect to happen?

Gnus to start.

## Steps to reproduce

At present all I need to do is to start emacs with a doom theme enabled, and then start gnus. The lock up happens.

## System Information

+ Emacs version: GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.23, cairo version 1.16.0) of 2020-11-07, modified by Debian
+ Emacs Distro: Prelude
+ Operating System: Debian Testing
+ Installed commit of doom-themes: doom-themes-20201220.836,  3761dfce75144e49789b6576e187acd82e2731ee

**Comment by mcraveiro** [comment]
In case its useful, my init related to doom. Note that treemacs is disabled due to this issue [1].

```
(prelude-require-package 'doom-themes)

;; Load the theme (doom-one, doom-molokai, etc); keep in mind that each theme
;; may have their own settings.
(load-theme 'doom-one t)

;; Enable flashing mode-line on errors
(doom-themes-visual-bell-config)

;; Enable custom neotree theme (all-the-icons must be installed!)
; (doom-themes-neotree-config)
;; or for treemacs users
;; (doom-themes-treemacs-config)

;; Corrects (and improves) org-mode's native fontification.
(doom-themes-org-config)

(prelude-require-package 'doom-modeline)
(doom-modeline-mode 1)
```

[1] https://github.com/Alexander-Miller/treemacs/issues/752

**Comment by hlissner** [comment]
Is this still an issue? I cannot reproduce this in vanilla Emacs or vanilla Doom Emacs, so I'm inclined to suspect Prelude or your private config.

**Comment by mcraveiro** [comment]
Sadly, I still have this issue. However, I have decided to move away from prelude into a literate config of my own, and hopefully that will also help me get to the bottom of this issue. Given no one else seems to have it, seems there is not much of a point in keeping this ticket open. Thanks very much for your time.
