### ISSUE TITLE
[Gruvbox-dark] Inactive modeline blends with the buffer background.

### ISSUE THREAD

**Issue by ocelaiwo** [hlissner/emacs-doom-themes#556]
I think it would be nice if the inactive modeline color in gruvbox-dark would differ a little from the color of the buffer background, because now when you split horizontally the two windows contents kind of blend in, especially if their contents are the same programming language or similar. Maybe add an option to have the colors slightly different?

## System Information
+ Emacs version: 27.1
+ Emacs Distro: None
+ Operating System: Arch
+ Installed commit of doom-themes:

**Comment by ema2159** [comment]
Please post a screenshot of the issue to have clear what you're referring to.

**Comment by hlissner** [comment]
Sorry for the late response. As of https://github.com/hlissner/emacs-doom-themes/commit/49c5334bd4846ea2f4d0a300f192a7cf7a878967 this should be resolved. Let me know if that isn't the case and I'll reopen the issue. Thanks for bringing it to my attention!
