### ISSUE TITLE
Improved syntax highlighting for certain themes?

### ISSUE THREAD

**Issue by zetashift** [hlissner/emacs-doom-themes#559]
## What happened? 
Compared to the screenshots in the repo, my syntax highlighting differs just a lil bit. I'd like to know how I can maybe change this: doom-material has certain niceties to the syntax highlighting compared to other themes I tried, like `doom-snazzy` or `doom-monokai-pro`. I would like to add these niceties to other themes too, but how do I do that?
Material has `type="text"` highlighted nicely:
![material](https://user-images.githubusercontent.com/1857826/103930244-bad01580-511e-11eb-8309-38952abed97d.png)
Molokai hasn't: 
![molokai](https://user-images.githubusercontent.com/1857826/103930249-bc014280-511e-11eb-91b1-3d12e8576559.png)

## What did you expect to happen?
Nothing! But I would like to have the same kind of highlighting of JSX attributes like `material`, the screenshots of snazzy for example even show the difference too.

## Steps to reproduce
1.Choose desired theme
2. ...
3. ...

## System Information
+ Emacs version: 28.0.50 (nativecomp)
+ Emacs Distro: Doom Emacs
+ Operating System: Ubuntu
+ Installed commit of doom-themes: 3761dfce75144e49789b6576e187acd82e2731ee

**Comment by ema2159** [comment]
Hi! Question; are you using the [jsx-mode](https://github.com/felipeochoa/rjsx-mode) package?

**Comment by zetashift** [comment]
I am, atleast I activated it by adding this:
`(add-to-list 'auto-mode-alist '("\\.js\\'" . rjsx-mode))`
to my `config.el`

**Comment by ema2159** [comment]
No problem man! We've all been there. I'd only need to tweak the rjsx-mode faces to make them look better.

**Comment by zetashift** [comment]
Looking at the screenshots: https://github.com/hlissner/emacs-doom-themes/tree/screenshots aren't they using rjsx-mode already?

**Comment by zetashift** [comment]
@ema2159 sorry for the ping, got any tips on how I can help?

**Comment by einSelbst** [comment]
@zetashift I'm a noob at this (too?), however, if you are interested in the topic in general this might be of interest: http://ergoemacs.org/emacs/elisp_syntax_coloring.html and the following posts.

**Comment by ema2159** [comment]
@zetashift sorry for the delay! Check the last tweaks I made! If you feel they are sufficient please close the issue but don't hesitate to tell me anything else you think it's worth addressing.

**Comment by zetashift** [comment]
@ema2159 hey thanks a lot!! How do I upgrade emacs-doom-themes? I tried `doom upgrade` but the syntax highlighting didn't change.
Am using the `doom-one` theme.

**Comment by ema2159** [comment]
Probably you'll just have to wait for the Melpa update so give it a couple of hours!

Yeah, those variables change the respective rjsx faces, but they do it inside Doom themes macro. If you wanted to change those faces inside your config you'd need to use the `(set-face-attribute...` function.

What would be the purpose of the PR you're mentioning?

**Comment by zetashift** [comment]
> Probably you'll just have to wait for the Melpa update so give it a couple of hours!
> 
> Yeah, those variables change the respective rjsx faces, but they do it inside Doom themes macro. If you wanted to change those faces inside your config you'd need to use the `(set-face-attribute...` function.
> 
> What would be the purpose of the PR you're mentioning?

Oh, I think I misunderstoond sorry! I thought your changes would only apply to the faces of `doom-one`. So the PR would change it for themes other than doom-one.

Also I went to do some digging on my own and saw that the `themes` Discord channel uses `custom-set-faces!`.

**Comment by zetashift** [comment]
The faces work fine and I learned a thing or two about emacs themes! Thank you very much :D.
