### ISSUE TITLE
[doom-theme-base.el] Adding a new face: ctrlf

### ISSUE THREAD

**Issue by gspe** [hlissner/emacs-doom-themes#561]
Would be nice if you can add new faces for ctrf https://github.com/raxod502/ctrlf package.
It need faces for:
```
ctrlf-highlight-activ
ctrlf-highlight-passive
ctrlf-highlight-line
```
Thank you

**Comment by hlissner** [comment]
These faces already [inherit from other faces](https://github.com/raxod502/ctrlf/blob/master/ctrlf.el#L267-L277) that we've already styled in `doom-themes-base.el`. Would you mind offering screenshots to show what's wrong with them? Or being more specific about how they could be improved?
