### ISSUE TITLE
Question: How can I increase the contrast in my terminal prompt with doom-wilmersdorf and vterm

### ISSUE THREAD

**Issue by ig-perez** [hlissner/emacs-doom-themes#563]
Thanks for maintaining this package!

## What happened?
Low contrast in the username part of my terminal prompt when using `vterm` with `doom-wilmersdorf`:
![image](https://user-images.githubusercontent.com/33359427/106341793-81498080-626c-11eb-8cdb-83feb1581387.png)

`Alacritty` is on the left with a theme applied by PyWal. At the right `doom-wilmersdorf` theme. As you can see the username is hard to read.

## What did you expect to happen?
Better contrast in the terminal prompt

## Steps to reproduce
1. Install `vterm`
2. Use `doom-wilmersdorf` theme
3. Setup your terminal prompt `PS1`

## System Information
+ Emacs version: 27.1
+ Emacs Distro: None
+ Operating System: Fedora 33
+ Installed commit of doom-themes: 18cddefb3c8b9da63086496142ad6756f0bc9167

**Comment by hlissner** [comment]
It's hard to tell without knowing what ansi codes your prompt is putting out, but if you're using evil, you could try to determine what faces are involved: switch to normal mode, place your cursor over the hard-to-read bits and invoke `M-x describe-char`. At the bottom of the popup that appears it will list all faces at point.

I'll guess that that is `vterm-color-red` and=or `vterm-color-magenta`. You can tweak them with:

```elisp
(custom-set-faces
  `(vterm-color-red ((t (:foreground "black")))))
```

And play around with that until you get the effect you want, but frankly, I think the best solution would be to tweak your prompt, or use a prompt theme that matches your Emacs theme as close as possible.

As our issue tracker isn't for how-to/config questions I'll close this, but feel free to follow up here.
