### ISSUE TITLE
Taking theme's color to use it elsewhere

### ISSUE THREAD

**Issue by souew** [hlissner/emacs-doom-themes#567]
I want to use bg and bg-alt declarations elsewhere in my config to make init.el portable cross all themes.

`(set-face-attribute 'minibuffer-prompt nil :background nil :foreground nil :box '(:line-width 3 :color "bg"))`

This should make a 3 pixel box around "M-x" prompt with the color of "bg" (which basically makes it invisible, acting as a padding)
Unfortunately I get - Unable to load color "bg". Can I get around of this?

**Comment by ymarco** [comment]
```emacs-lisp
`(:line-width 3 :color ,(doom-color 'bg))
```

**Comment by souew** [comment]
@ymarco Thank you!
