### ISSUE TITLE
Low contrast with doom-nord-light and marginalia/selectrum

### ISSUE THREAD

**Issue by ig-perez** [hlissner/emacs-doom-themes#573]
Thanks for maintaining this package!

## What happened?
After latest update it is hard to read the candidates provided by Marginalia, for example:
![image](https://user-images.githubusercontent.com/33359427/108735964-228bc580-74ff-11eb-8b59-a1c33119ef33.png)

## What did you expect to happen?
Better contrast with the provided text in the candidates list.

## Steps to reproduce
1. Install Marginalia and Selectrum
2. `M-x` and write `pack`
3. See candidates list, the word `pack` has almost vanished.

## System Information
+ Emacs version: 27.1
+ Emacs Distro: None
+ Operating System: Fedora 33 (Wayland)
+ Installed commit of doom-themes: 3fb14b4f82dd1c1d1059f8fd99e30af41e04157b

**Comment by Emiller88** [comment]
For me locally:
![image](https://user-images.githubusercontent.com/20095261/108948350-3ef04500-765a-11eb-8ff9-420547e19b25.png)

Can you double-check that you're on 3fb14b4? I'm using this branch on my fork https://github.com/hlissner/doom-emacs/pull/4664 if you could try it with that also.

**Comment by Emiller88** [comment]
Okay, I rebased the branch onto dev, and now I've got the same thing.

**Comment by jmorag** [comment]
I've opened a PR with the fix. Apologies for not testing more with light themes @ig-perez!

**Comment by ig-perez** [comment]
> I've opened a PR with the fix. Apologies for not testing more with light themes @ig-perez!

No need to apologize @jmorag Thanks a lot for your time.
