### ISSUE TITLE
doom-themes-treemacs-config breaks treemacs resizing

### ISSUE THREAD

**Issue by mruegenberg** [hlissner/emacs-doom-themes#575]
When I run `doom-themes-treemacs-config` in my init.el, resizing of the Treemacs buffer (via `M-x treemacs-toggle-fixed-width`) does not work any more, no matter where I click.

The culprit appears to be this: 

```
(defun doom-themes-hide-modeline ()
  (setq mode-line-format nil))
```

in `doom-themes-ext-treemacs.el`. If I remove the line adding that function as a hook, it works.

**Comment by hlissner** [comment]
It doesn't make much sense that unsetting the mode-line would tamper with treemacs' ability to resize itself. Please restore `doom-themes-hide-modeline` and check \*Messages\* for errors or warnings after trying to resize treemacs. `C-h e` will open this buffer.

**Comment by mruegenberg** [comment]
Hello,
I've investigated some more. The actual resizing (via `C-x {` and `C-x }`) does work after switching to the treemacs buffer via `C-x o`. The part that actually doesn't work is resizing via the mouse pointer. It simply doesn't show the typical resizing pointer style you get when moving the pointer to the separator between two adjacent buffers.

Could hiding the modeline be made optional?

**Comment by hlissner** [comment]
Sorry for the tremendously later response: after looking into this again I realize that my earlier suspicions were correct: your behavior has nothing to do with the visibility of the mode-line, _but_ Treemacs fixes the width of its window by default. You can toggle this fixed-width off by pressing `t w` (or `M-x treemacs-toggle-fixed-width`), the `C-x {` / `C-x }` will work.

You can make this the default behavior with:

```elisp
(add-hook 'treemacs-mode-hook #'treemacs-toggle-fixed-width)
```

If for some reason this still doesn't fix your issue, you can prevent the mode-line by being hidden with

```elisp
;; after you call `doom-themes-treemacs-config'
(with-eval-after-load 'treemacs
  (remove-hook 'treemacs-mode-hook #'doom-themes-hide-modeline))
```

But as this would simply be masking an underlying issue, it's not appropriate to upstream.

In any case, thanks for bringing it to my attention!
