### ISSUE TITLE
Text remains highlighted after replace

### ISSUE THREAD

**Issue by beojan** [hlissner/emacs-doom-themes#577]
After replacing text with `:%s` or in a visual selection with `:'<,'>s` whatever was highlighted remains visibly highlighted. `ESC` doesn't clear this, only a dummy `:%s` command that I then cancel instead of executing clears the selection.

**Comment by hlissner** [comment]
This is not an issue with this package, but with [evil-traces](https://github.com/mamapanda/evil-traces/issues). A recent update to evil broke some weeks ago. I am not aware of any fixes. Please raise this issue there.
