### ISSUE TITLE
Wrong Color in Emacs Terminal Mode Running in WSL2

### ISSUE THREAD

**Issue by mangkoran** [hlissner/emacs-doom-themes#581]
## What happened?
Different theme color (in this case `Nord`) in `emacs -nw` running in WSL2 in Windows Terminal.

Arch WSL2:
![image](https://user-images.githubusercontent.com/57625126/112102519-5b44ba80-8be3-11eb-80fe-afce0b1334a0.png)

For comparison, in native Arch:
![image](https://media.discordapp.net/attachments/746683130483572817/823805232827334706/unknown.png?width=705&height=630)

## What did you expect to happen?
Nord Theme is applied as it should be
## Steps to reproduce
1. [Install WSL2](https://docs.microsoft.com/en-us/windows/wsl/install-win10l)
2. [Install ArchWSL](https://github.com/yuk7/ArchWSL)
3. Install `emacs` and `doom`

## System Information
+ Emacs version: 27.1
+ Emacs Distro: Doom
+ Operating System: Arch Linux on Windows 10 x86_64 20H2
+ Kernel: 5.4.72-microsoft-standard-WSL2
+ Terminal: Windows Terminal v1.6.10571.0
+ Installed commit of doom-themes: I don't really know how to check this, but as I installed `doom-themes`, the latest in repo is [4199e74
](https://github.com/hlissner/emacs-doom-themes/commit/4199e74db170200995ee8dfbb55ffae004d6e219)

**Comment by mangkoran** [comment]
I think this issue is related to terminal emulator used. The WSL one used Windows Terminal. Arch used kitty. Both are running `emacs -nw`

**Comment by hlissner** [comment]
Sorry for the late response. This seems like a Windows Terminal configuration issue. Unfortunately, I don't have a Windows system or environment available to me at the moment, and I know little about the WSL environment, much less the Windows Terminal, so I don't know how best to debug this. You may have better luck asking on /r/emacs or a larger community.
