### ISSUE TITLE
`doom-gruvbox` minibuffer looks bad

### ISSUE THREAD

**Issue by kartikdc** [hlissner/emacs-doom-themes#587]
## What happened?

This is a personal opinion so feel free to close the issue if this is deemed unnecessary.

The minibuffer in `doom-gruvbox` used to have same or similar (can't recall which exactly) background colour as the buffers. Recently I upgraded to the latest commit and it uses a darker variant of the base background colour for the minibuffer. I think it looks out of place as the colour is too dark. The following is a screenshot for the `hard` variant of the theme:

![](https://cdn.discordapp.com/attachments/406554085794381833/832532757438660618/screenshot-20210416082529.png)

## What did you expect to happen?

I would like the minibuffer background to be a bit brighter. Using `#1d2021` even for the dark variant is fine for me. Right now it looks a bit out of place.

## Additional Notes

If people want this change I can file a PR for this. Sorry for polluting the issue queue with a subjective opinion.

## Steps to reproduce
1. Install doom-emacs
1. In `config.el`, do `(setq doom-theme doom-gruvbox)`
2. Start Emacs

## System Information
+ Emacs version: 27.1
+ Emacs Distro: Doom Emacs
+ Operating System: Ubuntu 20.04
+ Installed commit of doom-themes: `4199e74db170200995ee8dfbb55ffae004d6e219`

**Comment by kartikdc** [comment]
For reference, this is how it used to before:

![screenshot-20210416091144](https://user-images.githubusercontent.com/77477066/115002037-e99a1c80-9ec1-11eb-8590-92943db0281e.png)

**Comment by hlissner** [comment]
Not a bug. This is the work of the [solaire-mode](https://github.com/hlissner/emacs-solaire-mode) plugin. [How to disable packages in Doom Emacs](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#disabling-packages).
