### ISSUE TITLE
doom-plain theme does not differentiate broken links

### ISSUE THREAD

**Issue by brunoperdigao** [hlissner/emacs-doom-themes#588]
Most themes use different color to identify broken links as the example below:
![image](https://user-images.githubusercontent.com/57102715/115078175-992cba00-9ed5-11eb-933a-aa2fc867da0f.png)

But in `doom-plain` they are displayed with the same (or almost the same) color:
![image](https://user-images.githubusercontent.com/57102715/115078404-f3c61600-9ed5-11eb-9c67-70bd9c9974a4.png)

It would be nice if there was a bit more contrast between them.

**Comment by ema2159** [comment]
Do you happen to know which is the face for the broken links?

**Comment by hlissner** [comment]
I'm going to wager @brunoperdigao is a Doom Emacs user, since native Org doesn't do this, but [Doom does](https://github.com/hlissner/doom-emacs/blob/develop/modules/lang/org/config.el#L464-L472). If so, it's using the `error` face.

**Comment by brunoperdigao** [comment]
Yes, this example was created in Doom Emacs

**Comment by hlissner** [comment]
As of 5bef894 and https://github.com/hlissner/doom-emacs/commit/4dceae18269629e99dd51a3d0b6826a84a256133 (in doom-emacs), this should be fixed. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
