### ISSUE TITLE
Wrong(?) Color Usage

### ISSUE THREAD

**Issue by mangkoran** [hlissner/emacs-doom-themes#591]
## What happened?
`doom-gruvbox` theme uses `#262626` as background/bg0.
![image](https://user-images.githubusercontent.com/57625126/115890152-36b05c80-a487-11eb-87a5-1a298a286115.png)
Using `powertoys` color picker to see the applied background color.

## What did you expect to happen?
`doom-gruvbox` theme uses `#282828` as background/bg0, as declared in [doom-gruvbox-theme.el](https://github.com/hlissner/emacs-doom-themes/blob/master/themes/doom-gruvbox-theme.el).

## Steps to reproduce
1. Run `emacs -nw`
2. `M-x load-theme doom-gruvbox`

## System Information
+ Emacs version: Emacs 27.2
+ Emacs Distro: Doom Emacs
+ Operating System: WSL2, ArchWSL
+ Terminal Emulator: Windows Terminal
+ Installed commit of doom-themes: 4199e74db170200995ee8dfbb55ffae004d6e219

**Comment by ema2159** [comment]
This is likely to be a terminal-related issue. I don't use Emacs in the terminal but as far as I know, the range of colors that the terminal emulator supports is limited, and when a color is missing it renders another color close to the one requested. If I am not wrong some terminal emulators can be configured to render these colors, but you'd have to look that up.

**Comment by hlissner** [comment]
This is indeed a tty issue. It's approximating #282828 to the nearest color in 8-bit space. Our 8-bit colors aren't hand-picked from a 8-bit palette, so we leave it to Emacs/the terminal to approximate. Unfortunately, there is no acceptable fix for this, so I will close this.

But it can be worked around on your end by either:

+ Using a 24-bit color-capable terminal [and set it up to use 24-bit colors](https://github.com/hlissner/doom-emacs/blob/805810b95f21327a3144baaa8cf536660d2a17ac/modules/os/tty/README.org#true-color-and-italic-support)

+ Or customize your background by hand:

```elisp
(custom-set-faces
  `(default ((t (:background nil)))))
```

This will force Emacs to use your terminal's background as its background. (You may need to set `solaire-default-face` too if you use [solaire-mode](https://github.com/hlissner/emacs-solaire-mode/issues)).

Hope that helps!
