### ISSUE TITLE
Solarized theme

### ISSUE THREAD

**Issue by MrNilDev** [hlissner/emacs-doom-themes#593]
Hi, I've got some basic questions..
I'm trying to change gruvbox's theme a bit, but doom-gruvbox dark theme doesn't implement as well as solarized theme does: 
![which-key](https://user-images.githubusercontent.com/61497342/116773416-8df79380-aa6a-11eb-8b94-e16a9cf877dd.png)
I wonder how solarized theme implemented which-key colors, I'm looking at the theme's file but there isn't anything related to which-key, but there is in gruvbox theme. My questions is how solarized theme did that? I wanna achieve that too with gruvbox theme

**Comment by hlissner** [comment]
All of our themes are derived from [doom-themes-base.el](https://github.com/hlissner/emacs-doom-themes/blob/master/doom-themes-base.el). If a theme doesn't have its own settings for a certain face/group of faces, then check that file.

**Comment by MrNilDev** [comment]
Good job :+1:

**Comment by MrNilDev** [comment]
But can i say how are they "derived" ? 
i mean which line in the gruvbox theme ?

**Comment by hlissner** [comment]
> But can i say how are they "derived" ?

Each doom theme is defined with `def-doom-theme`, which merges the faces in of the current theme (e.g. doom-gruvbox) with the faces in `doom-themes-base.el`.

> i mean which line in the gruvbox theme ?

[This line.](https://github.com/hlissner/emacs-doom-themes/blob/master/themes/doom-gruvbox-theme.el#L30)

> and also what are these which-key-command-description-face ? are these variables or what ? How can i bring the help page for them ?

These are faces. You can use `M-x describe-faces` to look up faces and their documentation. Remember that the package (which-key in this case) must be loaded for those faces to be visible.

[Entry in Emacs manual about faces.](https://www.gnu.org/software/emacs/manual/html_node/emacs/Faces.html).
