### ISSUE TITLE
Theme setup

### ISSUE THREAD

**Issue by MrNilDev** [hlissner/emacs-doom-themes#594]
How can I achieve this syntax using doom themes?
![image](https://user-images.githubusercontent.com/61497342/116779599-8a750400-aa8c-11eb-90fc-ebe9443aa169.png)
 currently it looks like this: 
![image](https://user-images.githubusercontent.com/61497342/116779744-5fd77b00-aa8d-11eb-8319-d3d4c40de34e.png)
I changed some of the colors and type's color in doom-gruvbox theme. but don't know how i can highlight `usleep` and `cout`

**Comment by hlissner** [comment]
Has nothing to do with this package. `c++-mode` does not highlight these keywords, so you'll have to do so yourself.

```lisp
(font-lock-add-keywords
   'c++-mode `((,(regexp-opt '("usleep" "cout")) . font-lock-keyword-face)))
```

[Emacs manual: font-lock-mode](https://www.gnu.org/software/emacs/manual/html_node/emacs/Font-Lock.html)

-----

Please post questions like these on [r/emacs](https://reddit.com/r/emacs) in the future. Our issue tracker is a place for bugs and feature requests, not how-to help.
