### ISSUE TITLE
Gruvbox ivy theme

### ISSUE THREAD

**Issue by ItsNilDev** [hlissner/emacs-doom-themes#599]
Hey! Why is ivy's theme in doom-gruvbox broken? I want to have the same color as it had like for example: 
![1 pic](https://user-images.githubusercontent.com/61497342/118477567-0d9c8800-b724-11eb-8932-066008bfed6d.png)

![image](https://user-images.githubusercontent.com/61497342/118477547-08d7d400-b724-11eb-9f68-272748606bd0.png)
As you see here the orange and yellow color is gone, but I want to keep them.
in another theme that's like
![image](https://user-images.githubusercontent.com/61497342/118477831-5fdda900-b724-11eb-8bb6-2e0655c43215.png)
How can I achieve this?

**Comment by MrNilDev** [comment]
Any Idea ?

**Comment by ema2159** [comment]
Why does your Ivy looks different from mine?
![image](https://user-images.githubusercontent.com/17773218/119228301-aa8b6680-bb12-11eb-9227-891c471b9898.png)

**Comment by ItsNilDev** [comment]
how is it different ?

**Comment by ema2159** [comment]
Could you please do M-x list-faces-display and then go to the ivy section?

**Comment by ItsNilDev** [comment]
Sure, Here: 
![image](https://user-images.githubusercontent.com/61497342/119249394-8466d480-bbad-11eb-9f95-290d502cab49.png)
I think my "current match" is the problem

**Comment by ema2159** [comment]
With the last update of doom-themes, this would be the one for me:
![image](https://user-images.githubusercontent.com/17773218/119255035-d9104c80-bbb9-11eb-8dea-ac5e2ff5d65b.png)
Are you using the latest version of Doom themes? Also, check that you don't have any manual customizations loaded which may also be a possibility.

**Comment by ItsNilDev** [comment]
`M-x pkg-info-package-version RET doom-modeline` says that I'm using the version `20210419.958` I don't know if it's up to date or not. I did `package-refresh-contents` tho

**Comment by ItsNilDev** [comment]
@ema2159 Am I using the wrong version ? What's the version you're using ?

**Comment by ema2159** [comment]
The version is correct, however, there seems to be some customization applied somewhere else which is messing up your theming. Here is my customization screen:

![image](https://user-images.githubusercontent.com/17773218/119459871-61b7f580-bd3e-11eb-96a5-0b3d91a91e0b.png)

**Comment by ItsNilDev** [comment]
It seems like I had some lines in my init.el file that was generated by the emacs itself. I deleted all of them and now it works fine! 
Thanks for your helps!
