### ISSUE TITLE
color scheme request

### ISSUE THREAD

**Issue by bigardone** [hlissner/emacs-doom-themes#60]
Hi! First of all thanks for the theme, I simply love it :)
Would it be possible requesting a color scheme based on Nova for vim? https://trevordmiller.com/projects/nova
If you don't have the time for it, I could work on a PR for adding it following this basic color list described here https://github.com/trevordmiller/nova-colors/blob/master/src/index.js
What do you think?

**Comment by hlissner** [comment]
That is a lovely colorscheme! So I'd be happy to include it.

I've got others in the pipeline however, so it may take me a while to get to it. That basic color-list PR would be appreciated though, and would go a long way to speed the process up.

**Comment by bigardone** [comment]
Awesome! I'll start working on that PR then :)
Cheers!
