### ISSUE TITLE
Theme Request: spacemacs theme (dark and light)

### ISSUE THREAD

**Issue by quarkquartet** [hlissner/emacs-doom-themes#611]
## What happened?
Installed spacemacs theme from [https://github.com/nashamri/spacemacs-theme](url). But there is some incompatibility with Doom configuration. e.g. the org-mode bullet is ugly.
## What did you expect to happen?
Display spacemacs theme.
## Steps to reproduce
1. In doom emacs, write this spacemacstheme package in package.el.
2. Load spacemacs theme in config.el

## System Information
+ Emacs version: 27.2, emacs-plus
+ Emacs Distro: Doom Emacs
+ Operating System: MacOS
+ Installed commit of doom-themes: Version updated in Jun.1

**Comment by hlissner** [comment]
This seems like something that should be reported to and addressed in the spacemacs-theme project, which is a complex theme with many settings. Porting it over would be needlessly duplicating code and work, and this project doesn't exist simply to "fork" themes to correct trivial differences. If you have grievances with the spacemacs theme, please report them there in detail. Thanks for bringing it to my attention and sorry for the trouble!
