### ISSUE TITLE
doom-one-light shadow face is not is the same as default

### ISSUE THREAD

**Issue by andreyorst** [hlissner/emacs-doom-themes#615]
## What happened?

`shadow` face is supposed to be a bit more grayish, based on what I've observed from other themes in this package, yet for `doom-one-light` it has the same foreground as `default` face.

Looking into code, I see that `doom-one-light` defines it's `fg` facr as:

https://github.com/hlissner/emacs-doom-themes/blob/ee16ff277e9ae054aec34239c1ca702bff202f50/themes/doom-one-light-theme.el#L53

And its `shadow` face as:

https://github.com/hlissner/emacs-doom-themes/blob/ee16ff277e9ae054aec34239c1ca702bff202f50/themes/doom-one-light-theme.el#L70

given that `shadow` uses `base5`:

https://github.com/hlissner/emacs-doom-themes/blob/ee16ff277e9ae054aec34239c1ca702bff202f50/doom-themes-base.el#L18

## What did you expect to happen?

`shadow` face uses more dimmed face, as per `doom-one`

## Steps to reproduce
1. M-x load-theme RET doom-one-light RET
2. M-: (equal (face-attribute 'default :foreground) (face-attribute 'shadow :foreground)) RET

## System Information
+ Emacs version: GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.29, cairo version 1.17.4) of 2021-05-30
+ Emacs distro: None
+ Operating system: Fedora 34
+ Installed commit of doom-themes: 90ef722
+ Which theme are you using: `doom-one-light`

**Comment by hlissner** [comment]
As of 0819fa9 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by verhovsky** [comment]
@hlissner the background of the entire emacs window is now grey for me.
