### ISSUE TITLE
[Solarized-light] Bg_alt color is incorrect 

### ISSUE THREAD

**Issue by shaunsingh** [hlissner/emacs-doom-themes#618]
## What happened?

The background alt color for the solarized light theme is incorrect. The official site (https://ethanschoonover.com/solarized/) states the alternate background color should be #eee8d5, while in the doom theme (https://github.com/hlissner/emacs-doom-themes/blob/master/themes/doom-solarized-light-theme.el) the color is defined as #FFFBEA

Proper color for the theme: 
<img width="392" alt="image" src="https://user-images.githubusercontent.com/71196912/120849049-9187aa00-c543-11eb-9e15-d8802fce4a17.png">
 
Current color: 
<img width="382" alt="image" src="https://user-images.githubusercontent.com/71196912/120849099-a106f300-c543-11eb-9f7e-4291767e69da.png">

## What did you expect to happen?

Ideally the color should be duller and match the official color palette. 

## Steps to reproduce
1. Download Emacs/install doom emacs 
2. set the theme to solarized light 
3. restart emacs and look at the echo minibuffer and the tabline

## System Information
Not sure how this is relevant but
+ Emacs version: Emacs-plus@28 (latest)
+ Emacs distro: Doom emacs
+ Operating system: macOS 11.4
+ Installed commit of doom-themes: latest (updated with `doom upgrade` and `doom sync`)
+ Which theme are you using: solarized light

**Comment by hlissner** [comment]
As of b2c0ea0 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
