### ISSUE TITLE
[Nord Dark] Centaur-tabs displaying incorrectly 

### ISSUE THREAD

**Issue by shaunsingh** [hlissner/emacs-doom-themes#619]
## What happened?

Upon loading a file in doom emacs, the tabline is displaying incorrectly. 

<img width="195" alt="image" src="https://user-images.githubusercontent.com/71196912/121062357-f7b63c00-c792-11eb-8a71-207ac57518f5.png">

## What did you expect to happen?

The tabline should display correctly as it does with other themes 

## Steps to reproduce
1. Open doom emacs 
2. Enable centaur tabs in `init.el`
3. `Doom Sync` and open a file

## System Information
+ Emacs version: emacs-plus@28 with native-comp
+ Emacs distro: Doom-Emcas
+ Operating system: MacOS 11.4
+ Installed commit of doom-themes: Latest
+ Which theme are you using: Doom-nord

**Comment by hlissner** [comment]
This was fixed in 5d30984, but I haven't yet bumped the pin for the `doom-themes` package in Doom Emacs yet.

To unpin the package:added `(unpin! doom-themes)` to `~/.doom.d/packages.el`, then run `doom sync -u` and restart Emacs.
