### ISSUE TITLE
Accented characters not correctly represented in Win10 terminal version

### ISSUE THREAD

**Issue by ronnac** [hlissner/emacs-doom-themes#625]
## What happened?
Accented characters are replaced by other characters

## What did you expect to happen?
Accented characters are correctly reproduced

## Steps to reproduce
1. In a win10 DOS command prompt run "emacs -nw"
2. Open any file that contains accented characters

Note:
a) When running simply "emacs" there is no problem (but I need the terminal version to work).
b) In config.el, when I set the doom theme to a theme that doesn't exist, I will get a warning on startup "theme not found", however the characters are represented correctly. However the evil layer doesn't work.
c) in gitbash SDK-64, when I run "winpty emacs -nw" the characters are displayed correctly. Gitbash has several environment variables / paths set differently.
d) I tried several doom themes, to no avail

## System Information
+ Emacs version:  28.0.50 native compiled
+ Emacs distro: Doom Emacs
+ Operating system: Windows 10
+ Installed commit of doom-themes: latest
+ Which theme are you using:  doom-one

**Comment by hlissner** [comment]
This is not a doom-themes issue and there isn't enough information to go on. Please report this on https://github.com/hlissner/doom-emacs/issues if you are still experiencing this and if it is a Doom issue.
