### ISSUE TITLE
[regression] doom-one and doom-vibrant not rendering background correctly

### ISSUE THREAD

**Issue by shunlir** [hlissner/emacs-doom-themes#631]
## What happened?
![image](https://user-images.githubusercontent.com/14887081/124305229-6078b480-db97-11eb-93e9-917a5b217888.png)

## What did you expect to happen?
![image](https://user-images.githubusercontent.com/14887081/124305299-78e8cf00-db97-11eb-8b93-c1c07c248352.png)

## Steps to reproduce
1. configure to use `doom-vibrant`: `(setq doom-theme 'doom-vibrant)`
2. start doom-emacs, edit some file

## System Information
+ Emacs version: 27.1 
+ Emacs distro: Doom Emacs 
+ Operating system: mosh from Windows to Linux 
+ Installed commit of doom-themes: b2c0ea0
+ Which theme are you using: doom-vibrant 

## More information
from https://www.reddit.com/r/DoomEmacs/comments/nvrvoz/the_doomone_theme_is_not_rendered_correctly_in/
> I have met the problem on Konsole, too.
> 
> Because of this line https://github.com/hlissner/emacs-doom-themes/blob/b2c0ea0f0778a6ea85b87e1b87916572e98e1fe7/themes/doom-one-theme.el#L52,
> 
> "brightblack", which is the default background, is rendered as gray on Konsole, perhaps on other terminal emulators, too.
> 
> It's back to black after setting the 256 bg color to nil
> 
> You should open an issue at https://github.com/hlissner/emacs-doom-themes/issues
> 
> Edit: it's due to this commit https://github.com/hlissner/emacs-doom-themes/commit/7ce9be332fa6b5f805ee54c47b65e07060aec37c

**Comment by hlissner** [comment]
As of 5221b06 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
