### ISSUE TITLE
Terminal mode colors are broken

### ISSUE THREAD

**Issue by foxfromabyss** [hlissner/emacs-doom-themes#634]
### What did you expect to happen?

![alt text](https://media.discordapp.net/attachments/849352606853103687/852148778981916672/unknown.png?width=627&height=470)

### What actually happened?

![alt text](https://media.discordapp.net/attachments/406554085794381833/852144474628685824/unknown.png?width=627&height=470)

### Describe your attempts to resolve the issue

Reverting this https://github.com/hlissner/doom-emacs/commit/335b6f9abbe3be7ba147f8d3113ac77f83d15ff7 commit fixes the issue, but I haven't had the time to find the exact offending commit in one of the packages. 

### Steps to reproduce

1. Open Emacs on latest commit in terminal mode with `doom-one` theme selected
2. Open any file :) 

### System Information

https://pastebin.com/NUUxtQ6r

**Comment by rburchell** [comment]
I guess https://github.com/hlissner/emacs-doom-themes/issues/631 is the underlying issue then.

**Comment by hlissner** [comment]
As of 5221b06 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
