### ISSUE TITLE
Org-priority face doesn't inherit height from underlying faces

### ISSUE THREAD

**Issue by jacksondm33** [hlissner/emacs-doom-themes#644]
## What happened?
Org-priority face doesn't inherit height from org-level-*, which causes org-priority text to have a different height on headlines (when using variable font height for headlines)

## What did you expect to happen?
Doom-themes-org-config sets org-todo and org-headline-done to inherit height from underlying faces (org-level-*), so it would make sense to also do this for org-priority.

## Steps to reproduce
1. Configure org-level-* faces to use a different height from default.
2. Use org-priority in a headline (ex. * TODO [#A] Foo)

## System Information
+ Emacs version: 28.0.50
+ Emacs distro: None
+ Operating system: Arch
+ Installed commit of doom-themes: Latest from MELPA
+ Which theme are you using: doom-vibrant

**Comment by hlissner** [comment]
I cannot reproduce this.

![image](https://user-images.githubusercontent.com/510883/127802074-ec71f43d-029e-4a3d-bfb7-cd89d170ea55.png)

Used this to set 2nd level headings to a non-standard size, color, and italicized.

```elisp
(custom-set-faces!
  `(org-level-2 :foreground ,(doom-color 'blue) :slant italic :height 1.8))
```

It correctly inherited :slant and :height, since `:foreground` is the only attribute for `org-priorities` that was specified. 

Are you sure you're on the latest version of Org (9.5)? I'm sporting a commit that is within 2 weeks old.

**Comment by jacksondm33** [comment]
I am using Org version 9.4.4 (Org 9.5 hasn't been released yet?). I'm going to keep messing around to see if I can find the cause of the issue, but I have already tested removing all other org configuration. If you do have time, could you check if org-todo face also has this issue if you don't run `(doom-themes-org-config)`. For me, it does, and running this fixes the issue (not for org-priority, though).

**Comment by jacksondm33** [comment]
Well I managed to put together some code that fixed the issue for me. It seems that the original `org-font-lock-add-priority-faces` function defines the `face` property of the target text, which overrides anything done by font lock mode. I'm still pretty new to working with emacs lisp, so this is probably not the best way to fix this, but it did work:
```
(defvar jacksondm33/current-org-priority-face)

(defun jacksondm33/org-font-lock ()
  (let ((org-priority (format org-heading-keyword-regexp-format org-priority-regexp)))
    (setq org-font-lock-extra-keywords (append (org-delete-all '((org-font-lock-add-priority-faces)) org-font-lock-extra-keywords)
    '((jacksondm33/org-font-lock-add-priority-faces (1 jacksondm33/current-org-priority-face prepend)))))))

(defun jacksondm33/org-font-lock-add-priority-faces (limit)
  (when (re-search-forward org-priority-regexp limit t)
    (setq jacksondm33/current-org-priority-face (org-get-priority-face (string-to-char (match-string 2))))))

(add-hook 'org-font-lock-set-keywords-hook #'jacksondm33/org-font-lock)
```
