### ISSUE TITLE
doom-vibrant not a first class citizen theme?

### ISSUE THREAD

**Issue by cremacs** [hlissner/emacs-doom-themes#65]
Hi,

I'm using spacemacs. When I try to load doom-one in the 'dotspacemacs-themes variable, there's no problem. But when I do the same with doom-vibrant, it is treated as an unrecognized package and goes to install (which of course doesn't work). Do you have any advice about how to fix this? Thanks.

**Comment by hlissner** [comment]
Could you check the value of `custom-theme-load-path` and let me know if it contains the path to the doom-theme? (`M-x describe-variable RET custom-theme-load-path`)

If not, it is likely that something, elsewhere in your config is modifying this variable. To get around this, you can:

```emacs-lisp
(require 'doom-themes)
(require 'doom-vibrant-theme)
(load-theme 'doom-vibrant t)
```

**Comment by ekaschalk** [comment]
I can confirm the same situation with (the most recent dev branch of) spacemacs. Doom theme is on the loadpath and the load-theme snippet doesn't work. It can be gotten around with a call to `cycle-spacemacs-theme` in the user-config but this is not ideal.

**Comment by hlissner** [comment]
(Sorry for the late reply)

@ekaschalk It's possible spacemacs has its own theme-loading code that runs later in the startup process; this would override any custom effort of yours. I'm not a spacemacs users to know for certain, but from the documentation, I suspect this will work:

```emacs-lisp
(require 'doom-themes)
(setq-default dotspacemacs-themes '(doom-one))
```

Let me know how that fares.
