### ISSUE TITLE
doom-themes font size looks very big in org-mode 

### ISSUE THREAD

**Issue by hbsd** [hlissner/emacs-doom-themes#651]
Hello
I use doom-one theme. doom themes looks great in all modes except org-mode.
How can I use regular font size and face in org-mode. I'd really appreciate if you help me to do that.
Thanks.

**Comment by hlissner** [comment]
Our themes don't control font size. This is something you control in your private config, when setting your fonts and customizing your faces. As I know nothing about your config I can't help you with specifics.

In any case, I'll close this since this isn't an issue with this project.

**Comment by hbsd** [comment]
Will you please look at this:

A regular file:
![2021-08-22-213313_1024x768_scrot](https://user-images.githubusercontent.com/78821889/130363695-0ca5c745-6f4f-446b-8319-403bf853caeb.png)

org-mode file:
![2021-08-22-213411_1024x768_scrot](https://user-images.githubusercontent.com/78821889/130363709-bbd00349-51fd-4b00-b0e2-605e24aa3db8.png)

I can't disable bold formatting text...

some of my code:

;; default font size and font face
(set-frame-font "Hack 13" nil t)

;; disable bold text
(set-face-bold-p 'bold nil)

;; default theme (doom)
  (require 'doom-themes)
  ;; Global settings (defaults)
  (setq doom-themes-enable-bold t    ; if nil, bold is universally disabled
        doom-themes-enable-italic t) ; if nil, italics is universally disabled
  ;; Load the theme (doom-one, doom-molokai, etc); keep in mind that each
  ;; theme may have their own settings.
  (load-theme 'doom-one t)
  ;; Enable flashing mode-line on errors
  (doom-themes-visual-bell-config)
  ;; Enable custom neotree theme
  (doom-themes-neotree-config)  ; all-the-icons fonts must be installed!
  ;; Corrects (and improves) org-mode's native fontification.
  (doom-themes-org-config)
