### ISSUE TITLE
*Bold* sometimes changes the color when `doom-themes-enable-bold` is `nil`

### ISSUE THREAD

**Issue by jeep** [hlissner/emacs-doom-themes#667]
### What would you like to know?

In org mode, when I type `*bold*` the color is changed to white, even when the normal color would not be white. Is it possible to have bold maintain the non-bold color similar to how underline and italics do? I've tried looking at the code, but I don't see anything obvious.

![bold-is-white](https://user-images.githubusercontent.com/89500/136272107-ee4b0042-9009-46ec-abb5-736132ffe8e8.png)

Thanks.

**Comment by jeep** [comment]
doom-one

**Comment by iyefrat** [comment]
This is pretty weird, I can sometimes reproduce this, but not reliably. I think it might have something to do with setting `doom-themes-enable-bold` on and off.

**Comment by iyefrat** [comment]
> I need to set doom-themes-enable-bold to nil to get bold to turn on
yeah this i can't reproduce

**Comment by iyefrat** [comment]
Ah, guess my issue was that setting theme variables and reloading the theme mid-session isn't robust.
