### ISSUE TITLE
Support new emacs built-in font face: mode-line-active

### ISSUE THREAD

**Issue by miangraham** [hlissner/emacs-doom-themes#689]
### What did you expect to happen?

Emacs master added a new modeline face, `mode-line-active`, in this commit two weeks ago: https://git.savannah.gnu.org/cgit/emacs.git/commit/?id=3f843b25dc96867043feebb1d928bde4a7a777a3

When using doom-themes, they should modify this face as appropriate.

### What actually happened?

As is, `mode-line-active` inherits from the default `variable-pitch` face and doom-themes don't touch it. This results in a different, unexpected font for the active mode line after upgrading emacs.

### Describe your attempts to resolve the issue

I believe it's appropriate for themes to set face `mode-line-active` to the same thing as `mode-line` or just modify the inheritance. Not an active theme tweaker so thoughts appreciated. Going to experiment but wanted to get a tracking issue out there.

As a temporary workaround I've just grabbed the face settings from `mode-line` and thrown them into a `custom-set-faces` in my personal config:

```elisp
(custom-set-faces `(mode-line-active ((t (:background "#68217A" :foreground "#f4f4f4" :box (:line-width 4 :color "#68217A"))))))
```

This gets me fixed visually while waiting for theme support.

### Steps to reproduce

1. Install a version of emacs at least as recent as https://git.savannah.gnu.org/cgit/emacs.git/commit/?id=3f843b25dc96867043feebb1d928bde4a7a777a3
2. Apply a theme such as `(load-theme 'doom-dark+ t)`
3. `M-x describe-face` on faces `mode-line`, `mode-line-inactive`, and `mode-line-active`.
4. Observe that only the former two are modified. Specifically `mode-line-active` retains its inheritance of `variable-pitch` while `mode-line` and `mode-line-active` do not. This results in a visually different font.

### Package commit

96edc0ceb864b7d72218e58c8e9272cd96e5712c

### System Information

* NixOS
* GNU Emacs from source using the pgtk branch and nativeComp enabled, built from https://git.savannah.gnu.org/cgit/emacs.git/commit/?id=ea8bb59c1b393e57046fec698fbb498f08bc70cc

**Comment by miangraham** [comment]
Here's a general purpose workaround that just tweaks the inheritance. Should work for anyone seeing the same change to variable pitch.

```elisp
(set-face-attribute 'mode-line-active nil :inherit 'mode-line)
```

**Comment by hlissner** [comment]
This issue should now be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by miangraham** [comment]
Late shout back that it works great here! Cheers!
