### ISSUE TITLE
company-template-field missing

### ISSUE THREAD

**Issue by gicmo** [hlissner/emacs-doom-themes#72]
Hey,
the `company-template-field` (`company-template.el`, line 26) is missing.
Its default is:
```elisp
(defface company-template-field
  '((((background dark)) (:background "yellow" :foreground "black"))
    (((background light)) (:background "orange" :foreground "black")))
  "Face used for editable text in template fields."
  :group 'company)
```
It doesnt look to bad but I guess it would be nicer if it was properly themed. I let you pick the color since I dont think I am qualified ;)
![emacs_doom_company_template](https://cloud.githubusercontent.com/assets/2040/26728668/4aeaa0bc-47ab-11e7-835a-1ddfcadc7ed5.png)

**Comment by hlissner** [comment]
Good catch. I'll address this soon.
