### ISSUE TITLE
linum-relative-current-face and linum-highlight-face

### ISSUE THREAD

**Issue by jupl** [hlissner/emacs-doom-themes#75]
There was a change made such that `linum-relative-current-face` now inherits from `linum-highlight-face`, but `linum-highlight-face` is undefined. This breaks `linum-relative-current-face` as it does not get styled anymore.

**Comment by hlissner** [comment]
That should do it. Let me know if you still have the problem.

**Comment by jupl** [comment]
That sure did. Thank you!
