### ISSUE TITLE
Styling orgmode header size / background color.

### ISSUE THREAD

**Issue by teesloane** [hlissner/emacs-doom-themes#77]
Hey! Love your themes. This is a small aesthetic question — nothing is broken; if you have time to answer would love any feedback! 

I usually have my org mode looking like this:

<img width="411" alt="screenshot 2017-06-19 19 18 19" src="https://user-images.githubusercontent.com/12987958/27309859-646395c2-5524-11e7-950c-4f1e050eb4a7.png">

My org mode in this theme looks like this:
<img width="476" alt="screenshot 2017-06-19 19 20 05" src="https://user-images.githubusercontent.com/12987958/27309873-797f9384-5524-11e7-8a53-af0d510c5761.png">

I haven't had much luck googling for any tips, but was using this snippet before to make all my org headings the same size. I found this snippet somewhere deep in the intern and Don't really know if it's actually doing something / can't find the source haha

``` lisp
  (defun my/org-mode-hook ()
    ;; Stop the org-level headers from increasing in height relative to the other text.
    (dolist (face '(org-level-1
                    org-level-2
                    org-level-3
                    org-level-4
                    org-level-5))
      (set-face-attribute face nil :weight 'semi-bold :height 1.0)))
  (add-hook 'org-mode-hook 'my/org-mode-hook)

```

Thanks for any tips, and for sharing your hard work. Your themes definitely make using spacemacs a lot more pleasant for myself.

**Comment by hlissner** [comment]
Sorry for the late reply! There are a few issues here, let me try to address them all:

+ The background of headers seems unnaturally harsh. I've justed pushed a fix to mitigate that.
+ If you only want your headers to be the same size, you don't need to modify all 5 header levels, just level 1 (it's the only one that this theme changes). i.e. this is sufficient:

  ```emacs-lisp
  (set-face-attribute 'org-level-1 nil :height 1.0)
  ```

  **However**, this must be done *after* `doom-nova` is loaded. I am not a spacemacs user so I don't know when during startup that happens. If the above doesn't work, try:

  ```emacs-lisp
  (defun my/org-mode-hook ()
    (set-face-attribute 'org-level-1 nil :height 1.0))
  (add-hook 'org-load-hook #'my/org-mode-hook)
  ```
+ If you want to get rid of header backgrounds too, modify that `set-face-attribute` line like so:

  ```emacs-lisp
  (set-face-attribute 'org-level-1 nil :height 1.0 :background nil)
  ```
+ If you want to keep background colors, but would like the color to extend to the end of the screen, you need `org-fontify-whole-heading-line` set:

  ```emacs-lisp
  (setq org-fontify-whole-heading-line t
        ;; I've included these to maximize compatibility to doom-one
        org-fontify-done-headline t
        org-fontify-quote-and-verse-blocks t)
  ```

  These can be placed anywhere.

---

Let me know if that solves your problem!

**Comment by teesloane** [comment]
Wow, amazing! Thanks so much helping out with such detail. I will enjoy customizing my setup this weekend and report back in shortly.

cheers!

**Comment by teesloane** [comment]
@hlissner Ok, just popped open Org-mode and I've seen some success! All headers are the same size!

Thanks for helping out!
