### ISSUE TITLE
Doom airline themes

### ISSUE THREAD

**Issue by AnthonyDiGirolamo** [hlissner/emacs-doom-themes#78]
No issue here. Just wanted to say thanks for the great themes!

I added modeline themes for doom-one and doom-molokai to https://github.com/AnthonyDiGirolamo/airline-themes

### airline-doom-one-theme

![airline-doom-one-theme](https://github.com/AnthonyDiGirolamo/airline-themes/raw/master/screenshots/airline-doom-one-theme.png)

### airline-doom-molokai-theme

![airline-doom-molokai-theme](https://github.com/AnthonyDiGirolamo/airline-themes/raw/master/screenshots/airline-doom-molokai-theme.png)

**Comment by hlissner** [comment]
Fantastic work, they look great!

**Comment by YuSuu** [comment]
i use airline and doom-one both  XD

**Comment by Red-Portal** [comment]
@hlissner  @AnthonyDiGirolamo  How can I have that square shape in the screenshot?

**Comment by AnthonyDiGirolamo** [comment]
`(setq powerline-default-separator nil)`

There are a bunch of options besides the arrow and nothing. See https://github.com/milkypostman/powerline/blob/master/powerline.el#L75 for all valid options.

**Comment by Red-Portal** [comment]
@AnthonyDiGirolamo  Thanks. Hope you could add some guidance for customization in the README
