### ISSUE TITLE
tabbar support

### ISSUE THREAD

**Issue by fbob** [hlissner/emacs-doom-themes#79]
First, many thanks for this gorgeous theme :)

It would be wonderful if this theme support tabbar mode too.
In the same way  as Atom's One Dark themes for example.

Anyway many many thanks for your excellent job !

**Comment by hlissner** [comment]
Thank you for the kind words!

I've pushed a few improvements for tabbar support, but I do not use tabbar, so I'm unable to test it.

However, if you want tabbar to look more like Atom's tabs, here is something to get you started:

```emacs-lisp
(defun make-xpm-bar (color height width)
  "Create an XPM bitmap of a bar."
  (propertize
   " " 'display
   (let ((data (make-list height (make-list width 1)))
         (color (or color "None")))
     (create-image
      (concat
       (format "/* XPM */\nstatic char * percent[] = {\n\"%i %i 2 1\",\n\". c %s\",\n\"  c %s\","
               (length (car data))
               (length data)
               color
               color)
       (apply #'concat
              (cl-loop with idx = 0
                       with len = (length data)
                       for dl in data
                       do (cl-incf idx)
                       collect
                       (concat "\""
                               (cl-loop for d in dl
                                        if (= d 0) collect (string-to-char " ")
                                        else collect (string-to-char "."))
                               (if (eq idx len) "\"};" "\",\n")))))
      'xpm t :ascent 'center))))

(defun my-tabbar-display-tab (tab)
    (let ((label (if tabbar--buffer-show-groups
                     (format "[%s]" (tabbar-tab-tabset tab))
                   (format "%s" (tabbar-tab-value tab))))
          (bar-color "#51afef")
          (bar-height 25)
          (bar-width 3)
          (selected-p (eq tab (tabbar-selected-tab (tabbar-current-tabset)))))
      (concat (when (and (display-graphic-p) selected-p)
                (make-xpm-bar bar-color bar-height bar-width))
              " "
              (if tabbar-auto-scroll-flag
                  label
                (tabbar-shorten
                 label (max 1 (/ (window-width)
                                 (length (tabbar-view
                                          (tabbar-current-tabset)))))))
              " ")))

(setq tabbar-tab-label-function #'my-tabbar-display-tab)
```

This should give you something like this:

![screenshot of modified tabbar](https://i.snag.gy/4oOlJe.jpg)

**Comment by wpcarro** [comment]
I'm new to `tabbar`, but the screenshot provided here compelled me to install it and check it out. Is there anything I need to do besides execute `tabbar-mode` to produce the screenshot @hlissner provided above?

Here's what I have currently, which is... well unusable

<img width="330" alt="screen shot 2017-06-29 at 10 42 25 am" src="https://user-images.githubusercontent.com/13058701/27693539-b59df582-5cb7-11e7-863a-a927305878b1.png">

Here are two pertinent snippets from my config:

```lisp
(use-package doom-themes
  :ensure t
  :config
  (setq doom-themes-enable-bold nil
        doom-themes-enable-italic nil)
  (load-theme 'doom-one)
  (doom-themes-visual-bell-config)
  (doom-themes-neotree-config))
```

and 

```lisp
(use-package tabbar
  :ensure t
  :config
  (tabbar-mode))
```

**Comment by fbob** [comment]
Whaouu !
Even better than I would have expected :)

I'm using Spacemacs distribution but I unfortunately can't reproduce the same behavior and got something like the screenshot below. 
![tabbar-zoom](https://user-images.githubusercontent.com/8211124/27706107-91a41d24-5d10-11e7-809d-2cfdcbbc4568.png)
I messed up something for sure but can not see where for now.
Where did you put your code in your dotemacs ?
Sorry to disturb you with my manifest incompetence :)

**Comment by fbob** [comment]
Did I say incompetent :)
Just put the (tabbar-mode 1) before ... yes I'm as bad as that
And voila :+1: 

![spectacle a29436](https://user-images.githubusercontent.com/8211124/27709610-0cc58c5c-5d1d-11e7-87d1-435de324c6fe.png)

Many many thanks !!!

**Comment by hlissner** [comment]
I'm glad you figured it out! I'll consider this resolved.

**Comment by HumHongeKamyaab** [comment]
Is this possible for inbuilt `tab-bar-mode`?
