### ISSUE TITLE
Interested in contributing a theme

### ISSUE THREAD

**Issue by teesloane** [hlissner/emacs-doom-themes#82]
Hello!

Thanks for helping me out with [my issue](https://github.com/hlissner/emacs-doom-themes/issues/77) a little while ago!

I'm interested in trying to contribute a theme. I can't promise it will successfully happen; but am willing to try.

Curious if you could lend a hand outlining how I could get started testing this on my config. Here's what I'm thinking:

1. fork the repo
2. Move / symlink the project folder to wherever my spacemacs gets packages from).
3. I duplicate one of the themes
4. Hopefully the themes show up in Spacemacs when I try and change themes; then I load up the new one I duplicated + renamed.
5. Every time I make a change, I reload spacemacs to see how it looks?

Does that sound feasible? Just wondering if I'm missing anything big; any tools for increasing my prototyping speed. Also, happy to write docs as I go to add to describe this process so you do not have to do it more than once!

Cheers, and thanks for your awesome themes.

**Comment by hlissner** [comment]
Your workflow looks fine. I'd suggest you duplicate doom-one, since it's the most developed of the lot.

If you find yourself modifying doom-themes-common.el for whatever reason, you'll need to forcibly reload it everytime you reload the theme to see the effects, e.g.

```emacs-lisp
(defun reload-theme ()
  (interactive)
  (load "doom-themes-common.el" nil t)
  (load-theme 'doom-one t)) ;; change this to the theme you're making
```

**Comment by teesloane** [comment]
Awesome, thanks! I will stumble around for a while when I find some free time and see if I can come up with anything :)
