### ISSUE TITLE
Support for perspective mode

### ISSUE THREAD

**Issue by pavkum** [hlissner/emacs-doom-themes#85]
Hello,
  I have been using doom-themes for a while.  Thank you for the awesome work.

  I use [perspectives](https://github.com/nex3/perspective-el/blob/master/perspective.el) a lot. The [selected face](https://github.com/nex3/perspective-el/blob/master/perspective.el#L252) of perspectives uses default colors. I have done some customizations locally for doom-one. But it would be great if we get support by the theme.

**Comment by hlissner** [comment]
Thanks for the kind words!

I added the linked face. Was that the only customization perspectives needs? If so, go ahead and close this issue.

**Comment by pavkum** [comment]
@hlissner Thank you for the update. Yes I'm pretty sure we need only **selected face**. 

Closing the issue.
