### ISSUE TITLE
Support for 256 colors console mode

### ISSUE THREAD

**Issue by amoriello** [hlissner/emacs-doom-themes#89]
These are really nice themes, it would be great to also have support for people using emacs in terminal mode (with at least 256 colors).

This might also require custom palette for the terminal itself, like what we've got here for solarized:
https://github.com/altercation/solarized.

Thanks!

**Comment by amoriello** [comment]
Actually, it's already pretty good.

I'm using iterm2, and I just changing the background color to 282c34, and black to 1B2229  gives good results.

I know nothing about color scheme customisation,  but I know that iTerm2 supports Truecolor (24bits colors). I wonder how / if we can use that extra set of colors to be closer the the GUI version.

https://gist.github.com/XVilka/8346728

FYI, I found thism but this iterm scheme doesn't work well with your emacs theme.
https://github.com/sonph/onehalf

**Comment by amoriello** [comment]
So, I spent some time figuring out this colour madness in terminals.

I was thinking you could trick the terminal to give each of the 256 colors values an overriding color.
But no... looking closer to an iTerm colour scheme file, it obviously doesn't work like that.

So, I went down another path:

## Truecolor

iTerm ([and a bunch of others](https://gist.github.com/XVilka/8346728)) support "truecolor" (a.k.a 24bit colour mode).

Unfortunately, mainstream emacs (as of 25.2) doesn't provide support for 24bit colour mode yet.

Though, this patch that add support! 😋 
[emacs-25.1-rc1 24-bit color](https://gist.github.com/bsuh/bab7eeb8bda2421ac01c760c90668100) **(said to be working for 25.1 rc1, but I tried, and it applies perfectly to emacs 25.2.1 source code)**

So, rebuilding emacs with this patch did provide support for 24bit colour, and running with `ITERM_24BIT=1 emacs` fires up a beautiful emacs with your Doom one theme in my console 😍 

## Preview 256 colours vs truecolor in terminal (iTerm)

**On the left side**: Doom one theme with 256 colours (no truecolors), and iTerm background set to #282C34, and "black" set to #1B2229.

**On the right side**: Doom one theme with emacs truecolor enabled (no need to customise the terminal colours!)

<img width="1680" alt="screen shot 2017-07-23 at 11 31 08 am" src="https://user-images.githubusercontent.com/733189/28502157-0f7f4244-6fa1-11e7-9b2a-fee6bba060e0.png">

@hlissner: the mode bar still doesn't look really good in terminal though. I'll hack something to fit my needs, but it would be great to improve terminal support for the mode bar.

## Side note
I'm actually using a more complexe remote setup with mosh + tmux.
For truecolor to work, the information has to be propagated to every layers.

The screenshot above is taken in an ssh + tmux session. Note that to run emacs within tmux in truecolor mode with the patch reference above, you have to run with 
`KONSOLE_DBUS_SESSION=1 emacs` (because the way truecolors delimiter are passed by tmux).

### Tmux
Tmux >= 2.2 works fine with truecolor:

just add this line to your `.tmux.conf`:
`set-option -ga terminal-overrides ",xterm-256color:Tc"`

and verify that the support is then enabled by running:
```
#> tmux info | grep Tc
Tc: (flag) True
```

Make sure that everything is working fine (with, and witthout tmux) by running this fancy awk script

```
awk 'BEGIN{
    s="/\\/\\/\\/\\/\\"; s=s s s s s s s s s s s s s s s s s s s s s s s;
    for (colnum = 0; colnum<256; colnum++) {
        r = 255-(colnum*255/255);
        g = (colnum*510/255);
        b = (colnum*255/255);
        if (g>255) g = 510-g;
        printf "\033[48;2;%d;%d;%dm", r,g,b;
        printf "\033[38;2;%d;%d;%dm", 255-r,255-g,255-b;
        printf "%s\033[0m", substr(s,colnum+1,1);
    }
    printf "\n";
}'
```

You should see a nice and smooth gradient.

### Mosh
Mosh, on the overhand, doesn't support it yet.
Here's the issue: https://github.com/mobile-shell/mosh/issues/649

So, I went back to raw ssh...

**Comment by carlosvigil** [comment]
@amoriello Great write up, do you know if there's a way to switch colors automatically from remote? Using either the shell or vim? I've tried finding a way for the shell, but most advice is for ssh client side. I'll give vim color switching a search.

**Comment by seagle0128** [comment]
In terminal, strings are too dark in `doom-one` and other themes.
The strange thing is the strings color is normal after reloading theme.

<img width="586" alt="screen" src="https://user-images.githubusercontent.com/140797/40127910-ff1f2fca-5962-11e8-868a-29a33526cb36.png">

**Comment by seagle0128** [comment]
Thanks very much.
