### ISSUE TITLE
Change default secondary modeline color for powerline

### ISSUE THREAD

**Issue by IvanMalison** [hlissner/emacs-doom-themes#91]
Is there a reason that  powerline-active2 is set to the same color as the modeline?
```
(powerline-active2   :inherit 'mode-line)
```

Could it perhaps be set to something a little more interesting?

**Comment by hlissner** [comment]
I don't use powerline, so I did that as a reasonable default. So I tried it out and I see what you mean. I'll look into a nicer default over the weekend.

**Comment by hlissner** [comment]
Alright, tweaked it to look less bland. That said, after playing around with powerline, I think it's best that's all I do, and leave it to users to customize from there.
