### ISSUE TITLE
Customise faces using theme colours

### ISSUE THREAD

**Issue by ryankask** [hlissner/emacs-doom-themes#92]
I'd like to customise a few faces. Is it possible to access the themes' colours? For example, with the solarized theme there is a macro called `solarized-with-color-variables` that allows you to do this:

````
(solarized-with-color-variables 'dark
    (custom-theme-set-faces
      `(ivy-subdir ((,class (:foreground ,blue))))
      `(ivy-virtual ((,class (:foreground ,cyan))))))
````

Thanks for the great theme.

**Comment by hlissner** [comment]
Certainly. There's `(doom-color COLOR-NAME &optional TYPE)`:

+ `COLOR-NAME` is a symbol; any of [these letvars](https://github.com/hlissner/emacs-doom-themes/blob/master/themes/doom-one-theme.el#L36), e.g. `'red` or `'highlight`.
+ `TYPE`, a symbol, tells it which version of the color to get, e.g. `'256` or `'16`.

Examples:

```emacs-lisp
(doom-color 'red)      ; => "#ff6c6b" (16-bit)
(doom-color 'red '256) ; => "#ff6655" (8-bit)
(doom-color 'red '16)  ; => "red" (4-bit)
```

Hope that helps!

**Comment by ryankask** [comment]
Excellent! Thanks for the quick response. I missed that when looking through the code.

**Comment by ryankask** [comment]
If anyone sees this issue, I created the below macro to help override some variables. It uses `doom-themes--build-face` which proved to be very useful. I think the `--` convention means it's supposed to be private so this might break.

```elisp
(defmacro my-doom-theme-set-faces (theme-name &rest faces)
  `(custom-theme-set-faces
    ,theme-name
    ,@(mapcar #'doom-themes--build-face faces)))
```

and then I used it like this:

```elisp
(defun my-doom-one-theme-customise ()
  (my-doom-theme-set-faces
   'doom-one
   ;; base
   (cursor :background fg)
   (minibuffer-prompt :foreground fg)
   (font-lock-variable-name-face :foreground fg)
   ;; dired
   (dired-directory :foreground blue)
   ;; ivy
   (ivy-current-match :weight 'bold :background base4)
   (ivy-minibuffer-match-face-2 :foreground magenta)
   (ivy-minibuffer-match-face-3 :foreground green)
   (ivy-minibuffer-match-face-4 :foreground yellow)
   (ivy-subdir :foreground blue)
   (ivy-virtual :foreground (doom-darken fg 0.2))))
```

**Comment by hlissner** [comment]
@ryankask I like that macro so much I added `doom-theme-set-faces` to doom-themes proper! Thanks for sharing it!
