### ISSUE TITLE
Org titles change size when moved from TODO to DONE

### ISSUE THREAD

**Issue by r-darwish** [hlissner/emacs-doom-themes#93]
![screenshot from 2017-07-30 14-06-19](https://user-images.githubusercontent.com/1383193/28752785-546a751a-7530-11e7-8305-5706c55b3966.png)

P.S.
Thank for you this awesome theme

**Comment by hlissner** [comment]
This is a problem with org-mode's native fontification. I've fixed it locally, in my own config, but I decided to include it with doom-themes.

Add `(doom-themes-org-config)` to your config after you load doom-themes. It contains a number of fontification fixes/enhancements for org-mode which should resolve this issue for you.

**Comment by hlissner** [comment]
Has this fixed your issue?

**Comment by r-darwish** [comment]
Yes, it has. Thank you
